### ISSUE TITLE
NullPointerException when launching a JUnit4 test with coverage

### ISSUE THREAD

**Issue by unix-junkie** [oracle/visualvm#104]
When using both the _VisualVM Eclipse launcher_ ([v1.1.2](https://github.com/oracle/visualvm/releases/download/1.4/visualvm_launcher_u2_eclipse.zip)) together with [EclEmma](https://www.eclemma.org/) (e. g.: v3.0.1.201711142128), it's impossible to run a JUnit4 test with coverage, even when using a regular Eclipse launcher.

The problem is caused by the following NPE:

```
!ENTRY org.eclipse.core.jobs 4 2 2018-08-28 15:12:26.783
!MESSAGE An internal error occurred during: "Launching TimeZoneTest (1)".
!STACK 0
java.lang.NullPointerException
        at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:188)
        at org.eclipse.visualvm.launcher.java.VisualVMJUnitDelegate.launch(VisualVMJUnitDelegate.java:20)
        at org.eclipse.eclemma.core.launching.CoverageLauncher.launch(CoverageLauncher.java:94)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
        at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
        at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

Regular Java applications as well as _TestNG_ tests are not affected by this problem.

The issue can be worked around by uninstalling the _VisualVM launcher_.

This is a known issue -- see, for example, [Coverage As -> JUnit Test in Eclipse Oxygen reports NullPointerException](https://stackoverflow.com/questions/51377019).

**Comment by unix-junkie** [comment]
Looking at the bytecode at line 188:

```
/* 188*/                runner.run(runConfig, launch, monitor);
/* 188*/        //  258  575:aload           7
/* 188*/        //  259  577:aload           15
/* 188*/        //  260  579:aload_3         
/* 188*/        //  261  580:aload           4
/* 188*/        //  262  582:invokeinterface #740 <Method void IVMRunner.run(VMRunnerConfiguration, ILaunch, IProgressMonitor)>
```

it looks that most probably the `runner` returned from the overridden [getVMRunner(...)](https://github.com/oracle/visualvm/blob/3415bed626b7dbde5bebdee6eb82cb94ff1fcf04/integrations/eclipse/org.eclipse.visualvm.launcher.java/src/org/eclipse/visualvm/launcher/java/VisualVMJUnitDelegate.java#L34) is most probably `null`

**Comment by thurka** [comment]
Can you please test attached new version of [VisualVM Launcher](https://github.com/oracle/visualvm/files/2724859/visualvm_launcher_u3_eclipse.zip). It should fix this issue. Thanks.
