### ISSUE TITLE
NPE from HprofHeap.findReferencesFor

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#107]
Current devbuild, opening a heap dump for the first time, switching to Objects, displaying both References and GC Root details and selecting a class eventually throws a NPE:

```
java.lang.NullPointerException
	at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.findReferencesFor(HprofHeap.java:567)
	at org.graalvm.visualvm.lib.jfluid.heap.InstanceDump.getReferences(InstanceDump.java:115)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaReferencesPlugin.computeInstancesReferences(JavaReferencesPlugin.java:242)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaReferencesPlugin.access$500(JavaReferencesPlugin.java:95)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaReferencesPlugin$1.computeData(JavaReferencesPlugin.java:152)
	at org.graalvm.visualvm.heapviewer.ui.TreeTableView$1.lazilyComputeChildren(TreeTableView.java:146)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode$1.doInBackground(HeapViewerNode.java:154)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode$1.doInBackground(HeapViewerNode.java:152)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by thurka** [comment]
Fixed in trunk.
