### ISSUE TITLE
java.lang.IllegalArgumentException: JViewport.setBorder() not supported

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#110]
I opened an existing hprof dump, sorted by "Retained" and a few seconds later this exception was thrown:

```
java.lang.IllegalArgumentException: JViewport.setBorder() not supported
	at java.desktop/javax.swing.JViewport.setBorder(JViewport.java:573)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:309)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:273)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$JComponentBuilder.setupInstance(ComponentBuilders.java:300)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.WindowBuilders$JRootPaneBuilder.setupInstance(WindowBuilders.java:112)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.WindowBuilders$JRootPaneBuilder.setupInstance(WindowBuilders.java:95)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ChildrenBuilder.createInstanceImpl(ComponentBuilders.java:105)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:220)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ContainerBuilder.setupInstance(ComponentBuilders.java:260)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.WindowBuilders$FrameBuilder.setupInstance(WindowBuilders.java:176)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.WindowBuilders$FrameBuilder.setupInstance(WindowBuilders.java:148)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$InstanceBuilder.createInstance(Utils.java:221)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentBuilders$ComponentBuilder.createPresenter(ComponentBuilders.java:230)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentDetailsProvider$ComponentView.getComponent(ComponentDetailsProvider.java:216)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.ComponentDetailsProvider$ComponentView.getComponent(ComponentDetailsProvider.java:166)
	at org.netbeans.modules.profiler.heapwalk.details.jdk.ui.Utils$View$1.run(Utils.java:264)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I don't know how to reproduce this issue on demand because it doesn't seem to occur if I repeat the above steps. Hopefully the stacktrace and attached log will help.

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/2485524/messages.log)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.55]
 - JDK version: JDK 11
 - Version: 1.4.2

**Comment by jisedlac** [comment]
The exception has been thrown when trying to reconstruct UI of the application from which the heap has been dumped - the viewer has been switched to the "Windows" view. Unrelated to sorting by retained size.

By analyzing the related code it looks like the application uses reflection to modify the "border" field for a JViewport instance, which is forbidden - JViewport must always have null border.

**Comment by cowwoc** [comment]
@jisedlac The application I was dumping the heap for is IntelliJ IDEA. The "Windows" view showed a single entry: a dialog box warning that the IDE ran out of memory and prompting the user to enter a new max memory value.

Are you saying that when VisualVM enters "Windows" view it runs IDEA's code? And IDEA is using reflection to find the container for its dialog box and attempting to modify its border?

If so, I'm not sure how we can fix this sort of thing. Is there a way for us to "sandbox" the application code somehow so it doesn't see the component as having a parent?

**Comment by jisedlac** [comment]
I'm saying that the Windows view of the heap viewer tries to reconstruct the IDEA's UI from the heap dump, including all the component properties, including the invalid ones. It looks like IDEA is using reflection to set a non-null JViewport instance border.

**Comment by cowwoc** [comment]
@jisedlac What is the appropriate course of action in this case? Does it make sense to expose this exception to the end-user? If not, let's suppress it.

If it makes sense to expose this exception then you should probably add commentary in the error dialog indicating that the error was triggered by the application's UI (maybe they used reflection) instead of by VisualVM itself. Otherwise users might mistakenly believe this is an error in VisualVM.

**Comment by jisedlac** [comment]
Similar problems can occur for any other component for many reasons. VisualVM will just silently skip the failing components.

**Comment by cowwoc** [comment]
Your call though again users will have a hard time differentiating between failures in VisualVM (which require bug reports) from failures in user code (which do not). Feel free to close this issue if you are comfortable with the current situation.

**Comment by jisedlac** [comment]
Fixed according to my previous comment.
