### ISSUE TITLE
NoClassDefFoundError: java/lang/instrument/IllegalClassFormatException

### ISSUE THREAD

**Issue by 941112341** [oracle/visualvm#128]
java11, cannot start visualvm today. i tried to download another but fail also.
i used java 11 and it work fine yesterday.
this is console output:
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/instrument/IllegalClassFormatException
        at org.netbeans.MainImpl.execute(MainImpl.java:178)
        at org.netbeans.MainImpl.main(MainImpl.java:85)
        at org.netbeans.Main.main(Main.java:83)
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.IllegalClassFormatException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

so how to fixed it?

**Comment by 941112341** [comment]
and i've try use --jdkhome jdk8,, it work!! i'm curious about  what happend on my jdk11 ....

**Comment by TaoSupr** [comment]
jdk 13 failed too...

**Comment by thurka** [comment]
Without steps to reproduce this cannot be investigated. Closing until more info is available.

**Comment by h928725721** [comment]
@941112341 Has your problem been resolved? I have encountered this problem now and don't know how to solve it.

**Comment by thurka** [comment]
See GH-256 for solution.
