### ISSUE TITLE
Cannot take heap dump from application run in docker-compose on Ubuntu

### ISSUE THREAD

**Issue by stsypanov** [oracle/visualvm#173]
**Describe the bug**
Heap dump is not made

**To Reproduce**
1. Connect to local docker container with JMX
2. Click on 'Make Heap dump'
3. See error

**Expected behavior**
Heap dump is taken and available

```
java.lang.UnsupportedOperationException: DataSource already in repository: JmxApplication [id: service:jmx:rmi:///jndi/rmi://localhost:9010/jmxrmi]
	at com.sun.tools.visualvm.core.datasource.DataSourceProvider.logUnsupportedOperation(DataSourceProvider.java:231)
	at com.sun.tools.visualvm.core.datasource.DataSourceProvider.checkAdded(DataSourceProvider.java:206)
	at com.sun.tools.visualvm.core.datasource.DataSourceProvider.access$300(DataSourceProvider.java:48)
	at com.sun.tools.visualvm.core.datasource.DataSourceProvider$3.run(DataSourceProvider.java:143)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

**Comment by stsypanov** [comment]
Here's the log

[messages.txt](https://github.com/oracle/visualvm/files/4198913/messages.txt)

**Comment by AndreLouisCaron** [comment]
Did you find a workaround?

**Comment by stsypanov** [comment]
@AndreLouisCaron nope (

**Comment by omartrigui** [comment]
duplicate with https://github.com/oracle/visualvm/issues/187

**Comment by thurka** [comment]
This problem looks similar to GH-187. It should be fixed by fix for GH-187.

**Comment by RomanValov** [comment]
For those who uses visualvm on the same host with docker engine and unable to take heap dump. There is a workaround which works for local jvms (not jmx), i.e. when visualvm can detect jvm in docker as local but fails to make a heap dump. Basically visualvm fails to take a heap dump locally due to paths mismatch between host and container filesystems. The solution is to make an exact bind mount into docker container for the directory which visualvm considers to be tmpdir, so:

1) Run visualvm as:

   ```
   $ visualvm -J-Dvisualvm.tmpdir=/tmp/visualvm/
   ```

2) Add following lines to your docker-compose.yml or docker-compose.override.yml:

   ```
   services:
     my-container:
       volumes:
          - type: bind
            source: /tmp/visualvm
            target: /tmp/visualvm
            read_only: false
   ```
