### ISSUE TITLE
Taking Heap Dump does not work for tunnelled connection to a remote host

### ISSUE THREAD

**Issue by gerritgriebel** [oracle/visualvm#187]
Installed current 2.0.1 (Build 200326); platform 20191008-unknown-revn on Mac OS X (10.15.4) , x86_64 64bit and clicked button "Heap Dump" on tab "Monitor" for a JMX-connection (service:jmx:rmi://localhost:10032/jndi/rmi://localhost:10031/jmxrmi) results in "Cannot take heap dump for ....". Heap dump for local VMs works.

User directory: /Users/gg/Library/Application Support/VisualVM/2.0.1
Cache directory: /Users/gg/Library/Caches/VisualVM/2.0.1

Using /Applications/VisualVM.app/Contents/MacOS/visualvm -J-Dnetbeans.logger.console=true the following startup message is issued:

```
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
Diagnostic information
Input arguments:
        -Djdk.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home
        -Dnetbeans.default_userdir_root=/Users/gg/Library/Application Support/VisualVM
        -Dnetbeans.dirs=/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm:
        -Dnetbeans.home=/Applications/VisualVM.app/Contents/Resources/visualvm/platform
        -Xms24m
        -Xmx768m
        -Dnetbeans.accept_license_class=org.graalvm.visualvm.modules.startup.AcceptLicense
        -Dsun.jvmstat.perdata.syncWaitMs=10000
        -Dsun.java2d.noddraw=true
        -Dsun.java2d.d3d=false
        -Dorg.netbeans.core.TimeableEventQueue.quantum=360000
        -Dpolyglot.js.nashorn-compat=true
        -Dsun.misc.URLClassPath.disableJarChecking=true
        --add-exports=java.desktop/sun.awt=ALL-UNNAMED
        --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED
        --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
        --add-exports=java.desktop/sun.swing=ALL-UNNAMED
        --add-exports=jdk.attach/sun.tools.attach=ALL-UNNAMED
        --add-opens=java.base/java.net=ALL-UNNAMED
        --add-opens=java.base/java.lang.ref=ALL-UNNAMED
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.desktop/javax.swing=ALL-UNNAMED
        --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
        -XX:+IgnoreUnrecognizedVMOptions
        -Dnetbeans.logger.console=true
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/Users/gg/Library/Application Support/VisualVM/2.0.1/var/log/heapdump.hprof
```
Notice that XX:HeapDumpPath does not point to directory but to a filename.

On click of "Heap Dump" I get
```
Java HotSpot(TM) 64-Bit Server VM warning: GC locker is held; pre-heapdump GC was skipped
INFO [org.graalvm.visualvm.attach.AttachModelImpl]: takeHeapDump
INFO [org.graalvm.visualvm.jmx.impl.JmxSupport]: takeHeapDump
java.io.IOException: No such file or directory
	at sun.management.HotSpotDiagnostic.dumpHeap0(Native Method)
	at sun.management.HotSpotDiagnostic.dumpHeap(HotSpotDiagnostic.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at javax.management.StandardMBean.invoke(StandardMBean.java:405)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)
```

**Comment by thurka** [comment]
Is this "service:jmx:rmi://localhost:10032/jndi/rmi://localhost:10031/jmxrmi" remote application?

**Comment by gerritgriebel** [comment]
yes, it's a tunneled connection to a remote Java8 JVM running tomcat 7

**Comment by thurka** [comment]
> yes, it's a tunneled connection to a remote Java8 JVM running tomcat 7

This is the reason, why it does not work. JMX connection string looks like this is local application and therefor VisualVM tries to take heap dump like it is local application. For remote application there is no API we can get heap dump file from the remote machine to local host.

**Comment by gerritgriebel** [comment]
ok, I see. If there's a way for visualvm to know it's remote connection it might just hide the button or issue an error message like "Cannot take heap dump for ... (visualvm can not take heap dumps of remote JVMs)"

**Comment by thurka** [comment]
> ok, I see, thanks! If there's a way for visualvm to know it's remote connection it might just hide the button or issue an error message like "Cannot take heap dump for ... (visualvm can not take heap dumps of remote JVMs)"

We can detect that such JMX connection is in fact remote host, once the JMX connection is established. 
All this should be probably part of more complex change - such `proxy` JMX connection should be added under real remote host (not under 'Local'). Once this is done, heap dump action will behave correctly.

**Comment by gerritgriebel** [comment]
I failed to add a localhost remote server, I tried to trick it with a custom hostname in /etc/hosts for 127.0.0.1 but visualvm is too smart, it says "already monitored as Local". Anyhow, not really a problem, I just don't use the heap dump button and instead use jmap on the remote side.

**Comment by DestyNova** [comment]
I'm running into this too, I *think*. It shows up in the "Local" section, even when added via an `/etc/hosts` alias like @gerritgriebel said. However in my case I can't do anything with it -- I just see:

<img width="619" alt="Screenshot 2021-01-14 at 18 19 07" src="https://user-images.githubusercontent.com/1646628/104632068-12c5c980-5695-11eb-8982-cf2d9ef13c70.png">

**Comment by omartrigui** [comment]
@gerritgriebel @DestyNova The following process should work for you.

![add-jmx-local](https://user-images.githubusercontent.com/7053612/107132063-4aaede00-68dc-11eb-8706-a8804c24819f.png)

**Comment by omartrigui** [comment]
@gerritgriebel @DestyNova The following process should work for localhost (tunneling remote hosts)

![add-jmx-local](https://user-images.githubusercontent.com/7053612/107132063-4aaede00-68dc-11eb-8706-a8804c24819f.png)

**Comment by AndreLouisCaron** [comment]
@omartrigui Last time I tried this (almost a year ago), I could successfully establish a JMX connection to the remote host via tunneling, but attempting to take a heap dump systematically lead to an error.  Have you managed to get it working?

**Comment by janknobloch** [comment]
not working for me right now tunneling via our aws cluster.

**Comment by mikebell90** [comment]
Workaround for heap dump is installing mbeans plugin and going to the hotspot and requesting a jmx operation. Its a pita, but it works

**Comment by thurka** [comment]
I added heuristics to detect tunneled JMX application. Let us see how successful it will be.

**Comment by Dishant18** [comment]
@thurka When will these changes be released? In the [official page](https://visualvm.github.io/) I can see the latest version was released in April. Any estimated timelines for this?

**Comment by thurka** [comment]
> When will these changes be released? In the [official page](https://visualvm.github.io/) I can see the latest version was released in April. Any estimated timelines for this?

I think you can get good estimate if you take a look at previous releases at https://visualvm.github.io/releases.html
