### ISSUE TITLE
visualVM: Can not attach  to current VM

### ISSUE THREAD

**Issue by hangxie1** [oracle/visualvm#202]
When I tried to open the visualVM, it stuck at computing description. Looks at the log, it said:  can not attach to current VM. I. am using mac:
-------------------------------------------------------------------------------
>Log Session: Tuesday, June 2, 2020 at 11:39:22 AM Central Daylight Time
>System Info:
  Product Version         = VisualVM 2.0.2
  Operating System        = Mac OS X version 10.13.6 running on x86_64
  Java; VM; Vendor        = 11.0.6; Java HotSpot(TM) 64-Bit Server VM 11.0.6+8-LTS; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 11.0.6+8-LTS
  Java Home               = /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home
  System Locale; Encoding = en_US (visualvm); UTF-8
  Home Directory          = /Users/c050051
  Current Directory       = /
  User Directory          = /Users/c050051/Library/Application Support/VisualVM/2.0.2
  Cache Directory         = /Users/c050051/Library/Caches/VisualVM/2.0.2
  Installation            = /Applications/VisualVM.app/Contents/Resources/visualvm/visualvm
                            /Applications/VisualVM.app/Contents/Resources/visualvm/platform
  Boot & Ext. Classpath   =
  Application Classpath   = /Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/boot.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-modules.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util-lookup.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util-ui.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util.jar
  Startup Classpath       = /Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/org-netbeans-libs-asm.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/asm-all-5.0.1.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/org-openide-filesystems.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/core.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/core-base.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm/core/org-graalvm-visualvm-modules-startup.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm/core/locale/core_visualvm.jar
-------------------------------------------------------------------------------
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.38 20191008-unknown-revn]
	org.openide.util [9.12 20191008-unknown-revn]
	org.openide.util.ui [9.13 20191008-unknown-revn]
	org.openide.modules [7.53 20191008-unknown-revn]
	org.netbeans.api.annotations.common/1 [1.32 20191008-unknown-revn]
	org.openide.filesystems [9.15 20191008-unknown-revn]
	org.openide.awt [7.73 20191008-unknown-revn]
	org.netbeans.api.progress/1 [1.52 20191008-unknown-revn]
	org.netbeans.api.progress.nb [1.52 20191008-unknown-revn]
	org.openide.dialogs [7.47 20191008-unknown-revn]
	org.openide.nodes [7.50 20191008-unknown-revn]
	org.openide.windows [6.82 20191008-unknown-revn]
	org.netbeans.modules.editor.mimelookup/1 [1.45 20191008-unknown-revn]
	org.openide.text [6.72 20191008-unknown-revn]
	org.netbeans.api.scripting [1.2 20191008-unknown-revn]
	org.netbeans.swing.tabcontrol [1.61 20191008-unknown-revn]
	org.netbeans.swing.outline [1.39 20191008-unknown-revn]
	org.openide.explorer [6.67 20191008-unknown-revn]
	org.openide.actions [6.44 20191008-unknown-revn]
	org.netbeans.modules.queries/1 [1.48 20191008-unknown-revn]
	org.netbeans.api.templates [1.13 20191008-unknown-revn]
	org.openide.filesystems.nb [9.15 20191008-unknown-revn]
	org.openide.loaders [7.72 20191008-unknown-revn]
	org.netbeans.api.intent [1.7 20191008-unknown-revn]
	org.netbeans.api.io [1.8 20191008-unknown-revn]
	org.openide.io [1.54 20191008-unknown-revn]
	org.netbeans.swing.plaf [1.46 20191008-unknown-revn]
	org.netbeans.spi.quicksearch [1.32 20191008-unknown-revn]
	org.netbeans.libs.asm [5.8 20191008-unknown-revn]
	org.netbeans.bootstrap/1 [2.83 20191008-unknown-revn]
	org.netbeans.core.startup.base [1.67.0.1 1 20191008-unknown-revn]
	org.netbeans.core.startup/1 [1.67.0.1 20191008-unknown-revn]
	org.netbeans.modules.settings/1 [1.54 20191008-unknown-revn]
	org.netbeans.modules.sendopts/2 [2.41 20191008-unknown-revn]
	org.netbeans.modules.sampler [1.19 20191008-unknown-revn]
	org.netbeans.modules.progress.ui [1.38 20191008-unknown-revn]
	org.netbeans.modules.keyring [1.29 20191008-unknown-revn]
	org.netbeans.core/2 [3.56 20191008-unknown-revn]
	org.netbeans.modules.options.api/1 [1.50 20191008-unknown-revn]
	org.netbeans.modules.options.keymap [1.42 20191008-unknown-revn]
	org.netbeans.modules.masterfs/2 [2.60.0.2 2 20191008-unknown-revn]
	org.netbeans.modules.masterfs.ui [2.8.0.2 20191008-unknown-revn]
	org.netbeans.modules.masterfs.nio2 [1.20 20191008-unknown-revn]
	org.netbeans.libs.jna/1 [1.52 20191008-unknown-revn]
	org.netbeans.modules.masterfs.macosx [1.18 20191008-unknown-revn]
	org.netbeans.modules.keyring.fallback [1.13 20191008-unknown-revn]
	org.netbeans.modules.keyring.impl [1.29 20191008-unknown-revn]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.37 20191008-unknown-revn]
	org.netbeans.modules.autoupdate.services [1.58 20191008-unknown-revn]
	org.netbeans.modules.autoupdate.ui [1.50 20191008-unknown-revn]
	org.netbeans.modules.autoupdate.cli [1.18 20191008-unknown-revn]
	org.netbeans.core.windows/2 [2.88 20191008-unknown-revn]
	org.netbeans.modules.applemenu/1 [1.42 20191008-unknown-revn]
	org.netbeans.libs.jna.platform/1 [1.20 20191008-unknown-revn]
	org.netbeans.core.ui/1 [1.50 20191008-unknown-revn]
	org.netbeans.core.network [1.17 20191008-unknown-revn]
	org.netbeans.core.nativeaccess/1 [1.36 20191008-unknown-revn]
	org.netbeans.core.multitabs/1 [1.17.0.1 1 20191008-unknown-revn]
	org.netbeans.core.io.ui/1 [1.35 20191008-unknown-revn]
	org.graalvm.visualvm.lib.jfluid/2 [2.1 200514]
	org.graalvm.visualvm.lib.charts/2 [2.0 200514]
	org.graalvm.visualvm.lib.common/2 [2.1 200514]
	org.graalvm.visualvm.lib.profiler.api/2 [2.0 200514]
	org.graalvm.visualvm.lib.ui/2 [2.0 200514]
	org.graalvm.visualvm.uisupport/2 [2.0 200514]
	org.graalvm.visualvm.core/2 [2.1 200514]
	org.graalvm.visualvm.host/2 [2.0 200514]
	org.graalvm.visualvm.application/2 [2.0 200514]
	org.graalvm.visualvm.tools/2 [2.0 200514]
	org.graalvm.visualvm.coredump/2 [2.0 200514]
	org.graalvm.visualvm.threaddump/2 [2.0 200514]
	org.graalvm.visualvm.lib.profiler.utilities/2 [2.0 200514]
	org.graalvm.visualvm.lib.profiler.attach/2 [2.0 200514]
	org.graalvm.visualvm.lib.profiler/2 [2.1 200514]
	org.graalvm.visualvm.lib.profiler.snaptracer/2 [2.0 200514]
	org.graalvm.visualvm.profiling/2 [2.0 200514]
	org.graalvm.visualvm.lib.profiler.oql/2 [2.0 200514]
	org.graalvm.visualvm.lib.profiler.heapwalker/2 [2.0 200514]
	org.graalvm.visualvm.heapviewer/2 [2.0 200514]
	org.graalvm.visualvm.heapdump/2 [2.0 200514]
	org.graalvm.visualvm.sampler.truffle/2 [2.0 200514]
	org.graalvm.visualvm.sampler/2 [2.0 200514]
	org.graalvm.visualvm.sa/2 [2.0 200514]
	org.graalvm.visualvm.modules.startup/2 [2.0 200514]
	org.graalvm.visualvm.profiler/2 [2.0 200514]
	org.graalvm.visualvm.charts/2 [2.0 200514]
	org.graalvm.visualvm.application.views/2 [2.0 200514]
	org.graalvm.visualvm.modules.graalvm/2 [2.0 200514]
	org.graalvm.visualvm.modules.appui/2 [2.0 200514]
	org.graalvm.visualvm.jvmstat/2 [2.0 200514]
	org.graalvm.visualvm.jvm/2 [2.0 200514]
	org.graalvm.visualvm.jmx/2 [2.1 200514]
	org.graalvm.visualvm.jfr/2 [2.1 200514]
	org.graalvm.visualvm.jfr.jdk9/2 [2.1 200514]
	org.graalvm.visualvm.jfr.jdk11/2 [2.1 200514]
	org.graalvm.visualvm.jfr.generic/2 [2.1 200514]
	org.graalvm.visualvm.host.views/2 [2.0 200514]
	org.graalvm.visualvm.host.remote/2 [2.0 200514]
	org.graalvm.visualvm.heapviewer.truffle/2 [2.0 200514]
	org.graalvm.visualvm.heapviewer.console/2 [2.0 200514]
	org.graalvm.visualvm.attach/2 [2.0 200514]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Mac
INFO [org.netbeans.core.network.proxy.mac.MacNetworkProxy]: Mac system proxy resolver: auto - PAC (http://pac.hybrid-web.global.blackspider.com/proxy.pac?p=7gh9mks3)
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
Warning: Nashorn engine is planned to be removed from a future JDK release
INFO [null]: Last record repeated again.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: auto
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - pac url: http://pac.hybrid-web.global.blackspider.com/proxy.pac?p=7gh9mks3
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy TEST - http host:
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy TEST - http port: 0
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
Diagnostic information
Input arguments:
	-Djdk.home=/Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home
	-Dnetbeans.default_userdir_root=/Users/c050051/Library/Application Support/VisualVM
	-Dnetbeans.dirs=/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm:
	-Dnetbeans.home=/Applications/VisualVM.app/Contents/Resources/visualvm/platform
	-Xms24m
	-Xmx768m
	-Dnetbeans.accept_license_class=org.graalvm.visualvm.modules.startup.AcceptLicense
	-Dsun.jvmstat.perdata.syncWaitMs=10000
	-Dsun.java2d.noddraw=true
	-Dsun.java2d.d3d=false
	-Dorg.netbeans.core.TimeableEventQueue.quantum=360000
	-Dpolyglot.js.nashorn-compat=true
	-Dsun.misc.URLClassPath.disableJarChecking=true
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED
	--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
	--add-exports=java.desktop/sun.swing=ALL-UNNAMED
	--add-exports=jdk.attach/sun.tools.attach=ALL-UNNAMED
	--add-opens=java.base/java.net=ALL-UNNAMED
	--add-opens=java.base/java.lang.ref=ALL-UNNAMED
	--add-opens=java.base/java.lang=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
	-XX:+IgnoreUnrecognizedVMOptions
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=/Users/c050051/Library/Application Support/VisualVM/2.0.2/var/log/heapdump.hprof
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 24.0MB maximum 768.0MB
Non heap memory usage: initial 7.3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=19 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=7935 total loaded=7937 unloaded 2
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 17,179,869,184
INFO [null]: Total physical memory 17,179,869,184
INFO [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: Unpaired license D5533D83 without any module.
WARNING [org.openide.filesystems.Ordering]: Found same position 1,500 for both VisualVM/ExplorerPopupSelection/org-graalvm-visualvm-application-RemoveFinishedApplicationsAction-selectionAware.instance and VisualVM/ExplorerPopupSelection/org-graalvm-visualvm-application-snapshot-ApplicationSnapshotAction.shadow
WARNING [org.netbeans.modules.progress.spi.InternalHandle]: Cannot switch to silent mode when not running at org.netbeans.core.ui.warmup.MenuWarmUpTask$NbWindowsAdapter$1HandleBridge.run(MenuWarmUpTask.java:244)
INFO [org.graalvm.visualvm.attach.AttachModelImpl]: printFlag
java.io.IOException: Can not attach to current VM
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:56)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at org.graalvm.visualvm.attach.AttachModelImpl.getVirtualMachine(AttachModelImpl.java:124)
Caused: java.io.IOException: Can not attach to current VM
	at org.graalvm.visualvm.attach.AttachModelImpl.getVirtualMachine(AttachModelImpl.java:126)
[catch] at org.graalvm.visualvm.attach.AttachModelImpl.printFlag(AttachModelImpl.java:89)
	at org.graalvm.visualvm.jvm.JVMImpl.isDumpOnOOMEnabled(JVMImpl.java:257)
	at org.graalvm.visualvm.heapdump.impl.HeapDumpOnOOMEAction.updateState(HeapDumpOnOOMEAction.java:87)
	at org.graalvm.visualvm.heapdump.impl.HeapDumpOnOOMEAction.isEnabled(HeapDumpOnOOMEAction.java:81)
	at org.graalvm.visualvm.heapdump.impl.HeapDumpOnOOMEAction.isEnabled(HeapDumpOnOOMEAction.java:50)
	at org.graalvm.visualvm.core.ui.actions.SingleDataSourceAction.updateState(SingleDataSourceAction.java:77)
	at org.graalvm.visualvm.heapdump.impl.HeapDumpOnOOMEAction.updateState(HeapDumpOnOOMEAction.java:95)
	at org.graalvm.visualvm.core.ui.actions.DataSourceAction$1.selectionChanged(DataSourceAction.java:85)
	at org.graalvm.visualvm.core.explorer.ExplorerSupport$ExplorerTreeSelectionListener.valueChanged(ExplorerSupport.java:272)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1656)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2736)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4016)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3955)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at org.graalvm.visualvm.core.explorer.ExplorerComponent$1.processMouseEvent(ExplorerComponent.java:110)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO [org.graalvm.visualvm.attach.AttachModelImpl]: getSystemProperties
java.io.IOException: Can not attach to current VM
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:56)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at org.graalvm.visualvm.attach.AttachModelImpl.getVirtualMachine(AttachModelImpl.java:124)
Caused: java.io.IOException: Can not attach to current VM
	at org.graalvm.visualvm.attach.AttachModelImpl.getVirtualMachine(AttachModelImpl.java:126)
[catch] at org.graalvm.visualvm.attach.AttachModelImpl.getSystemProperties(AttachModelImpl.java:56)
	at org.graalvm.visualvm.jvm.JVMImpl.getSystemProperties(JVMImpl.java:341)
	at org.graalvm.visualvm.application.views.overview.ApplicationOverviewModel.initialize(ApplicationOverviewModel.java:242)
	at org.graalvm.visualvm.application.views.overview.ApplicationOverviewModel.initialize(ApplicationOverviewModel.java:135)
	at org.graalvm.visualvm.application.views.overview.ApplicationOverviewView.willBeAdded(ApplicationOverviewView.java:56)
	at org.graalvm.visualvm.core.ui.DataSourceView.viewWillBeAdded(DataSourceView.java:192)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.addViews(DataSourceWindowManager.java:337)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.openWindowAndAddView(DataSourceWindowManager.java:260)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.access$000(DataSourceWindowManager.java:51)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager$2.run(DataSourceWindowManager.java:118)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

  MACC02VJ2CTHTDD in ~/Library/Application Support/visualvm/2.0.2/var/log
○ →

**Comment by thurka** [comment]
`Can not attach to current VM` is not related to `computing description`. Are you using VPN? 

BTW: Next time, please, attach messages.log file to the issue instead of pasting its content to the description field. Thanks.

**Comment by thurka** [comment]
Closing until more info is available.
