### ISSUE TITLE
CPU Sampling is disabled.

### ISSUE THREAD

**Issue by gopaladhith** [oracle/visualvm#214]
**Describe the bug**
CPU button under sampling section is disabled, and also Threads section is also not appearing. Not able to attach the screenshot here. The summary page says the following,

**Not available. Failed to create JMX connection to target application. Use 'Add JMX Connection' action to attach to the application**

**To Reproduce**
Just open the application under applications section and navigate to Sampler tab.

**Expected behavior**
CPU Sampling should be enabled.

**VisualVM log**
**Not able to upload files here hence pasting the error trace**,
INFO [com.sun.tools.visualvm.jmx.impl.JmxModelImpl]: connect(19240)
java.net.SocketException: Malformed reply from SOCKS server
	at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:129)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:459)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
Caused: java.rmi.ConnectIOException: Exception creating connection to: 172.17.41.97; nested exception is: 
	java.net.SocketException: Malformed reply from SOCKS server
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:631)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy11.newClient(Unknown Source)
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
	at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$ProxyClient.tryConnect(JmxModelImpl.java:573)
[catch] at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$ProxyClient.connect(JmxModelImpl.java:507)
	at com.sun.tools.visualvm.jmx.impl.JmxModelImpl.connect(JmxModelImpl.java:235)
	at com.sun.tools.visualvm.jmx.impl.JmxModelImpl.<init>(JmxModelImpl.java:205)
	at com.sun.tools.visualvm.jmx.impl.JmxModelProvider.createModelFor(JmxModelProvider.java:64)
	at com.sun.tools.visualvm.jmx.impl.JmxModelProvider.createModelFor(JmxModelProvider.java:41)
	at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
	at com.sun.tools.visualvm.tools.jmx.JmxModelFactory.getJmxModelFor(JmxModelFactory.java:69)
	at com.sun.tools.visualvm.jvm.JmxSupport.getJvmMXBeans(JmxSupport.java:157)
	at com.sun.tools.visualvm.jvm.JmxSupport.getRuntime(JmxSupport.java:90)
	at com.sun.tools.visualvm.jvm.JmxSupport.getJvmArgs(JmxSupport.java:177)
	at com.sun.tools.visualvm.jvm.JVMImpl.getJvmArgsJvmstat(JVMImpl.java:530)
	at com.sun.tools.visualvm.jvm.JVMImpl.initStaticData(JVMImpl.java:501)
	at com.sun.tools.visualvm.jvm.JVMImpl.getMainClass(JVMImpl.java:139)
	at com.sun.tools.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:148)
	at com.sun.tools.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:42)
	at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
	at com.sun.tools.visualvm.application.type.ApplicationTypeFactory.getApplicationTypeFor(ApplicationTypeFactory.java:74)
	at com.sun.tools.visualvm.application.ApplicationDescriptor.<init>(ApplicationDescriptor.java:55)
	at com.sun.tools.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:43)
	at com.sun.tools.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:38)
	at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
	at com.sun.tools.visualvm.core.datasource.descriptor.DataSourceDescriptorFactory.getDescriptor(DataSourceDescriptorFactory.java:69)
	at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.processAddedDisplayableDataSources(ExplorerModelBuilder.java:152)
	at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.processIndependentAddedDataSources(ExplorerModelBuilder.java:116)
	at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.processAddedDataSources(ExplorerModelBuilder.java:105)
	at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.access$200(ExplorerModelBuilder.java:59)
	at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder$1.run(ExplorerModelBuilder.java:98)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Screenshots**
Not able to attach screen shot the summary page message is provided above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version: JDK 1.8.0_212
 - Version: 1.3.9

**Comment by gopaladhith** [comment]
After Removing this option - "-Djava.net.preferIPv4Stack=true" from the eclipse application i am able to perform CPU Sampling. But not sure why this has to be removed. I am behind a corporate proxy and CNTLM is also enabled. 

Is this issue surfacing because of some proxy setting. Some inputs here would be appreciated. Thanks in advance.

**Comment by thurka** [comment]
Yes, it looks like proxy setting. What is your proxy setting in VisualVM? Can you try to set proxy to 'No proxy' and see if it helps. Based on the stack trace, it looks like there is socks proxy set and used for accessing local process, which obviously does not work.

See this official guide https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests for info how to attach file to issue.

**Comment by gopaladhith** [comment]
Previously it was **Use system settings** under proxy, changed it to **No Proxy** but this also did not solve the issue.

**Comment by thurka** [comment]
Ok does it throw the same exception? Please attach VisualVM log file, so we can investigate it.

**Comment by gopaladhith** [comment]
Sorry for the late response, I am attaching the error log that got generated with **No Proxy** set in visual vm,

[visualvm.txt](https://github.com/oracle/visualvm/files/4929396/visualvm.txt)

**Comment by thurka** [comment]
The log file shows that the issue with proxy is solved and you have different error:
`java.net.SocketException: Permission denied: connect`
this is somehow connected with `-Djava.net.preferIPv4Stack=true`.  Are you using Cisco AnyConnect? If so see this: https://www.mythics.com/about/blog/permission-denied-socketexception-java-7-and-vpn

**Comment by gopaladhith** [comment]
No but in my case if i start the tool(to be monitored) with this **"-Djava.net.preferIPv4Stack=true"** option then this problem occurs and without this option only i am able to work.(Cisco Anyconnect is used)

But in a different system with the same Cisco Anyconnect and this **"-Djava.net.preferIPv4Stack=true"** option it is working fine.
