### ISSUE TITLE
Failed to initialize view org.graalvm.visualvm.profiling.snapshot.diff.SnapshotDiffView

### ISSUE THREAD

**Issue by kmishra** [oracle/visualvm#216]
Hi
**Java**: AmazonCorretto8 (jdk1.8.0_252)
**VisualVM**: 2.0.2

I tried to compare 2 snapshots (VisualVM 2.0.2) and I am getting following error. Even though if I take local snapshots - then also the same error is thrown.

SEVERE [org.graalvm.visualvm.core.ui.DataSourceWindowManager]: Failed to initialize view org.graalvm.visualvm.profiling.snapshot.diff.SnapshotDiffView@77705f7c
java.lang.NullPointerException
	at org.graalvm.visualvm.profiling.snapshot.diff.SnapshotDiffView$MasterViewSupport.getMasterView(SnapshotDiffView.java:147)
	at org.graalvm.visualvm.profiling.snapshot.diff.SnapshotDiffView.createComponent(SnapshotDiffView.java:106)
	at org.graalvm.visualvm.core.ui.DataSourceView.getView(DataSourceView.java:184)
	at org.graalvm.visualvm.core.ui.DataSourceWindowTabbedPane$ViewContainer.setView(DataSourceWindowTabbedPane.java:230)
	at org.graalvm.visualvm.core.ui.DataSourceWindowTabbedPane$ViewContainer.<init>(DataSourceWindowTabbedPane.java:209)
	at org.graalvm.visualvm.core.ui.DataSourceWindowTabbedPane.addView(DataSourceWindowTabbedPane.java:121)
	at org.graalvm.visualvm.core.ui.DataSourceWindow.addView(DataSourceWindow.java:94)
[catch] at org.graalvm.visualvm.core.ui.DataSourceWindowManager$8.run(DataSourceWindowManager.java:349)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kmishra** [comment]
Attatching the message.log.
[messages.log](https://github.com/oracle/visualvm/files/4928744/messages.log)

**Comment by jisedlac** [comment]
Thank you for the report! Can you please describe exact steps leading to the exception? I'm unable to reproduce the problem on my side just based on the stacktrace.

**Comment by jisedlac** [comment]
Probably found your steps - you've selected two memory snapshots in the Applications view, right-clicked the selection and invoked the Compare action from the context menu. Is this how you've hit the exception?

The Compare action should probably not be there at all. The right way to compare two snapshots is to open the first snapshot and use the Compare with another snapshot... action in its toolbar.

This way you exactly know what is the "main" snapshot being compared to and what is the "reference" snapshot for the comparison. The order of snapshots being compared using the Compare action for selection in Applications view is unclear.

**Comment by kmishra** [comment]
Thanks @jisedlac for your quick help. I could compare snapshots now.

Another observation - I remember in earlier setup with v2.0 (before my laptop crashed) - after comparing data is displayed, With that feature, I could filtered the required package via Filter box at the bottom, but now I dont see that anymore.

**Comment by jisedlac** [comment]
Right-click the results view and invoke the Filter action from its context menu. The Filter box will be displayed.
