### ISSUE TITLE
Local Java applications cannot be detected - 11.0.8.j9-adpt

### ISSUE THREAD

**Issue by cdsap** [oracle/visualvm#243]
**Describe the bug**
Similar to #219 when I start the app with 11.0.8.j9-adpt and Catalina VisualVm reports "Local Java applications cannot be detected"

**To Reproduce**
1. Set Java  11.0.8.j9-adpt
2. Start app

**Expected behavior**
See the java processes

**VisualVM log**
```
-------------------------------------------------------------------------------
>Log Session: Thursday, October 8, 2020 at 7:04:03 PM Pacific Daylight Time
>System Info: 
  Product Version         = VisualVM 2.0.4
  Operating System        = Mac OS X version 10.15.7 running on x86_64
  Java; VM; Vendor        = 11.0.8; Eclipse OpenJ9 VM openj9-0.21.0; AdoptOpenJDK
  Runtime                 = OpenJDK Runtime Environment 11.0.8+10
  Java Home               = /Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt
  System Locale; Encoding = en_US (visualvm); UTF-8
  Home Directory          = /Users/inakivillar
  Current Directory       = /
  User Directory          = /Users/inakivillar/Library/Application Support/VisualVM/2.0.4
  Cache Directory         = /Users/inakivillar/Library/Caches/VisualVM/2.0.4
  Installation            = /Applications/VisualVM.app/Contents/Resources/visualvm/visualvm
                            /Applications/VisualVM.app/Contents/Resources/visualvm/platform
  Boot & Ext. Classpath   = 
  Application Classpath   = /Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/boot.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-modules.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util-lookup.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util-ui.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util.jar
  Startup Classpath       = /Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/org-netbeans-libs-asm.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/org-openide-filesystems.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/asm-7.2.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/asm-commons-7.2.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/asm-tree-7.2.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/core.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/core/core-base.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm/core/org-graalvm-visualvm-modules-startup.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm/core/locale/core_visualvm.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.core.projects.cache]: layer jar:file:/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm/modules/org-graalvm-visualvm-jfr.jar!/org/graalvm/visualvm/jfr/resources/layer.xml contains duplicate folders named Actions/Other
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.40 20200619-unknown-revn]
	org.openide.util [9.14 20200619-unknown-revn]
	org.openide.util.ui [9.15 20200619-unknown-revn]
	org.openide.modules [7.55 20200619-unknown-revn]
	org.netbeans.api.annotations.common/1 [1.34 20200619-unknown-revn]
	org.openide.filesystems [9.17 20200619-unknown-revn]
	org.openide.awt [7.75 20200619-unknown-revn]
	org.netbeans.api.progress/1 [1.54 20200619-unknown-revn]
	org.netbeans.api.progress.nb [1.54 20200619-unknown-revn]
	org.openide.dialogs [7.49 20200619-unknown-revn]
	org.openide.nodes [7.52 20200619-unknown-revn]
	org.openide.windows [6.84 20200619-unknown-revn]
	org.netbeans.modules.editor.mimelookup/1 [1.47 20200619-unknown-revn]
	org.openide.text [6.74 20200619-unknown-revn]
	org.netbeans.api.scripting [1.4 20200619-unknown-revn]
	org.netbeans.swing.tabcontrol [1.63 20200619-unknown-revn]
	org.netbeans.swing.outline [1.41 20200619-unknown-revn]
	org.openide.explorer [6.69 20200619-unknown-revn]
	org.openide.actions [6.46 20200619-unknown-revn]
	org.netbeans.modules.queries/1 [1.50 20200619-unknown-revn]
	org.netbeans.api.templates [1.15 20200619-unknown-revn]
	org.openide.filesystems.nb [9.17 20200619-unknown-revn]
	org.openide.loaders [7.74 20200619-unknown-revn]
	org.netbeans.api.intent [1.9 20200619-unknown-revn]
	org.netbeans.api.io [1.10 20200619-unknown-revn]
	org.openide.io [1.56 20200619-unknown-revn]
	org.netbeans.swing.plaf [1.49 20200619-unknown-revn]
	org.netbeans.spi.quicksearch [1.34 20200619-unknown-revn]
	org.netbeans.libs.asm [5.10 20200619-unknown-revn]
	org.netbeans.bootstrap/1 [2.85 20200619-unknown-revn]
	org.netbeans.core.startup.base [1.69.0.1 1 20200619-unknown-revn]
	org.netbeans.core.startup/1 [1.69.0.1 20200619-unknown-revn]
	org.netbeans.modules.settings/1 [1.56 20200619-unknown-revn]
	org.netbeans.modules.sendopts/2 [2.43 20200619-unknown-revn]
	org.netbeans.modules.sampler [1.21 20200619-unknown-revn]
	org.netbeans.modules.progress.ui [1.40 20200619-unknown-revn]
	org.netbeans.modules.keyring [1.31 20200619-unknown-revn]
	org.netbeans.core/2 [3.58 20200619-unknown-revn]
	org.netbeans.modules.options.api/1 [1.52 20200619-unknown-revn]
	org.netbeans.modules.options.keymap [1.44 20200619-unknown-revn]
	org.netbeans.modules.masterfs/2 [2.62.0.2 2 20200619-unknown-revn]
	org.netbeans.modules.masterfs.ui [2.10.0.2 20200619-unknown-revn]
	org.netbeans.modules.masterfs.nio2 [1.22 20200619-unknown-revn]
	org.netbeans.libs.jna/2 [2.2 20200619-unknown-revn]
	org.netbeans.modules.masterfs.macosx [1.20 20200619-unknown-revn]
	org.netbeans.modules.keyring.fallback [1.15 20200619-unknown-revn]
	org.netbeans.modules.keyring.impl [1.31 20200619-unknown-revn]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.39 20200619-unknown-revn]
	org.netbeans.modules.autoupdate.services [1.62 20200619-unknown-revn]
	org.netbeans.modules.autoupdate.ui [1.53 20200619-unknown-revn]
	org.netbeans.modules.autoupdate.cli [1.20 20200619-unknown-revn]
	org.netbeans.core.windows/2 [2.90 20200619-unknown-revn]
	org.netbeans.modules.applemenu/1 [1.44 20200619-unknown-revn]
	org.netbeans.libs.jna.platform/2 [2.2 20200619-unknown-revn]
	org.netbeans.core.ui/1 [1.52 20200619-unknown-revn]
	org.netbeans.core.network [1.19 20200619-unknown-revn]
	org.netbeans.core.nativeaccess/1 [1.38 20200619-unknown-revn]
	org.netbeans.core.multitabs/1 [1.19.0.1 1 20200619-unknown-revn]
	org.netbeans.core.io.ui/1 [1.37 20200619-unknown-revn]
	org.graalvm.visualvm.lib.jfluid/2 [2.3 200811]
	org.graalvm.visualvm.lib.charts/2 [2.0 200811]
	org.graalvm.visualvm.lib.common/2 [2.1 200811]
	org.graalvm.visualvm.lib.profiler.api/2 [2.1 200811]
	org.graalvm.visualvm.lib.ui/2 [2.2 200811]
	org.graalvm.visualvm.uisupport/2 [2.0 200811]
	org.graalvm.visualvm.core/2 [2.2 200811]
	org.graalvm.visualvm.host/2 [2.0 200811]
	org.graalvm.visualvm.application/2 [2.0 200811]
	org.graalvm.visualvm.tools/2 [2.0 200811]
	org.graalvm.visualvm.coredump/2 [2.0 200811]
	org.graalvm.visualvm.threaddump/2 [2.0 200811]
	org.graalvm.visualvm.lib.profiler.utilities/2 [2.0 200811]
	org.graalvm.visualvm.lib.profiler.attach/2 [2.0 200811]
	org.graalvm.visualvm.lib.profiler/2 [2.1 200811]
	org.graalvm.visualvm.lib.profiler.snaptracer/2 [2.0 200811]
	org.graalvm.visualvm.profiling/2 [2.1 200811]
	org.graalvm.visualvm.lib.profiler.oql/2 [2.0 200811]
	org.graalvm.visualvm.lib.profiler.heapwalker/2 [2.0 200811]
	org.graalvm.visualvm.heapviewer/2 [2.2 200811]
	org.graalvm.visualvm.heapdump/2 [2.0 200811]
	org.graalvm.visualvm.sampler.truffle/2 [2.0 200811]
	org.graalvm.visualvm.sampler/2 [2.0 200811]
	org.graalvm.visualvm.sa/2 [2.0 200811]
	org.graalvm.visualvm.modules.startup/2 [2.0 200811]
	org.graalvm.visualvm.profiler/2 [2.0 200811]
	org.graalvm.visualvm.charts/2 [2.0 200811]
	org.graalvm.visualvm.application.views/2 [2.0 200811]
	org.graalvm.visualvm.modules.graalvm/2 [2.0 200811]
	org.graalvm.visualvm.modules.extensions/2 [2.0 200207]
	org.graalvm.visualvm.modules.appui/2 [2.0 200811]
	org.graalvm.visualvm.jvmstat/2 [2.0 200811]
	org.graalvm.visualvm.jvm/2 [2.0 200811]
	org.graalvm.visualvm.jmx/2 [2.1 200811]
	org.graalvm.visualvm.jfr/2 [2.1 200811]
	org.graalvm.visualvm.jfr.jdk9/2 [2.1 200811]
	org.graalvm.visualvm.jfr.jdk11/2 [2.1 200811]
	org.graalvm.visualvm.jfr.generic/2 [2.1 200811]
	org.graalvm.visualvm.host.views/2 [2.0 200811]
	org.graalvm.visualvm.host.remote/2 [2.0 200811]
	org.graalvm.visualvm.heapviewer.truffle/2 [2.0 200811]
	org.graalvm.visualvm.heapviewer.console/2 [2.0 200811]
	org.graalvm.visualvm.attach/2 [2.0 200811]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Mac
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading failed! Trying fallback resolver.
INFO [org.netbeans.core.network.proxy.fallback.FallbackNetworkProxy]: Fallback system proxy resolver: no http_proxy variable found
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded. Fallback provider was successful.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO [org.graalvm.visualvm.jvmstat.JvmstatModelProvider]: getMonitoredVm failed
java.lang.NullPointerException
	at java.base/jdk.internal.perf.Perf.attachImpl(Perf.java:284)
	at java.base/jdk.internal.perf.Perf.attach(Perf.java:200)
	at jdk.internal.jvmstat/sun.jvmstat.perfdata.monitor.protocol.local.PerfDataBuffer.<init>(PerfDataBuffer.java:64)
	at jdk.internal.jvmstat/sun.jvmstat.perfdata.monitor.protocol.local.LocalMonitoredVm.<init>(LocalMonitoredVm.java:68)
	at jdk.internal.jvmstat/sun.jvmstat.perfdata.monitor.protocol.local.MonitoredHostProvider.getMonitoredVm(MonitoredHostProvider.java:77)
[catch] at org.graalvm.visualvm.jvmstat.JvmstatModelProvider.getMonitoredVm(JvmstatModelProvider.java:56)
	at org.graalvm.visualvm.jvmstat.JvmstatModelProvider.createModelFor(JvmstatModelProvider.java:71)
	at org.graalvm.visualvm.jvmstat.JvmstatModelProvider.createModelFor(JvmstatModelProvider.java:45)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.tools.jvmstat.JvmstatModelFactory.getJvmstatFor(JvmstatModelFactory.java:65)
	at org.graalvm.visualvm.graalvm.svm.SVMJvmProvider.createModelFor(SVMJvmProvider.java:49)
	at org.graalvm.visualvm.graalvm.svm.SVMJvmProvider.createModelFor(SVMJvmProvider.java:37)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.application.jvm.JvmFactory.getJVMFor(JvmFactory.java:65)
	at org.graalvm.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:145)
	at org.graalvm.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:42)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.application.type.ApplicationTypeFactory.getApplicationTypeFor(ApplicationTypeFactory.java:74)
	at org.graalvm.visualvm.application.ApplicationDescriptor.<init>(ApplicationDescriptor.java:65)
	at org.graalvm.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:43)
	at org.graalvm.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:38)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.core.datasource.descriptor.DataSourceDescriptorFactory.getDescriptor(DataSourceDescriptorFactory.java:69)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processAddedDisplayableDataSources(ExplorerModelBuilder.java:160)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processIndependentAddedDataSources(ExplorerModelBuilder.java:121)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processAddedDataSources(ExplorerModelBuilder.java:110)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.access$200(ExplorerModelBuilder.java:60)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder$1.run(ExplorerModelBuilder.java:100)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Diagnostic information
Input arguments:
	-Xoptionsfile=/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib/options.default
	-Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple
	-Xjcl:jclse29
	-Dcom.ibm.oti.vm.bootstrap.library.path=/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib/compressedrefs:/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib
	-Dsun.boot.library.path=/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib/compressedrefs:/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib
	-Djava.library.path=/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib/compressedrefs:/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt/lib:/usr/lib
	-Djava.home=/Users/inakivillar/.sdkman/candidates/java/11.0.8.j9-adpt
	-Duser.dir=/
	-Djdk.home=/Users/inakivillar/.sdkman/candidates/java/current
	-Djava.class.path=/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/boot.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-modules.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util-lookup.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util-ui.jar:/Applications/VisualVM.app/Contents/Resources/visualvm/platform/lib/org-openide-util.jar
	-Dnetbeans.default_userdir_root=/Users/inakivillar/Library/Application Support/VisualVM
	-Dnetbeans.dirs=/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm:
	-Dnetbeans.home=/Applications/VisualVM.app/Contents/Resources/visualvm/platform
	-Xms24m
	-Xmx768m
	-Dnetbeans.accept_license_class=org.graalvm.visualvm.modules.startup.AcceptLicense
	-Dsun.jvmstat.perdata.syncWaitMs=10000
	-Dsun.java2d.noddraw=true
	-Dsun.java2d.d3d=false
	-Dorg.netbeans.core.TimeableEventQueue.quantum=360000
	-Dpolyglot.js.nashorn-compat=true
	-Dsun.misc.URLClassPath.disableJarChecking=true
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED
	--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
	--add-exports=java.desktop/sun.swing=ALL-UNNAMED
	--add-exports=jdk.attach/sun.tools.attach=ALL-UNNAMED
	--add-opens=java.base/java.net=ALL-UNNAMED
	--add-opens=java.base/java.lang.ref=ALL-UNNAMED
	--add-opens=java.base/java.lang=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
	-XX:+IgnoreUnrecognizedVMOptions
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=/Users/inakivillar/Library/Application Support/VisualVM/2.0.4/var/log/heapdump.hprof
	-Dsun.java.command=org.netbeans.Main --cachedir /Users/inakivillar/Library/Caches/VisualVM/2.0.4 --userdir /Users/inakivillar/Library/Application Support/VisualVM/2.0.4 --branding visualvm --laf com.apple.laf.AquaLookAndFeel
	-Dsun.java.launcher=SUN_STANDARD
Compiler: j9jit29
Heap memory usage: initial 24.0MB maximum 768.0MB
Non heap memory usage: initial 395.2MB maximum -1b
Garbage collector: scavenge (Collections=15 Total time spent=0s)
Garbage collector: global (Collections=4 Total time spent=0s)
Classes: loaded=6356 total loaded=6356 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 34,359,738,368
INFO [null]: Total physical memory 34,359,738,368
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://visualvm.github.io/uc/release204/updates.xml.gz?unique=026c7ed80-9076-48aa-814c-b39c83bcf918_b3a90c00-6d3a-456f-b914-c02b375182d6:96:175: Element type "message_digest" must be declared.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://visualvm.github.io/uc/release204/updates.xml.gz?unique=026c7ed80-9076-48aa-814c-b39c83bcf918_b3a90c00-6d3a-456f-b914-c02b375182d6:97:10: The content of element type "module" must match "(description?,module_notification?,external_package*,(manifest|l10n))".
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://visualvm.github.io/uc/release204/updates.xml.gz?unique=026c7ed80-9076-48aa-814c-b39c83bcf918_b3a90c00-6d3a-456f-b914-c02b375182d6:107:175: Element type "message_digest" must be declared.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://visualvm.github.io/uc/release204/updates.xml.gz?unique=026c7ed80-9076-48aa-814c-b39c83bcf918_b3a90c00-6d3a-456f-b914-c02b375182d6:108:10: The content of element type "module" must match "(description?,module_notification?,external_package*,(manifest|l10n))".
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://visualvm.github.io/uc/release204/updates.xml.gz?unique=026c7ed80-9076-48aa-814c-b39c83bcf918_b3a90c00-6d3a-456f-b914-c02b375182d6:113:175: Element type "message_digest" must be declared.
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://visualvm.github.io/uc/release204/updates.xml.gz?unique=026c7ed80-9076-48aa-814c-b39c83bcf918_b3a90c00-6d3a-456f-b914-c02b375182d6:114:10: The content of element type "module" must match "(description?,module_notification?,external_package*,(manifest|l10n))".
```
**Screenshots**
Same as  #219 

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - JDK version 11.0.8.j9-adpt
 - Version 2.0.4

**Additional context**
Additionally I need to setup the etc/visaulvm.conf with the path of the jvm. 
```
visualvm_jdkhome=/Users/user/.sdkman/candidates/java/current/
```

And when I test with Java versions like 11.0.8.hs-adpt everything works fine

**Comment by thurka** [comment]
Running VisualVM on 'Eclipse OpenJ9' is not supported. Please use OpenJDK/HotSpot for VisualVM. You can still monitor Eclipse OpenJ9 processes via JMX.
