### ISSUE TITLE
NPE when expanding some memory profile nodes

### ISSUE THREAD

**Issue by byteit101** [oracle/visualvm#244]
**To Reproduce**
1. Start memory profiling
2. Collect Data & Stop memory profiling
3. Expand a class name that triggers this bug (seems random overall, but consistent run-to-run)
4. See Swing stops repainting and notice the lack of changes aside from the new error notification in the corner

**Expected behavior**
Class name expands and shows details

**VisualVM log**
```
java.lang.NullPointerException
	at org.graalvm.visualvm.lib.jfluid.results.memory.PresoObjAllocCCTNode.setChildren(PresoObjAllocCCTNode.java:133)
	at org.graalvm.visualvm.lib.ui.memory.LivenessTreeTableView$1Node.getChildren(LivenessTreeTableView.java:274)
	at org.graalvm.visualvm.lib.ui.memory.LivenessTreeTableView$1Node.getChildCount(LivenessTreeTableView.java:284)
	at java.desktop/javax.swing.tree.DefaultTreeModel.getChildCount(DefaultTreeModel.java:192)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$FilteredTreeModel.getChildCount(ProfilerTreeTable.java:942)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache$VisibleFHTreeStateNodeEnumeration.<init>(FixedHeightLayoutCache.java:1500)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache$VisibleFHTreeStateNodeEnumeration.<init>(FixedHeightLayoutCache.java:1493)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getVisiblePathsFrom(FixedHeightLayoutCache.java:283)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1330)
	at java.desktop/javax.swing.plaf.metal.MetalTreeUI.paint(MetalTreeUI.java:190)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$ProfilerTreeTableTree.paint(ProfilerTreeTable.java:1461)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable$ScrollableRenderer.paint(ProfilerTable.java:351)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:165)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2186)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2087)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1883)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTableContainer$8.paint(ProfilerTableContainer.java:309)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1024)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1024)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at org.netbeans.swing.tabcontrol.TabbedContainer.paint(TabbedContainer.java:969)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at org.netbeans.core.windows.view.ui.MainWindow$1.paint(MainWindow.java:166)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5262)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Screenshots**
In this picture, I expanded Date, LinkedList, and then attempted ArrayList, which crashed and prevented anything else from expanding/contracting afterwards
![expanding-jvm](https://user-images.githubusercontent.com/577344/96048067-16eb0c80-0e44-11eb-9c98-17f4d4d01563.png)

**Desktop**
 - OS: Debian 10
 - JDK version: openjdk (build 11.0.8+10-post-Debian-1deb10u1)
 - Version 2.0.4

**Comment by thurka** [comment]
Thanks for the report. Can you please attach whole messages.log file and the memory snapshot, so we can reproduce this NPE.

**Comment by byteit101** [comment]
How do I create the memory snapshot? That button is grayed out for me:
![graysnapshot](https://user-images.githubusercontent.com/577344/96186939-2b91d800-0f0a-11eb-8432-b248a719e6b0.png)

**Comment by thurka** [comment]
> How do I create the memory snapshot?

Take a snapshot while profiling is active.

**Comment by byteit101** [comment]
Ah, that's a confusing thing. The memory snapshot (gzipped): [visualvm_issue244_privatized.nps.gz](https://github.com/oracle/visualvm/files/5455202/visualvm_issue244_privatized.nps.gz)

**Comment by thurka** [comment]
Thanks for nps snapshot. BTW what is this:
```
Privatized with nps_censor.rb.

Use `nps_censor.rb -p private.nps mapfile output.nps` to unobscure the names.
Use `nps_censor -m method mapfile` to get the unobscured name and signature of a method,
and `nps_censor -c classname mapfile` for class names.

Generation Options:
arrays: false
intrinsics: false
java: true
public: ['java.lang.Long']
signatures: true
well_known: true
```

**Comment by thurka** [comment]
One more question. Do you have the following warning:
`Profiler Agent Warning: Cannot convert 0x...`
in the log file of your profiled application?

**Comment by thurka** [comment]
Fixed in master.

**Comment by byteit101** [comment]
Awesome, thanks!

BTW, I did see the `Profiler Agent Warning: Cannot convert 0x...` in the log file.

**Comment by thurka** [comment]
> BTW, I did see the `Profiler Agent Warning: Cannot convert 0x...` in the log file.

Thanks for confirmation. Can you file a new issue for that? It would be great if you can put together steps how to reproduce `Profiler Agent Warning: Cannot convert 0x...`.
