### ISSUE TITLE
NPE from Polyglot Sampler agent

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#249]
**Describe the bug**
Polyglot sampler agent sometimes throws the following NPE:
```
java.lang.NullPointerException
	at com.oracle.truffle.tools.profiler.impl.CPUSamplerInstrument.getSampler(CPUSamplerInstrument.java:93)
	at com.oracle.truffle.tools.profiler.CPUSampler.find(CPUSampler.java:270)
	at org.graalvm.visualvm.sampler.truffle.stagent.Truffle.getAllStackTracesInstances(Truffle.java:216)
	at org.graalvm.visualvm.sampler.truffle.stagent.Truffle.dumpAllThreads(Truffle.java:89)
```

**To Reproduce**
1. start VisualVM
2. open GraalVM application 
3. try to use polyglot sampler, click on 'CPU' button
4. NPE is thrown to console of the sampled application, VisualVM displays no CPU results

**Desktop (please complete the following information):**
 - OS: macOS
 - JDK version : JDK 1.8.0_181
 - Version Dev.

**Comment by thurka** [comment]
Fixed in master.
