### ISSUE TITLE
Fails to show VisualGC for ZGC

### ISSUE THREAD

**Issue by hallyhaa** [oracle/visualvm#261]
**Describe the bug**
When running a large java app using the ZGC garbage collector, the VisualVM tab VisualGC falsely claims it doesn't support the running JVM (whereas actually, it's the chosen GC that represents a problem).

**To Reproduce**
1 Start VisualVM
2 Start a JVM app using the commandline option -XX+UseZGC
3 Find the newly started app in VisualVM and click the VisualGC tab
4 See error

**Expected behavior**
A very nice graphical representation of the current state of the memory use should be displayed

**VisualVM log**
INFO [com.sun.jvmstat.tools.visualgc.VisualGCView]: Could not create GCSample
java.lang.NullPointerException: Cannot invoke "sun.jvmstat.monitor.LongMonitor.longValue()" because "this.edenSize" is null
	at com.sun.jvmstat.tools.visualgc.MonitoredVmModel.getNewGenMaxSize(MonitoredVmModel.java:250)
	at com.sun.jvmstat.tools.visualgc.GCSample.<init>(GCSample.java:131)
[catch] at com.sun.jvmstat.tools.visualgc.VisualGCView.initializeModel(VisualGCView.java:218)
	at com.sun.jvmstat.tools.visualgc.VisualGCView.<init>(VisualGCView.java:103)
	at org.graalvm.visualvm.modules.visualgc.VisualGCViewProvider.createView(VisualGCViewProvider.java:26)
	at org.graalvm.visualvm.modules.visualgc.VisualGCViewProvider.createView(VisualGCViewProvider.java:19)
	at org.graalvm.visualvm.core.ui.DataSourceViewProvider.getView(DataSourceViewProvider.java:103)
	at org.graalvm.visualvm.core.ui.DataSourceViewsManager.getViews(DataSourceViewsManager.java:137)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.openWindowAndAddView(DataSourceWindowManager.java:263)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.access$000(DataSourceWindowManager.java:53)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager$2.run(DataSourceWindowManager.java:122)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10 and Ubuntu 20.04
 - JDK version JDK 15
 - VisualVM version 2.0.5

**Additional context**
Very cold weather today

**Comment by ZhangDi-d** [comment]
encountered the same problem，with environment ： 1. window 10 ；2.DK version JDK 15；3.VisualVM version 2.0.6 。 everything was ok ,and visual GC plugins worked well .But when i use ZGC by add VM options “-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:ConcGCThreads=1” ，i meet the problem like @hallyhaa

**Comment by KyongSik-Yoon** [comment]
+1

**Comment by sgtcortez** [comment]
Visual VM 2.1.5 still does not work.

**Comment by sgtcortez** [comment]
Visual VM 2.1.5 still does not work.

**Comment by gjycn** [comment]
Visual VM 2.1.8 with Eclipse Adoptium 21.0.3+9 on windows 11 still does not work too.

**Comment by ncc0706** [comment]
Visual VM 2.1.10 with Eclipse Adoptium 21.0.4 on Alpine linux 3.16 still does not work too.
