### ISSUE TITLE
NPE: Cannot invoke "java.lang.management.MemoryMXBean.gc()"

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#273]
Steps to reproduce:

1. local application without JMX (Attach API must be working).
2. Invoke Memory sampler -> Perform GC
3. NPE

```
java.lang.NullPointerException: Cannot invoke "java.lang.management.MemoryMXBean.gc()" because the return value of "org.graalvm.visualvm.sampler.memory.MemoryView.access$1100(org.graalvm.visualvm.sampler.memory.MemoryView)" is null
[catch] at org.graalvm.visualvm.sampler.memory.MemoryView$10$1.run(MemoryView.java:465)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by thurka** [comment]
Fixed in master.
