### ISSUE TITLE
NPE at LongBuffer.startReading()

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#278]
```
java.lang.NullPointerException
	at org.graalvm.visualvm.lib.jfluid.heap.LongBuffer.startReading(LongBuffer.java:138)
	at org.graalvm.visualvm.lib.jfluid.heap.TreeObject.switchBuffers(TreeObject.java:193)
	at org.graalvm.visualvm.lib.jfluid.heap.TreeObject.computeTrees(TreeObject.java:84)
	at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.computeRetainedSize(HprofHeap.java:761)
	at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.getRetainedSize(HprofHeap.java:457)
	at org.graalvm.visualvm.lib.jfluid.heap.InstanceDump.getRetainedSize(InstanceDump.java:119)
	at org.graalvm.visualvm.heapviewer.utils.HeapOperations$3.run(HeapOperations.java:209)
```

**To Reproduce**
1. Open heap dump
2. Compute GC roots
3. Close VisualVM
4. Open the same heap dump
5. Compute retained sizes
6. NPE

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/6037227/messages.log)

**Comment by thurka** [comment]
Fixed in master.
