### ISSUE TITLE
java.lang.UnsupportedClassVersionError from SAModel

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#286]
Reported via email. The following exception can be thrown from SAModel:
```
java.lang.UnsupportedClassVersionError: sun/jvm/hotspot/HotSpotAgent has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 59.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at org.graalvm.visualvm.sa.SAWrapper.classForName(SAWrapper.java:80)
	at org.graalvm.visualvm.sa.SAWrapper.HotSpotAgent(SAWrapper.java:92)
	at org.graalvm.visualvm.sa.Agent.<init>(Agent.java:60)
	at org.graalvm.visualvm.sa.Agent.getAgent(Agent.java:46)
	at org.graalvm.visualvm.sa.SaModelImpl.<init>(SaModelImpl.java:50)
	at org.graalvm.visualvm.sa.SaModelProvider.createModelFor(SaModelProvider.java:85)
	at org.graalvm.visualvm.sa.SaModelProvider.createModelFor(SaModelProvider.java:46)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.tools.sa.SaModelFactory.getSAAgentFor(SaModelFactory.java:65)
	at org.graalvm.visualvm.jvm.JVMImpl.getSAAgent(JVMImpl.java:527)
	at org.graalvm.visualvm.jvm.JVMImpl.getJvmArgsJvmstat(JVMImpl.java:576)
	at org.graalvm.visualvm.jvm.JVMImpl.initStaticData(JVMImpl.java:541)
	at org.graalvm.visualvm.jvm.JVMImpl.getMainClass(JVMImpl.java:139)
	at org.graalvm.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:148)
	at org.graalvm.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:42)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.application.type.ApplicationTypeFactory.getApplicationTypeFor(ApplicationTypeFactory.java:74)
	at org.graalvm.visualvm.application.ApplicationDescriptor.<init>(ApplicationDescriptor.java:65)
	at org.graalvm.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:43)
	at org.graalvm.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:38)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.core.datasource.descriptor.DataSourceDescriptorFactory.getDescriptor(DataSourceDescriptorFactory.java:69)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processAddedDisplayableDataSources(ExplorerModelBuilder.java:160)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processIndependentAddedDataSources(ExplorerModelBuilder.java:121)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processAddedDataSources(ExplorerModelBuilder.java:110)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.access$200(ExplorerModelBuilder.java:60)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder$1.run(ExplorerModelBuilder.java:100)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by thurka** [comment]
Fixed in master.
