### ISSUE TITLE
Profiling Memory with Allocation Stack Traces fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by softignition** [oracle/visualvm#30]
I'm using the latest downloadable VisualVM version: 1.3.9 (Build 161004).
The following exception occurs each time when trying to Profile Memory with settings: "Record allocations stack traces" and "Track every 10th object allocation".

Exception in thread "*** Profiler Agent Communication Thread" *** Profiler engine warning: class java.lang.Throwable$PrintStreamOrWriter loaded by *** Profiler Agent Communication Thread
*** Profiler engine warning: class java.lang.Throwable$WrappedPrintStream loaded by *** Profiler Agent Communication Thread
java.lang.ArrayIndexOutOfBoundsException
	at org.netbeans.lib.profiler.server.system.Stacks.getMethodNamesForJMethodIds(Native Method)
	at org.netbeans.lib.profiler.server.ProfilerInterface.getMethodNamesForJMethodIds(ProfilerInterface.java:396)
	at org.netbeans.lib.profiler.server.ProfilerServer.handleClientCommand(ProfilerServer.java:1515)
	at org.netbeans.lib.profiler.server.ProfilerServer.listenToClient(ProfilerServer.java:1736)
	at org.netbeans.lib.profiler.server.ProfilerServer.run(ProfilerServer.java:693)

**Comment by bernacek** [comment]
Java 1.8.0_121

**Comment by thurka** [comment]
Is this still a problem with the latest VisualVM? Can you provide steps how to reproduce it?

**Comment by thurka** [comment]
Closing until more info is available.
