### ISSUE TITLE
Endless computation of thread dump

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#307]
1. Open heap dump
2. go to threads
3. switch to html view

html thread dump is not computed. Does not happen always, thread dump needs to be long. The computation is stuck at following stack trace: 
```
"AWT-EventQueue-0" #21 prio=6 os_prio=31 tid=0x00007f983f21a000 nid=0x11107 runnable [0x0000700008d3e000]
   java.lang.Thread.State: RUNNABLE
        at sun.util.locale.provider.RuleBasedBreakIterator.handleNext(RuleBasedBreakIterator.java:969)
        at sun.util.locale.provider.RuleBasedBreakIterator.previous(RuleBasedBreakIterator.java:668)
        at sun.util.locale.provider.RuleBasedBreakIterator.preceding(RuleBasedBreakIterator.java:821)
        at javax.swing.text.GlyphView.getBreakSpot(GlyphView.java:799)
        at javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:724)
        at javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:150)
        at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:733)
        at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
        at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
        at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
        at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
        at javax.swing.text.BoxView.getPreferredSpan(BoxView.java:545)
        at javax.swing.text.html.ParagraphView.getPreferredSpan(ParagraphView.java:253)
        at javax.swing.text.html.LineView.getMinimumSpan(LineView.java:74)
        at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
        at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
        at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
        at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
        at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
        at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
        at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
        at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
        at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
        at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
        at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
        at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
        at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
        at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
        at javax.swing.text.BoxView.layout(BoxView.java:708)
        at javax.swing.text.BoxView.setSize(BoxView.java:397)
        at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
        at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
        at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
        at org.graalvm.visualvm.lib.ui.components.HTMLTextArea.getPreferredSize(HTMLTextArea.java:690)
        at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
        - locked <0x00000007900ca858> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.preferredSize(Container.java:1799)
        - locked <0x00000007900ca858> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.getPreferredSize(Container.java:1783)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
        at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
        - locked <0x00000007900ca858> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.preferredSize(Container.java:1799)
        - locked <0x00000007900ca858> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.getPreferredSize(Container.java:1783)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
        at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
        at java.awt.Container.layout(Container.java:1513)
        at java.awt.Container.doLayout(Container.java:1502)
        at java.awt.Container.validateTree(Container.java:1698)
        at java.awt.Container.validate(Container.java:1633)
        - locked <0x00000007900ca858> (a java.awt.Component$AWTTreeLock)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

VisualVM 2.0.7
JDK 8u291
JDK 11.0.11
JDK 16.0.1

**Comment by thurka** [comment]
It looks like this is caused by bugfixes in JDK [JDK-8258373](https://bugs.openjdk.java.net/browse/JDK-8258373). Older JDKs, without the above fix, works fine.

**Comment by thurka** [comment]
Fixed in master.
