### ISSUE TITLE
NPE at TreeTableView.isColumnVisible(TreeTableView.java:287)

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#326]
**Describe the bug**
NPE from Truffle heapviewer
```
java.lang.NullPointerException
	at org.graalvm.visualvm.heapviewer.ui.TreeTableView.isColumnVisible(TreeTableView.java:287)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleObjectsView.setAggregation(TruffleObjectsView.java:334)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleObjectsView.configureObjectsBySize(TruffleObjectsView.java:254)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$ObjectsSection$8.run(TruffleSummaryView.java:553)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**To Reproduce**
1. open heap dump from GraalVM running JavaScript
2. switch to JavaScript Heap
3. in Overview click on 'view all' next to 'Objects by Size'
4. NPE is thrown

**Desktop (please complete the following information):**
 - macOS
 - JDK 1.8
 - since VisualVM 2.0

**Comment by jisedlac** [comment]
Fixed in master.
