### ISSUE TITLE
ProfilerPresets: Cannot invoke "String.indexOf(String)" because "args" is null

### ISSUE THREAD

**Issue by adiantek** [oracle/visualvm#329]
**Describe the bug**
Missing profiler option. I think it's due to the ARM64 platform.

**To Reproduce**
1. Go to Remote
2. Add host
3. Add JMX connection
4. I don't have Profiler option
4. See an error

**Expected behavior**

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/6873817/messages.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/13407885/126898126-1c34430c-d249-403b-9164-555a3cb56daf.png)
![image](https://user-images.githubusercontent.com/13407885/126898193-44442794-5c20-46ea-b65c-097ea76c14e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 on Surface Pro X (aarch64)
 - JDK version: https://github.com/microsoft/openjdk-aarch64/releases/tag/16-ea%2B19
 - Version: 2.1
```
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Organization:   N/A
Original Install Date:     02.07.2021, 05:01:44
System Boot Time:          23.07.2021, 08:38:22
System Manufacturer:       Microsoft Corporation
System Model:              Surface Pro X
System Type:               ARM64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: ARMv8 (64-bit) Family 8 Model 805 Revision D0E Qualcomm Technologies Inc ~2649 Mhz
BIOS Version:              Microsoft Corporation 7.570.140, 18.03.2021
```

**Additional context**
```
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "args" is null
	at org.graalvm.visualvm.profiling.presets.ProfilerPresets.getMainClass(ProfilerPresets.java:271)
	at org.graalvm.visualvm.profiling.presets.ProfilerPresets.getDefaultRootsP(ProfilerPresets.java:299)
	at org.graalvm.visualvm.profiling.presets.ProfilerPresets.createDefaultPreset(ProfilerPresets.java:251)
	at org.graalvm.visualvm.profiling.presets.ProfilerPresets.getPresets(ProfilerPresets.java:211)
	at org.graalvm.visualvm.profiling.presets.ProfilerPresets.createSelector(ProfilerPresets.java:168)
	at org.graalvm.visualvm.sampler.SamplerImpl.createSelector(SamplerImpl.java:194)
	at org.graalvm.visualvm.sampler.SamplerImpl.access$200(SamplerImpl.java:107)
	at org.graalvm.visualvm.sampler.SamplerImpl$1.createSelector(SamplerImpl.java:151)
	at org.graalvm.visualvm.sampler.cpu.CPUSettingsSupport.createPanel(CPUSettingsSupport.java:113)
	at org.graalvm.visualvm.sampler.cpu.CPUSettingsSupport.getDetailsView(CPUSettingsSupport.java:65)
	at org.graalvm.visualvm.sampler.SamplerImpl.setDataViewComponent(SamplerImpl.java:232)
	at org.graalvm.visualvm.sampler.ApplicationSamplerView.createComponent(ApplicationSamplerView.java:126)
	at org.graalvm.visualvm.core.ui.DataSourceView.getView(DataSourceView.java:194)
	at org.graalvm.visualvm.core.ui.DataSourceWindowTabbedPane$ViewContainer.setView(DataSourceWindowTabbedPane.java:231)
	at org.graalvm.visualvm.core.ui.DataSourceWindowTabbedPane$ViewContainer.<init>(DataSourceWindowTabbedPane.java:210)
	at org.graalvm.visualvm.core.ui.DataSourceWindowTabbedPane.addView(DataSourceWindowTabbedPane.java:121)
	at org.graalvm.visualvm.core.ui.DataSourceWindow.addView(DataSourceWindow.java:94)
[catch] at org.graalvm.visualvm.core.ui.DataSourceWindowManager$8.run(DataSourceWindowManager.java:352)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by jisedlac** [comment]
Reproducible on my side: Windows 10/amd64, JDK 16.0.2.

Regression, works fine in VisualVM 2.0.7 -- please confirm.
(can be downloaded at https://visualvm.github.io/releases.html)

Thanks for the bugreport!

**Comment by jisedlac** [comment]
Broken by https://github.com/oracle/visualvm/commit/c53976e03727d923a46c9a60adeaaee96290e50f.

**Comment by thurka** [comment]
The steps to reproduce are missing important step:

Remote application must be started with `-jar` parameter: `java -jar <jar_file>`

**Comment by thurka** [comment]
Fixed in master.
