### ISSUE TITLE
BTrace based tracer plugins do not work with GraalJS

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#334]
BTrace based tracer plugins do not work with GraalJS.

**Comment by likeablePanda** [comment]
If nothing else so that it shows in a google search-- would this be why i get this stacktrace when i try to sample or profile?
`java.lang.NullPointerException: Cannot invoke "org.graalvm.visualvm.lib.ui.swing.ProfilerTable.getActionMap()" because "table" is null
	at org.graalvm.visualvm.lib.ui.swing.SearchUtils.enableSearchActions(SearchUtils.java:188)
	at org.graalvm.visualvm.lib.ui.results.DataView$1.run(DataView.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`
