### ISSUE TITLE
NPE in InstanceNode.getName(InstanceNode.java:92)

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#335]
**Describe the bug**
```
java.lang.NullPointerException
	at org.graalvm.visualvm.heapviewer.java.InstanceNode.getName(InstanceNode.java:92)
	at org.graalvm.visualvm.heapviewer.java.InstanceNode.getValue(InstanceNode.java:168)
	at org.graalvm.visualvm.heapviewer.java.ThreadNode$Unknown.getValue(ThreadNode.java:90)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode.getValue(HeapViewerNode.java:291)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode.getValue(HeapViewerNode.java:286)
	at org.graalvm.visualvm.heapviewer.ui.TreeTableView$Model.getValueAt(TreeTableView.java:820)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$TableModelImpl.getValueAt(ProfilerTreeTable.java:867)
	at javax.swing.JTable.getValueAt(JTable.java:2720)
	at javax.swing.JTable.prepareRenderer(JTable.java:5712)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable.prepareRenderer(ProfilerTable.java:214)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable.getRenderer(ProfilerTable.java:342)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable.getRenderer(ProfilerTreeTable.java:458)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable.computeColumnPreferredWidth(ProfilerTable.java:702)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable.updateColumnsPreferredWidth(ProfilerTable.java:676)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable$9.adjustmentValueChanged(ProfilerTable.java:797)
	at javax.swing.JScrollBar.fireAdjustmentValueChanged(JScrollBar.java:705)
	at javax.swing.JScrollBar.access$100(JScrollBar.java:81)
	at javax.swing.JScrollBar$ModelListener.stateChanged(JScrollBar.java:727)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
	at javax.swing.JScrollBar.setValues(JScrollBar.java:623)
	at javax.swing.plaf.basic.BasicScrollPaneUI.syncScrollPaneWithViewport(BasicScrollPaneUI.java:285)
	at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1034)
	at javax.swing.JViewport.fireStateChanged(JViewport.java:1369)
	at javax.swing.JViewport.setViewSize(JViewport.java:1021)
	at javax.swing.ViewportLayout.layoutContainer(ViewportLayout.java:201)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**To Reproduce**
1. open heap dump
2. go to 'Threads'
3. NPE

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.
[messages.log](https://github.com/oracle/visualvm/files/7002070/messages.log)

**Desktop (please complete the following information):**
 - OS: macOS
 - JDK version: [JDK 1.8.0_181]
 - Version 2.1

**Comment by thurka** [comment]
Fixed in master.
