### ISSUE TITLE
Local Java applications cannot be detected - environment: RHEL Linux / IBM Java / Eclipse

### ISSUE THREAD

**Issue by julieka** [oracle/visualvm#35]
I am running Red Hat Enterprise Linux Server release 6.9 (Santiago). 
Using IBM JDK (ibm-java-x86_64-sdk-8.0-4.6.x86_64).  
I am using Eclipse (Mars.1 Release (4.5.1)) 
I installed VisualVM 1.3.9 and VisualVM Launcher.

I have a debug configuration which uses the VisualVM Launcher and VisualVM starts however it immediately displays the error "Local Java applications cannot be detected" with a link to https://visualvm.github.io/troubleshooting.html#jpswin and a second window "Cannot open requested application."  The suggestions in the troubleshooting guide suggests it can happen on Windows (I am running on Linux) and on Windows it is caused by permissions problems %TMP%\hsperfdata_username file.

I could not locate this file under Linux (what is the file name on Linux?) however all temporary directories have read/write access for the test id:
/home/me/.visualvm/1.3.9
/home/me/.cache/visualvm/1.3.9
/tmp

I tried starting visual vm with "-XX:+PerfBypassFileSystemCheck" as suggested in the guide
./visualvm --jdkhome /opt/ibm/java-x86_64-80 -XX:+PerfBypassFileSystemCheck
but this generated an error "unknown option"

The following is displayed if I ran from the command line:
Aug 16, 2017 4:55:20 PM org.openide.util.lookup.implspi.ActiveQueue reportError
WARNING: Cannot hack ReferenceQueue to fix bug #206621!
java.lang.NoSuchFieldException: lock
	at java.lang.Class.getDeclaredField(Class.java:779)
	at org.openide.util.lookup.implspi.ActiveQueue$Impl.<clinit>(ActiveQueue.java:83)
	at org.openide.util.lookup.implspi.ActiveQueue.queue(ActiveQueue.java:71)
	at org.openide.util.lookup.AbstractLookup.activeQueue(AbstractLookup.java:762)
	at org.openide.util.lookup.AbstractLookup.access$600(AbstractLookup.java:80)
	at org.openide.util.lookup.AbstractLookup$ReferenceToResult.<init>(AbstractLookup.java:1362)
	at org.openide.util.lookup.AbstractLookup$ReferenceToResult.<init>(AbstractLookup.java:1345)
	at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:496)
	at org.openide.util.Lookup.lookupResult(Lookup.java:251)
	at org.openide.util.Lookup.lookupAll(Lookup.java:271)
	at org.netbeans.MainImpl$BootClassLoader.allCLIs(MainImpl.java:376)
	at org.netbeans.CLIHandler.initialize(CLIHandler.java:384)
	at org.netbeans.MainImpl.execute(MainImpl.java:193)
	at org.netbeans.MainImpl.main(MainImpl.java:85)
	at org.netbeans.Main.main(Main.java:83)

What could be causing this problem? What can I do to troubleshoot and fix?

![image](https://user-images.githubusercontent.com/31079880/29384354-c39d8980-82a1-11e7-8127-ea171f32ad43.png)

**Comment by thurka** [comment]
The problem is caused by running VisualVM in IBM JDK. Please use Oracle JDK to run VisualVM. VisualVM can monitor processes running on IBM JDK via JMX connection.

**Comment by julieka** [comment]
I work for IBM and I am required to use IBM JDK, Oracle JDK is not an option.  Can you explain how to use JMX connection?  If there is some documentation or examples I will appreciate a pointer.   Thank you very much.

**Comment by thurka** [comment]
What about OpenJDK? Can you use OpenJDK?

**Comment by thurka** [comment]
There are several guides how to do it. Just search for `visualvm IBM JDK`. See for examle [Monitor a remote IBM Websphere with VisualVM and JMX](https://stackoverflow.com/questions/30253962/monitor-a-remote-ibm-websphere-with-visualvm-and-jmx). General information about JMX is  [here](http://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html)
Note that all guides uses Oracle JDK or OpenJDK to run VisualVM.

**Comment by tutak** [comment]
On a linux system the file is located at /tmp. I did the following steps to resolve the issue :

- Close all Java applications

- Make sure /tmp has appropriate permissions

- Remove hsperfdata_{username} from /tmp
