### ISSUE TITLE
NPE from HprofHeap.fillHeapTagBounds(HprofHeap.java:1320)

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#361]
```
java.lang.NullPointerException
	at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.fillHeapTagBounds(HprofHeap.java:1320)
	at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.<init>(HprofHeap.java:147)
	at org.graalvm.visualvm.lib.jfluid.heap.HeapFactory.createHeap(HeapFactory.java:87)
	at org.graalvm.visualvm.lib.jfluid.heap.HeapFactory.createHeap(HeapFactory.java:55)
	at org.graalvm.visualvm.heapviewer.HeapViewer.createHeap(HeapViewer.java:122)
	at org.graalvm.visualvm.heapviewer.HeapViewer.<init>(HeapViewer.java:72)
	at org.graalvm.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1.run(HeapDumpView.java:138)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```
**To Reproduce**
1. Open attached heap dump
2. See error

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/7485982/messages.log)

[nomimetype.zip](https://github.com/oracle/visualvm/files/7485985/nomimetype.zip)

**Comment by thurka** [comment]
Done in master.
