### ISSUE TITLE
NPE when trying to connect to packaged application

### ISSUE THREAD

**Issue by swpalmer** [oracle/visualvm#368]
Getting this exception whenever I try to connect to one of my applications (packaged with jpackage).  Am I missing a needed module in the JRE?  Didn't see anything in the troubleshooting documentation.

Several other applications running directly from the JDK connect okay.

```
java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String, String)" because "props" is null
	at org.graalvm.visualvm.sampler.truffle.SamplerSupport.isRunningOnGraalVM(SamplerSupport.java:86)
	at org.graalvm.visualvm.sampler.truffle.SamplerSupport.supportsProfiling(SamplerSupport.java:65)
	at org.graalvm.visualvm.sampler.truffle.ApplicationSamplerViewProvider.supportsViewFor(ApplicationSamplerViewProvider.java:40)
	at org.graalvm.visualvm.sampler.truffle.ApplicationSamplerViewProvider.supportsViewFor(ApplicationSamplerViewProvider.java:37)
	at org.graalvm.visualvm.core.ui.DataSourceViewsManager.getViews(DataSourceViewsManager.java:136)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.openWindowAndAddView(DataSourceWindowManager.java:262)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager.access$000(DataSourceWindowManager.java:52)
	at org.graalvm.visualvm.core.ui.DataSourceWindowManager$2.run(DataSourceWindowManager.java:121)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)```

**Comment by thurka** [comment]
Is there a way to reproduce it? I would like to fix the NPE.

**Comment by swpalmer** [comment]
I was using JDK 17.0.1 on Windows 10 Pro.  I don't think the packaging of the JRE had anything to do with it.  Just run a Java application from an Administrator command prompt, and then start VisualVM normally (not as Administrator).  Trying to connect to the JVM running as admin fails - but there is a little red dot in the bottom right that will show the NPE info when clicked.

**Comment by thurka** [comment]
Thanks, I was able to reproduce the NPE.

**Comment by thurka** [comment]
Fixed in master.
