### ISSUE TITLE
Error getting SA agent: ClassNotFoundException: sun.jvm.hotspot.HotSpotAgent

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#369]
**Describe the bug**
Windows, JDK 9+. Use SA to get Information from local process (when Attach API is disabled). 
```
java.lang.ClassNotFoundException: sun.jvm.hotspot.HotSpotAgent
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.graalvm.visualvm.sa.SAWrapper.classForName(SAWrapper.java:80)
	at org.graalvm.visualvm.sa.SAWrapper.HotSpotAgent(SAWrapper.java:92)
	at org.graalvm.visualvm.sa.Agent.<init>(Agent.java:60)
	at org.graalvm.visualvm.sa.Agent.getAgent(Agent.java:46)
	at org.graalvm.visualvm.sa.SaModelImpl.<init>(SaModelImpl.java:50)
[catch] at org.graalvm.visualvm.sa.SaModelProvider.createModelFor(SaModelProvider.java:84)
	at org.graalvm.visualvm.sa.SaModelProvider.createModelFor(SaModelProvider.java:45)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.tools.sa.SaModelFactory.getSAAgentFor(SaModelFactory.java:65)
	at org.graalvm.visualvm.jvm.JVMImpl.getSAAgent(JVMImpl.java:585)
	at org.graalvm.visualvm.jvm.JVMImpl.isTakeThreadDumpSupported(JVMImpl.java:431)
```

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/7651374/messages.log)

**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version JDK 9+
 - Version 2.1.1

**Comment by thurka** [comment]
Fixed in master.
