### ISSUE TITLE
NPE: Cannot invoke "Instance.getJavaClass()" because "loc" is null

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#370]
**Describe the bug**
Open heap dump from GraalVM EE with python
Switch to Python language

```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$1$1
java.lang.NullPointerException: Cannot invoke "org.graalvm.visualvm.lib.jfluid.heap.Instance.getJavaClass()" because "loc" is null
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getValueImpl(DynamicObject.java:462)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getEnterpriseValue(DynamicObject.java:736)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getValueImpl(DynamicObject.java:474)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getValue(DynamicObject.java:458)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.initFields(DynamicObject.java:231)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValues(DynamicObject.java:123)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValue(DynamicObject.java:128)
	at org.graalvm.visualvm.heapviewer.truffle.lang.python.PythonDetailsProvider.getDetailsString(PythonDetailsProvider.java:175)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:51)
	at org.graalvm.visualvm.heapviewer.truffle.lang.python.PythonViews$SummaryOverview.computeEnvironmentData(PythonViews.java:107)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$OverviewSection.computeData(TruffleSummaryView.java:238)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$1$1.run(TruffleSummaryView.java:124)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Desktop (please complete the following information):**
 - OS: macOS
 - JDK version: JDK 17.0.1
 - Version 2.1.1

**Comment by thurka** [comment]
Fixed in master.
