### ISSUE TITLE
CCE: class DynamicObject$Property$1 cannot be cast to class ObjectFieldValue

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#371]
**Describe the bug**
Open heap dump from GraalVM EE with Python
Browse 'module' class.

```
java.lang.ClassCastException: class org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property$1 cannot be cast to class org.graalvm.visualvm.lib.jfluid.heap.ObjectFieldValue (org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property$1 is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @3e18389d; org.graalvm.visualvm.lib.jfluid.heap.ObjectFieldValue is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @243f8737)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getPrimitiveArray(DynamicObject.java:758)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getEnterpriseValue(DynamicObject.java:736)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getValueImpl(DynamicObject.java:474)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.getValue(DynamicObject.java:458)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.initFields(DynamicObject.java:231)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValues(DynamicObject.java:123)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValue(DynamicObject.java:128)
	at org.graalvm.visualvm.heapviewer.truffle.lang.python.PythonDetailsProvider.getDetailsString(PythonDetailsProvider.java:175)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:51)
	at org.graalvm.visualvm.heapviewer.truffle.lang.python.PythonNodes.getLogicalValue(PythonNodes.java:205)
	at org.graalvm.visualvm.heapviewer.truffle.lang.python.PythonNodes$PythonObjectNode.computeLogicalValue(PythonNodes.java:239)
	at org.graalvm.visualvm.heapviewer.truffle.lang.python.PythonNodes$PythonObjectNode.computeLogicalValue(PythonNodes.java:222)
	at org.graalvm.visualvm.heapviewer.truffle.nodes.TruffleObjectNode$InstanceBased.getLogicalValue(TruffleObjectNode.java:100)
	at org.graalvm.visualvm.heapviewer.truffle.nodes.TruffleObjectNode$Renderer.setValue(TruffleObjectNode.java:169)
	at org.graalvm.visualvm.heapviewer.ui.TreeTableViewRenderer.setValue(TreeTableViewRenderer.java:77)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$ProfilerRendererWrapper.setValue(ProfilerTreeTable.java:488)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$ProfilerRendererWrapper.getTreeCellRendererComponent(ProfilerTreeTable.java:478)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3223)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:555)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:201)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:680)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:673)
	at java.desktop/javax.swing.JTree.getPathBounds(JTree.java:2194)
	at java.desktop/javax.swing.JTree.getRowBounds(JTree.java:2207)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$ProfilerTreeTableTree.getTableCellRendererComponent(ProfilerTreeTable.java:1411)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5797)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTable.prepareRenderer(ProfilerTable.java:214)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2210)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2112)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1908)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1155)
	at java.desktop/javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1731)
	at java.desktop/javax.swing.JViewport.windowBlitPaint(JViewport.java:1684)
	at java.desktop/javax.swing.JViewport.setViewPosition(JViewport.java:1219)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.vsbStateChanged(BasicScrollPaneUI.java:1189)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1178)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:371)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:309)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:175)
	at java.desktop/javax.swing.JScrollBar.setValue(JScrollBar.java:486)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.mouseWheelMoved(BasicScrollPaneUI.java:1124)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$MouseWheelHandler.mouseWheelMoved(BasicScrollPaneUI.java:651)
	at java.desktop/com.apple.laf.AquaScrollPaneUI$XYMouseWheelHandler.mouseWheelMoved(AquaScrollPaneUI.java:45)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTableContainer$5.mouseWheelMoved(ProfilerTableContainer.java:193)
	at java.desktop/java.awt.Component.processMouseWheelEvent(Component.java:6714)
	at java.desktop/java.awt.Component.processEvent(Component.java:6398)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventToSelf(Container.java:2348)
	at java.desktop/java.awt.Component.dispatchMouseWheelToAncestor(Component.java:5146)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4898)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4604)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
```
**Desktop (please complete the following information):**
 - OS: macOS
 - JDK version 17.0.1
 - Version 2.1.1

**Comment by thurka** [comment]
Fixed in master.
