### ISSUE TITLE
ArrayIndexOutOfBoundsException on Memory Snapshot Diff Class Expansion

### ISSUE THREAD

**Issue by MaisiKoleni** [oracle/visualvm#412]
**Describe the bug**

Making two memory profiling snapshots and comparing them with each other leads to a partial GUI crash when I try to expand a class entry that is present in one but not the other. 

Stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10588
	at org.graalvm.visualvm.lib.jfluid.results.memory.MemoryResultsSnapshot.createPresentationCCT(MemoryResultsSnapshot.java:213)
	at org.graalvm.visualvm.lib.jfluid.results.memory.LivenessMemoryResultsSnapshot.createPresentationCCT(LivenessMemoryResultsSnapshot.java:329)
	at org.graalvm.visualvm.lib.jfluid.results.memory.LivenessMemoryResultsDiff.createPresentationCCT(LivenessMemoryResultsDiff.java:162)
	at org.graalvm.visualvm.lib.jfluid.results.memory.LivenessMemoryResultsDiff.createPresentationCCT(LivenessMemoryResultsDiff.java:44)
	at org.graalvm.visualvm.lib.jfluid.results.memory.MemoryCCTManager.<init>(MemoryCCTManager.java:46)
	at org.graalvm.visualvm.lib.ui.memory.LivenessTreeTableView$1Node.getChildren(LivenessTreeTableView.java:254)
	at org.graalvm.visualvm.lib.ui.memory.LivenessTreeTableView$1Node.getChildCount(LivenessTreeTableView.java:266)
	at java.desktop/javax.swing.tree.DefaultTreeModel.getChildCount(DefaultTreeModel.java:201)
	at org.graalvm.visualvm.lib.ui.swing.ProfilerTreeTable$FilteredTreeModel.getChildCount(ProfilerTreeTable.java:926)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache$VisibleFHTreeStateNodeEnumeration.updateNextIndex(FixedHeightLayoutCache.java:1599)
	[ ... a lot more GUI stack frames ... ]
```

**Potential Fix**

The reason is that `MemoryResultsSnapshot.createPresentationCCT` gets `-1` and cannot handle it.
The issue seems to be that `LivenessMemoryResultsDiff.createPresentationCCT` does not take care of this:
https://github.com/oracle/visualvm/blob/a3f92891acf7e96308f24938d85ea22702ac924e/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/results/memory/LivenessMemoryResultsDiff.java#L180-L185

I imagine the solution would look very similar to `JdbcResultsDiff.createPresentationCCT`:
https://github.com/oracle/visualvm/blob/a3f92891acf7e96308f24938d85ea22702ac924e/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/results/jdbc/JdbcResultsDiff.java#L83-L96

A similar issue could be somewhere else in the code as well, e.g.:
https://github.com/oracle/visualvm/blob/a3f92891acf7e96308f24938d85ea22702ac924e/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/results/jdbc/JdbcResultsDiff.java#L110-L115
I have not tested this one, but there seems to be an array access based on the class index further down the line as well.

There might be even more similar problems, I haven't checked the whole codebase.

**Alternative Fix**
`MemoryResultsSnapshot.createPresentationCCT` and alike return `null` if the class is `-1`.

**Comment by thurka** [comment]
> Making two heap dumps and comparing them with each other leads to a partial GUI crash when I try to expand a class entry that is present in one but not the other.

Just to be sure - you are talking about snapshots from memory profiling with an allocation stack traces. There is no way to expand a class entry when comparing heap dumps, so the AIOOB exception cannot be reproduced with heap dumps.

**Comment by MaisiKoleni** [comment]
> > Making two heap dumps and comparing them with each other leads to a partial GUI crash when I try to expand a class entry that is present in one but not the other.
> 
> Just to be sure - you are talking about snapshots from memory profiling with an allocation stack traces. There is no way to expand a class entry when comparing heap dumps, so the AIOOB exception cannot be reproduced with heap dumps.

Yes, sorry. I used both and get them mixed up.

**Comment by thurka** [comment]
Thanks for clarification.

**Comment by thurka** [comment]
Fixed in master.
