### ISSUE TITLE
NPE in TruffleFrame.getObjectArray

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#424]
**Describe the bug**
Python heap dump from GraalVM 22.3.0-dev.

**To Reproduce**
1. Open heap dump from python
2. Show 'Truffle Object' for FrameWithoutBoxing
3. NPE

```
java.lang.NullPointerException
	at org.graalvm.visualvm.heapviewer.truffle.TruffleFrame.getObjectArray(TruffleFrame.java:151)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleFrame.<init>(TruffleFrame.java:79)
	at org.graalvm.visualvm.heapviewer.truffle.javaext.TruffleFieldsProvider$InstanceFieldsProvider.getFields(TruffleFieldsProvider.java:160)
	at org.graalvm.visualvm.heapviewer.truffle.javaext.TruffleFieldsProvider.getNodes(TruffleFieldsProvider.java:65)
	at org.graalvm.visualvm.heapviewer.truffle.javaext.TruffleFieldsProvider$InstanceFieldsProvider.getNodes(TruffleFieldsProvider.java:116)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode.lazilyComputeChildren(HeapViewerNode.java:243)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode$1.doInBackground(HeapViewerNode.java:180)
	at org.graalvm.visualvm.heapviewer.model.HeapViewerNode$1.doInBackground(HeapViewerNode.java:166)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by thurka** [comment]
Fixed in master.
