### ISSUE TITLE
NPE in TruffleFrame.createLocals()

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#436]
Steps:
1. Open python heap dump from GraalVM
2. switch to 'python threads'.
3. NPE, see below

```
java.lang.NullPointerException
	at org.graalvm.visualvm.heapviewer.truffle.TruffleFrame.createLocals(TruffleFrame.java:216)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleFrame.<init>(TruffleFrame.java:88)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$HotSpotTruffleRuntime.findLocalFrame(TruffleStackTraces.java:438)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$HotSpotTruffleRuntime.visitFrame(TruffleStackTraces.java:452)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$HotSpotTruffleRuntime.access$2300(TruffleStackTraces.java:330)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$FrameVisitor.visitFrame(TruffleStackTraces.java:625)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$FrameVisitor.access$1500(TruffleStackTraces.java:544)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$HotSpotTruffleRuntime.computeStackTrace(TruffleStackTraces.java:376)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$HotSpotTruffleRuntime.getStackTraces(TruffleStackTraces.java:475)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces$HotSpotTruffleRuntime.access$500(TruffleStackTraces.java:330)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleStackTraces.<init>(TruffleStackTraces.java:63)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleThreadsProvider.getThreadsHTML(TruffleThreadsProvider.java:171)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleThreadsView$2.computeData(TruffleThreadsView.java:108)
	at org.graalvm.visualvm.heapviewer.ui.HTMLView$2$2.doInBackground(HTMLView.java:191)
	at org.graalvm.visualvm.heapviewer.ui.HTMLView$2$2.doInBackground(HTMLView.java:189)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by thurka** [comment]
Fixed in master.
