### ISSUE TITLE
NPE from JvmJvmstatModel.getFirstArgument()

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#442]
In some rare cases `JvmJvmstatModel.getCommandLine()` and `Jvm.getJvmArgs()` can return `null`. This leads to various NPEs like the one below:
```
java.lang.NullPointerException
	at org.graalvm.visualvm.tools.jvmstat.JvmJvmstatModel.getFirstArgument(JvmJvmstatModel.java:282)
	at org.graalvm.visualvm.tools.jvmstat.JvmJvmstatModel.getMainArgs(JvmJvmstatModel.java:231)
	at org.graalvm.visualvm.graalvm.svm.SVMJVMImpl.initStaticData(SVMJVMImpl.java:410)
	at org.graalvm.visualvm.graalvm.svm.SVMJVMImpl.getMainClass(SVMJVMImpl.java:128)
	at org.graalvm.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:163)
	at org.graalvm.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:42)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.application.type.ApplicationTypeFactory.getApplicationTypeFor(ApplicationTypeFactory.java:74)
	at org.graalvm.visualvm.application.ApplicationDescriptor.<init>(ApplicationDescriptor.java:65)
	at org.graalvm.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:43)
	at org.graalvm.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:38)
	at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
	at org.graalvm.visualvm.core.datasource.descriptor.DataSourceDescriptorFactory.getDescriptor(DataSourceDescriptorFactory.java:69)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processAddedDisplayableDataSources(ExplorerModelBuilder.java:159)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processIndependentAddedDataSources(ExplorerModelBuilder.java:120)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.processAddedDataSources(ExplorerModelBuilder.java:109)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder.access$200(ExplorerModelBuilder.java:59)
	at org.graalvm.visualvm.core.explorer.ExplorerModelBuilder$1.run(ExplorerModelBuilder.java:99)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
```

**Comment by thurka** [comment]
Fixed in master.
