### ISSUE TITLE
VisualVM does not start wth Java 11

### ISSUE THREAD

**Issue by MarybethGasman** [oracle/visualvm#467]
visualvm can not start

visualvm.exe --jdkhome D:\jdk-11.0.2  --trace  log.txt
command line output
![image](https://user-images.githubusercontent.com/90539473/203991597-9f6e3141-7567-4b88-a26c-0462e7eec1ab.png)
**VisualVM log**
[log.txt](https://github.com/oracle/visualvm/files/10092950/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows10
 - JDK version: 11.0.2
 - Version 2.15

**Comment by thurka** [comment]
The log file from launcher looks OK and java process is started. Can you please try to run visualvm with:
```
visualvm.exe --jdkhome D:\jdk-11.0.2 -J-Dnetbeans.logger.console=true
```
and attach the console output. Thanks.

**Comment by MarybethGasman** [comment]
I got a NullPointerException.
```
>Log Session: Friday, November 25, 2022 at 10:21:51 PM China Standard Time
>System Info:
  Product Version         = VisualVM 2.1.5
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 11.0.2; Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 11.0.2+9-LTS
  Java Home               = D:\jdk-11.0.2
  System Locale; Encoding = zh_CN (visualvm); GBK
  Home Directory          = C:\Users\Think
  Current Directory       = C:\Users\Think\Desktop\visualvm_215\bin
  User Directory          = C:\Users\Think\AppData\Roaming\VisualVM\2.1.5
  Cache Directory         = C:\Users\Think\AppData\Local\VisualVM\Cache\2.1.5
  Installation            = C:\Users\Think\Desktop\visualvm_215\visualvm
                            C:\Users\Think\Desktop\visualvm_215\platform
  Boot & Ext. Classpath   =
  Application Classpath   = C:\Users\Think\Desktop\visualvm_215\platform\lib\boot.jar;C:\Users\Think\Desktop\visualvm_215\platform\lib\org-openide-modules.jar;C:\Users\Think\Desktop\visualvm_215\platform\lib\org-openide-util-lookup.jar;C:\Users\Think\Desktop\visualvm_215\platform\lib\org-openide-util-ui.jar;C:\Users\Think\Desktop\visualvm_215\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\Think\Desktop\visualvm_215\platform\core\asm-9.2.jar;C:\Users\Think\Desktop\visualvm_215\platform\core\asm-commons-9.2.jar;C:\Users\Think\Desktop\visualvm_215\platform\core\asm-tree-9.2.jar;C:\Users\Think\Desktop\visualvm_215\platform\core\core-base.jar;C:\Users\Think\Desktop\visualvm_215\platform\core\core.jar;C:\Users\Think\Desktop\visualvm_215\platform\core\org-netbeans-libs-asm.jar;C:\Users\Think\Desktop\visualvm_215\platform\core\org-openide-filesystems.jar;C:\Users\Think\Desktop\visualvm_215\visualvm\core\org-graalvm-visualvm-modules-startup.jar;C:\Users\Think\Desktop\visualvm_215\visualvm\core\locale\core_visualvm.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.core.startup.Main]
java.lang.NullPointerException
        at java.base/java.net.URLConnection$1.getContentTypeFor(URLConnection.java:313)
        at java.base/java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1464)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getContentType(JarURLConnection.java:223)
        at java.base/java.net.URLConnection.getContentHandler(URLConnection.java:1277)
        at java.base/java.net.URLConnection.getContent(URLConnection.java:778)
        at java.base/java.net.URL.getContent(URL.java:1150)
        at org.openide.util.lookup.MetaInfServicesLookup.search(MetaInfServicesLookup.java:293)
        at org.openide.util.lookup.MetaInfServicesLookup.beforeLookup(MetaInfServicesLookup.java:132)
        at org.openide.util.lookup.MetaInfServicesLookup.beforeLookupResult(MetaInfServicesLookup.java:111)
        at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:458)
        at org.openide.util.lookup.ProxyLookup$R.initResults(ProxyLookup.java:449)
        at org.openide.util.lookup.ProxyLookup$R.addLookupListener(ProxyLookup.java:548)
        at org.netbeans.ProxyURLStreamHandlerFactory.createURLStreamHandler(ProxyURLStreamHandlerFactory.java:130)
        at java.base/java.net.URL.getURLStreamHandler(URL.java:1415)
        at java.base/java.net.URL.<init>(URL.java:449)
        at java.base/java.net.URL.fromURI(URL.java:699)
        at java.base/java.net.URI.toURL(URI.java:1116)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:227)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:247)
        at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:146)
        at java.base/java.lang.Class.getResourceAsStream(Class.java:2633)
        at java.base/sun.net.www.MimeTable.load(MimeTable.java:240)
        at java.base/sun.net.www.MimeTable.<init>(MimeTable.java:73)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder$1.run(MimeTable.java:83)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder$1.run(MimeTable.java:81)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder.getDefaultInstance(MimeTable.java:80)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder.<clinit>(MimeTable.java:77)
Caused: java.lang.ExceptionInInitializerError
        at java.base/sun.net.www.MimeTable.getDefaultTable(MimeTable.java:96)
        at java.base/sun.net.www.MimeTable.loadTable(MimeTable.java:103)
        at java.base/java.net.URLConnection$1.<init>(URLConnection.java:310)
        at java.base/java.net.URLConnection.getFileNameMap(URLConnection.java:308)
        at java.base/java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1464)
        at org.netbeans.JarClassLoader$NbJarURLConnection.getContentType(JarClassLoader.java:1110)
        at java.desktop/javax.swing.JEditorPane.handleConnectionProperties(JEditorPane.java:780)
        at java.desktop/javax.swing.JEditorPane.getStream(JEditorPane.java:756)
        at java.desktop/javax.swing.JEditorPane.setPage(JEditorPane.java:433)
        at org.graalvm.visualvm.modules.startup.LicensePanel.<init>(LicensePanel.java:51)
        at org.graalvm.visualvm.modules.startup.AcceptLicense.showLicensePanel(AcceptLicense.java:70)
Caused: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[catch] at org.netbeans.core.startup.Main$1LicenseHandler.run(Main.java:470)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\Think\AppData\Roaming\VisualVM\2.1.5\var\log\messages.log
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\Think\AppData\Roaming\VisualVM\2.1.5\var\log
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\Think\AppData\Roaming\VisualVM\2.1.5\var
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\Think\AppData\Roaming\VisualVM\2.1.5
```

**Comment by thurka** [comment]
This is strange. Can you please try to upgrade JDK 11 to the latest version (11.0.17) or use JDK 17. If it fails, please post new log. Thanks.

**Comment by thurka** [comment]
There are similar bugs reported against NetBeans:
[crash in org.netbeans.core.startup.Main.getModuleSystem #4652](https://github.com/apache/netbeans/issues/4652)
[Error in startup caused by proxy #3958](https://github.com/apache/netbeans/issues/3958)

Both errors happen with JDK 11.0.2, you also use 11.0.2 - this suggest that updating JDK might fix it.

**Comment by thurka** [comment]
I am able to reproduce NPE with JDK 11.0.2, JDK 11.0.3 and JDK 11.0.4. JDK 11.0.5 works fine, please update your JDK.

**Comment by MarybethGasman** [comment]
You'are right, It works fine now. Thanks a lot.😀

**Comment by rajvijay68** [comment]
I got the same error with OpenJDK 11.0.2
It worked with OpenJDK 17.0.4


```bash
# This works
$ visualvm --jdkhome ~/.sdkman/candidates/java/17.0.4.1-ms/


# Doesn't work with 11.0.2
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)



$ visualvm -h
Usage: /home/tester/visualvm_215/platform/lib/nbexec {options} arguments

General options:
  --help                show this help 
  --jdkhome <path>      path to Java(TM) 2 SDK, Standard Edition
  -J<jvm_option>        pass <jvm_option> to JVM

  --cp:p <classpath>    prepend <classpath> to classpath
  --cp:a <classpath>    append <classpath> to classpath
/home/tester/visualvm_215/platform/lib/nbexec: WARNING: environment variable DISPLAY is not set
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.net.URLConnection$1.getContentTypeFor(URLConnection.java:313)
        at java.base/java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1464)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getContentType(JarURLConnection.java:223)
        at java.base/java.net.URLConnection.getContentHandler(URLConnection.java:1277)
        at java.base/java.net.URLConnection.getContent(URLConnection.java:778)
        at java.base/java.net.URL.getContent(URL.java:1150)
        at org.openide.util.lookup.MetaInfServicesLookup.search(MetaInfServicesLookup.java:293)
        at org.openide.util.lookup.MetaInfServicesLookup.beforeLookup(MetaInfServicesLookup.java:132)
        at org.openide.util.lookup.MetaInfServicesLookup.beforeLookupResult(MetaInfServicesLookup.java:111)
        at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:458)
        at org.openide.util.lookup.ProxyLookup$R.lookupChange(ProxyLookup.java:519)
        at org.openide.util.lookup.ProxyLookup.setData(ProxyLookup.java:372)
        at org.openide.util.lookup.ProxyLookup.setLookups(ProxyLookup.java:211)
        at org.openide.util.lookup.ProxyLookup.setLookups(ProxyLookup.java:184)
        at org.netbeans.core.startup.MainLookup.changeLookups(MainLookup.java:193)
        at org.netbeans.core.startup.MainLookup.systemClassLoaderChanged(MainLookup.java:93)
        at org.netbeans.core.startup.CLICoreBridge.usage(CLICoreBridge.java:105)
        at org.netbeans.CLIHandler.showHelp(CLIHandler.java:137)
        at org.netbeans.CLIHandler.checkHelp(CLIHandler.java:191)
        at org.netbeans.CLIHandler.initialize(CLIHandler.java:544)
        at org.netbeans.CLIHandler.initialize(CLIHandler.java:360)
        at org.netbeans.MainImpl.execute(MainImpl.java:168)
        at org.netbeans.MainImpl.main(MainImpl.java:60)
        at org.netbeans.Main.main(Main.java:58)
```
