### ISSUE TITLE
NPE in RecursiveMethodInstrumentor.scanBytecode()

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#475]
```
java.lang.NullPointerException
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.scanBytecode(RecursiveMethodInstrumentor.java:238)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:409)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.processInvoke(RecursiveMethodInstrumentor2.java:321)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.scanBytecode(RecursiveMethodInstrumentor.java:282)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:407)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:425)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.processInvoke(RecursiveMethodInstrumentor2.java:321)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.scanBytecode(RecursiveMethodInstrumentor.java:282)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:407)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:445)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.processInvoke(RecursiveMethodInstrumentor2.java:321)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.scanBytecode(RecursiveMethodInstrumentor.java:282)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:407)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.processInvoke(RecursiveMethodInstrumentor2.java:321)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.scanBytecode(RecursiveMethodInstrumentor.java:282)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:407)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.processInvoke(RecursiveMethodInstrumentor2.java:321)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.scanBytecode(RecursiveMethodInstrumentor.java:282)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.checkAndScanMethod(RecursiveMethodInstrumentor2.java:407)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.tryInstrumentSpawnedThreads(RecursiveMethodInstrumentor2.java:333)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.getInitialMethodsToInstrument(RecursiveMethodInstrumentor2.java:90)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.Instrumentor.createInitialInstrumentMethodGroupResponseForCallGraph(Instrumentor.java:440)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.Instrumentor.createInitialInstrumentMethodGroupResponse(Instrumentor.java:289)
	at org.graalvm.visualvm.lib.jfluid.ProfilerClient.instrumentMethodGroupFromRoot(ProfilerClient.java:1919)
	at org.graalvm.visualvm.lib.jfluid.ProfilerClient.access$200(ProfilerClient.java:74)
[catch] at org.graalvm.visualvm.lib.jfluid.ProfilerClient$SeparateCmdExecutionThread.run(ProfilerClient.java:105)
```

**Comment by thurka** [comment]
Happens only with eager instrumentation scheme.

**Comment by thurka** [comment]
Fixed in master.
