### ISSUE TITLE
ArrayIndexOutOfBoundsException in "eager instrumentation scheme"

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#490]
Profiling in eager instrumentation scheme on JDK 11+ sometimes fails with the `ArrayIndexOutOfBoundsException` below:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.createInstrumentedMethodPack15(RecursiveMethodInstrumentor.java:506)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor.createInstrumentedMethodPack(RecursiveMethodInstrumentor.java:345)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.RecursiveMethodInstrumentor2.getMethodsToInstrumentUponClassLoad(RecursiveMethodInstrumentor2.java:242)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.Instrumentor.createFollowUpInstrumentMethodGroupResponseForCallGraph(Instrumentor.java:357)
	at org.graalvm.visualvm.lib.jfluid.instrumentation.Instrumentor.createFollowUpInstrumentMethodGroupResponse(Instrumentor.java:249)
	at org.graalvm.visualvm.lib.jfluid.ProfilerClient.instrumentMethodGroupFollowUp(ProfilerClient.java:1886)
	at org.graalvm.visualvm.lib.jfluid.ProfilerClient.access$300(ProfilerClient.java:74)
[catch] at org.graalvm.visualvm.lib.jfluid.ProfilerClient$SeparateCmdExecutionThread.run(ProfilerClient.java:111)
```

**Comment by thurka** [comment]
Fixed in master.
