### ISSUE TITLE
Cannot Go to Source with certain External Viewers

### ISSUE THREAD

**Issue by TechPizzaDev** [oracle/visualvm#491]
**Describe the bug**
Certain External Viewer commands cannot open source files, seemingly because of a space in the Windows username.

**To Reproduce**
1. Sample java app
2. Try to **Go to Source**
![image](https://user-images.githubusercontent.com/23627133/233163702-3280ceef-7a5d-49d1-a741-89cca5da26df.png)
3. Error.

**Expected behavior**
The chosen External Viewer opens with the file.

**VisualVM log**
```java
INFO [org.graalvm.visualvm.gotosource.viewer.ExternalSourcesViewer]: Opening external sources viewer failed
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
	at java.lang.ProcessImpl.start(ProcessImpl.java:140)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Caused: java.io.IOException: Cannot run program "code" (in directory "C:\Users\A~1\AppData\Local\Temp\visualvm_A B.dat"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[catch] at org.graalvm.visualvm.gotosource.viewer.ExternalViewerLauncher.run(ExternalViewerLauncher.java:55)
	at org.graalvm.visualvm.gotosource.viewer.ExternalSourcesViewer.executeCommand(ExternalSourcesViewer.java:237)
	at org.graalvm.visualvm.gotosource.viewer.ExternalSourcesViewer.open(ExternalSourcesViewer.java:179)
	at org.graalvm.visualvm.gotosource.VisualVMGoToSource.openSourceImpl(VisualVMGoToSource.java:62)
	at org.graalvm.visualvm.gotosource.VisualVMGoToSource.access$000(VisualVMGoToSource.java:55)
	at org.graalvm.visualvm.gotosource.VisualVMGoToSource$Provider.openSource(VisualVMGoToSource.java:87)
	at org.graalvm.visualvm.lib.profiler.api.GoToSource.openSourceImpl(GoToSource.java:127)
	at org.graalvm.visualvm.lib.profiler.api.GoToSource.access$100(GoToSource.java:43)
	at org.graalvm.visualvm.lib.profiler.api.GoToSource$2.run(GoToSource.java:100)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/23627133/233163406-64069a8a-4972-43b9-a917-e711fc09f3a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0.19045)
 - JDK version: OpenJDK Runtime Environment Temurin-20+36 (build 20+36)
 - Version: VisualVM 2.1.5

**Additional context**
Adding quotes around the path in the command in Tools>Options>Sources changes nothing.
Certain external viewers (e.g. Notepad) work, while VSCode, Notepad++ or IDEA do not work.

**Comment by thurka** [comment]
Please attach whole `messages.log` file. Thanks.

**Comment by thurka** [comment]
This `Caused: java.io.IOException: Cannot run program "code" (in directory ` looks like you did not specified path to VSCode executable. Can you configure VisualVM with full path to VSCode executable? This should fix it.

**Comment by jisedlac** [comment]
> seemingly because of a space in the Windows username

The most probable reason is that you haven't provided full path to the selected external viewer. While Notepad is on a system path and thus works out of the box, the other viewers obviously are not and the system doesn't know how to launch them (`Cannot run program "code"`).

To configure an external viewer, please [follow the documentation](https://visualvm.github.io/sourcessupport.html#config-viewer) and provide the correct command to start the viewer.

**Comment by jisedlac** [comment]
> Full paths work fine.
