### ISSUE TITLE
CPU sampler tree navigate / search capabilities

### ISSUE THREAD

**Issue by nezda** [oracle/visualvm#492]
It is hard to find Hotspot entries in the Forward calls tree of the CPU Sampler. In my programs, Hotspots will often reveal lambdas like `com.foo.Baz$Lambda$1365+0x000000080104ead0.2086177500.test()` which I'd like to trace to named methods that call them. I'd like to be able to reveal/navigate from the Hotspots entry to all callers in the Forward calls tree. Alternatively, I'd like to be able to search for (in my example) `1365` or something equally unique in the Forward call tree to find the culprit(s).

**Solution I'd like**

I'd like to be able to right click the Hotspots entry to reveal/navigate to all callers in for Forward calls tree.
Alternatively, I'd like to have a search box or find-as-you-type that reveals matches in the Forward calls tree.

**Alternatives considered**

Alternatively, if I could export all of those trees somehow, e.g., select all nodes and copy paste into a text editor, find the culprit there and deduce which thread path(s) to expand to find a particular method, that would work, but is also not possible: you can only select one node at a time.

**Comment by nezda** [comment]
Related: https://stackoverflow.com/questions/41570839/finding-a-java-lambda-from-its-mangled-name-in-a-heap-dump

**Comment by thurka** [comment]
You can select the lambda method in Hotspots and invoke 'Find in Forward Calls' from its context menu - this will reveal this method in Forward calls tree. You can repeat that to find additional occurrences.  Similarly you can also use 'Find in Reverse Calls', where you could be able to find out methods that call it.

**Comment by nezda** [comment]
@thurka that sounds awesome! (Funny, I thought I remembered this feature!) When I right click on a Hot spot call no context menu comes up.

As an example, I can get a context menu for JFR Snapshots

![image](https://user-images.githubusercontent.com/179091/235742195-7fa0dce8-6782-4b24-88f4-d9bc5d095a5b.png)

but nothing happens in for the Hot spot rows.

![image](https://user-images.githubusercontent.com/179091/235742512-c0af8aa4-066e-4c32-9261-f2801fd8a285.png)

```
Version: 2.1.5 (Build 221003); platform 20220908-c4f2d87113
System: Mac OS X (13.1) , x86_64 64bit
Java: 17.0.5; OpenJDK 64-Bit Server VM (17.0.5+8, mixed mode, sharing)
```

**Comment by thurka** [comment]
This is really strange. The context menu should look like this:
<img width="824" alt="hotspots" src="https://user-images.githubusercontent.com/22048069/235752318-0456d413-2caa-423b-8b7c-fe2182b54523.png">

**Comment by nezda** [comment]
I updated to 2.1.6 with https://formulae.brew.sh/cask/visualvm and set my `visualvm_jdkhome`: same problem.

I also tried initiating the samping from VisualVM itself instead of opening a Java Flight Recording I'd made elsewhere: same problem.

```
Version: 2.1.6 (Build 230324); platform 20220908-c4f2d87113
System: Mac OS X (13.1) , x86_64 64bit
Java: 17.0.5; OpenJDK 64-Bit Server VM (17.0.5+8, mixed mode, sharing)
Vendor: Eclipse Adoptium, https://adoptium.net/
Environment: UTF-8; en_US (visualvm)
User directory: /Users/nezda/Library/Application Support/VisualVM/2.1.6
Cache directory: /Users/nezda/Library/Caches/VisualVM/2.1.6
Clusters: 
/Applications/VisualVM.app/Contents/Resources/visualvm/platform
/Applications/VisualVM.app/Contents/Resources/visualvm/visualvm
```

**Comment by nezda** [comment]
I should've looked in the log sooner: `java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.event.InputEvent.modifiers accessible: module java.desktop does not "opens java.awt.event" to unnamed module @3afc27e1`. Added `-J--add-opens=java.desktop/java.awt.event=ALL-UNNAMED` to `visualvm_default_options` worked!

```
INFO [null]: Last record repeated 4 more times.
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2045)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4907)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.event.InputEvent.modifiers accessible: module java.desktop does not "opens java.awt.event" to unnamed module @3afc27e1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.netbeans.modules.applemenu.CtrlClickHack.eventDispatched(CtrlClickHack.java:95)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2197)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2088)
INFO [null]: Last record repeated 4 more times.
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2045)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4907)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by thurka** [comment]
> I should've looked in the log sooner

:-) This is why we ask for log in the bug template. 

It is good that you discovered that is going on. The reason it is working for me is that you are  using ctrl-click instead of right-click to invoke the context menu. 
Can you please file a new issue that ctrl-click does not work on macOS with JDK 17+. Thanks.

**Comment by nezda** [comment]
Tricky that I saw a context menu for JFR Snapshots but not in CPU Sampler. Anyway, opened #498 - thanks for this great tool!

**Comment by thurka** [comment]
>  thanks for this great tool!

We're pleased to hear that. Thanks!
