### ISSUE TITLE
OQL: TypeError: Right-hand-side of instanceof is not callable in <eval> at line number 1299

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#515]
Steps to reproduce:
1. use dev. build of GraalVM (23.1.0-dev) from mid August
2. install GraalJS
3. run profiler.oql unit tests
4. some test fails

The following OQL fails: `select map(heap.findClass("java.io.File").statics, "index + '=' + toHtml(it)")` with exception below:
```
Testcase: testMap(org.graalvm.visualvm.lib.profiler.oql.engine.api.impl.OQLEngineTest):	Caused an ERROR
javax.script.ScriptException: TypeError: Right-hand-side of instanceof is not callable in <eval> at line number 1299 at column number 16
org.graalvm.visualvm.lib.profiler.oql.engine.api.OQLException: javax.script.ScriptException: TypeError: Right-hand-side of instanceof is not callable in <eval> at line number 1299 at column number 16
	at org.graalvm.visualvm.lib.profiler.oql.engine.api.impl.OQLEngineImpl.executeQuery(OQLEngineImpl.java:300)
	at org.graalvm.visualvm.lib.profiler.oql.engine.api.impl.OQLEngineImpl.executeQuery(OQLEngineImpl.java:114)
	at org.graalvm.visualvm.lib.profiler.oql.engine.api.OQLEngine.executeQuery(OQLEngine.java:97)
	at org.graalvm.visualvm.lib.profiler.oql.engine.api.impl.OQLEngineTest.testMap(OQLEngineTest.java:517)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Caused by: javax.script.ScriptException: TypeError: Right-hand-side of instanceof is not callable in <eval> at line number 1299 at column number 16
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:524)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:492)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine$11.eval(GraalJSScriptEngine.java:673)
	at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:107)
	at org.graalvm.visualvm.lib.profiler.oql.engine.api.impl.OQLEngineImpl.executeQuery(OQLEngineImpl.java:294)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: Right-hand-side of instanceof is not callable
	at <js>.wrapIterator(<eval>:1299)
	at <js>.map(<eval>:1572)
	at <js>.__select__(<eval>:1)
	at <js>.:program(<eval>:2)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context.eval(Context.java:403)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:490)
```

**Comment by thurka** [comment]
Fixed in master.
