### ISSUE TITLE
VisualVM doesn't start when using OpenJDK 11

### ISSUE THREAD

**Issue by ghevge** [oracle/visualvm#541]
I have openJDK 11 installed on my windows 10 system, and when I try to launch VisualVM, nothing happens. 
When I try to launch it from the command line, I get some warnings but nothing more. The VisualVM still doesn't pop up.
Any idea what is goin on ?

Command line message:
```
Desktop\visualvm_217\bin>visualvm.exe

C:\Users\bebe\Desktop\visualvm_217\bin>

The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: package sun.awt.X11 not in java.desktop
```

Java version:

```
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by thurka** [comment]
Can you please try to run visualvm with `-J-Dnetbeans.logger.console=true`?
```
C:\Users\bebe\Desktop\visualvm_217\bin>visualvm.exe -J-Dnetbeans.logger.console=true
```
Post the output. Thanks.

**Comment by ghevge** [comment]
The output for your request:

```
C:\Users\bebe\Desktop\visualvm_217\bin>visualvm.exe -J-Dnetbeans.logger.console=true

C:\Users\bebe\Desktop\visualvm_217\bin>

The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: package sun.awt.X11 not in java.desktop
-------------------------------------------------------------------------------
>Log Session: Tuesday, December 19, 2023 at 4:29:59 PM Eastern Standard Time
>System Info:
  Product Version         = VisualVM 2.1.7
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 11.0.2; OpenJDK 64-Bit Server VM 11.0.2+9; Oracle Corporation
  Runtime                 = OpenJDK Runtime Environment 11.0.2+9
  Java Home               = C:\Program Files\Java\jdk-11.0.2
  System Locale; Encoding = en_CA (visualvm); Cp1252
  Home Directory          = C:\Users\bebe
  Current Directory       = C:\Users\bebe\Desktop\visualvm_217\bin
  User Directory          = C:\Users\bebe\AppData\Roaming\VisualVM\2.1.7
  Cache Directory         = C:\Users\bebe\AppData\Local\VisualVM\Cache\2.1.7
  Installation            = C:\Users\bebe\Desktop\visualvm_217\visualvm
                            C:\Users\bebe\Desktop\visualvm_217\platform
  Boot & Ext. Classpath   =
  Application Classpath   = C:\Users\bebe\Desktop\visualvm_217\platform\lib\boot.jar;C:\Users\bebe\Desktop\visualvm_217\platform\lib\org-openide-modules.jar;C:\Users\bebe\Desktop\visualvm_217\platform\lib\org-openide-util-lookup.jar;C:\Users\bebe\Desktop\visualvm_217\platform\lib\org-openide-util-ui.jar;C:\Users\bebe\Desktop\visualvm_217\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\bebe\Desktop\visualvm_217\platform\core\asm-9.2.jar;C:\Users\bebe\Desktop\visualvm_217\platform\core\asm-commons-9.2.jar;C:\Users\bebe\Desktop\visualvm_217\platform\core\asm-tree-9.2.jar;C:\Users\bebe\Desktop\visualvm_217\platform\core\core-base.jar;C:\Users\bebe\Desktop\visualvm_217\platform\core\core.jar;C:\Users\bebe\Desktop\visualvm_217\platform\core\org-netbeans-libs-asm.jar;C:\Users\bebe\Desktop\visualvm_217\platform\core\org-openide-filesystems.jar;C:\Users\bebe\Desktop\visualvm_217\visualvm\core\org-graalvm-visualvm-modules-startup.jar;C:\Users\bebe\Desktop\visualvm_217\visualvm\core\locale\core_visualvm.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.core.startup.Main]
java.lang.NullPointerException
        at java.base/java.net.URLConnection$1.getContentTypeFor(URLConnection.java:313)
        at java.base/java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1464)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getContentType(JarURLConnection.java:223)
        at java.base/java.net.URLConnection.getContentHandler(URLConnection.java:1277)
        at java.base/java.net.URLConnection.getContent(URLConnection.java:778)
        at java.base/java.net.URL.getContent(URL.java:1150)
        at org.openide.util.lookup.MetaInfServicesLookup.search(MetaInfServicesLookup.java:293)
        at org.openide.util.lookup.MetaInfServicesLookup.beforeLookup(MetaInfServicesLookup.java:132)
        at org.openide.util.lookup.MetaInfServicesLookup.beforeLookupResult(MetaInfServicesLookup.java:111)
        at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:458)
        at org.openide.util.lookup.ProxyLookup$R.initResults(ProxyLookup.java:449)
        at org.openide.util.lookup.ProxyLookup$R.addLookupListener(ProxyLookup.java:548)
        at org.netbeans.ProxyURLStreamHandlerFactory.createURLStreamHandler(ProxyURLStreamHandlerFactory.java:130)
        at java.base/java.net.URL.getURLStreamHandler(URL.java:1415)
        at java.base/java.net.URL.<init>(URL.java:449)
        at java.base/java.net.URL.fromURI(URL.java:699)
        at java.base/java.net.URI.toURL(URI.java:1116)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:227)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:247)
        at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:146)
        at java.base/java.lang.Class.getResourceAsStream(Class.java:2633)
        at java.base/sun.net.www.MimeTable.load(MimeTable.java:240)
        at java.base/sun.net.www.MimeTable.<init>(MimeTable.java:73)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder$1.run(MimeTable.java:83)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder$1.run(MimeTable.java:81)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder.getDefaultInstance(MimeTable.java:80)
        at java.base/sun.net.www.MimeTable$DefaultInstanceHolder.<clinit>(MimeTable.java:77)
Caused: java.lang.ExceptionInInitializerError
        at java.base/sun.net.www.MimeTable.getDefaultTable(MimeTable.java:96)
        at java.base/sun.net.www.MimeTable.loadTable(MimeTable.java:103)
        at java.base/java.net.URLConnection$1.<init>(URLConnection.java:310)
        at java.base/java.net.URLConnection.getFileNameMap(URLConnection.java:308)
        at java.base/java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1464)
        at org.netbeans.JarClassLoader$NbJarURLConnection.getContentType(JarClassLoader.java:1110)
        at java.desktop/javax.swing.JEditorPane.handleConnectionProperties(JEditorPane.java:780)
        at java.desktop/javax.swing.JEditorPane.getStream(JEditorPane.java:756)
        at java.desktop/javax.swing.JEditorPane.setPage(JEditorPane.java:433)
        at org.graalvm.visualvm.modules.startup.LicensePanel.<init>(LicensePanel.java:51)
        at org.graalvm.visualvm.modules.startup.AcceptLicense.showLicensePanel(AcceptLicense.java:70)
Caused: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[catch] at org.netbeans.core.startup.Main$1LicenseHandler.run(Main.java:470)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\bebe\AppData\Roaming\VisualVM\2.1.7\var\log\messages.log
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\bebe\AppData\Roaming\VisualVM\2.1.7\var\log
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\bebe\AppData\Roaming\VisualVM\2.1.7\var
WARNING [org.netbeans.core.startup.Main]: Failed to delete C:\Users\bebe\AppData\Roaming\VisualVM\2.1.7
```

**Comment by thurka** [comment]
Thanks for the log file. It shows that you are using old version of JDK 11 - JDK 11.0.2. This particular version of JDK 11 causes this NPE. Please upgrade your JDK 11 to JDK 11.0.3 or newer. Current version is 11.0.20. For more details see duplicate bug GH-467.
