### ISSUE TITLE
VisualVm stuck in "Computing Retained Sizes..."

### ISSUE THREAD

**Issue by jukzi** [oracle/visualvm#552]
I have a 4GB heapdump from an eclipse IDE that VisualVM (and JDK Mission Control too) fail to analyse.
VisualVM is stuck  at 33%:
![image](https://github.com/oracle/visualvm/assets/51790620/d4a2ada2-ead0-4e68-a54f-6e5565e49a27)

Any chance it helps if i make the heapdump available for download?

VisualVM itself has enough memory and is reponsive but just does not progress the calculation.
Feels like there is a circular something inside the heapdump.

![image](https://github.com/oracle/visualvm/assets/51790620/b27a5b98-1073-44a3-8cfd-0fdf8a4aa3d2)

threaddump:

```
2024-01-31 14:17:18
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode):

"Inactive RequestProcessor thread [Was:VisualVM Shared RequestProcessor/org.graalvm.visualvm.tools.jmx.CachedMBeanServerConnectionFactory$SnapshotInvocationHandler$2]" #68 daemon prio=1 os_prio=-2 tid=0x000000002f0f0800 nid=0x6adc in Object.wait() [0x0000000033d3f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1977)
        - locked <0x00000005d5ae3768> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"Swing-Shell" #61 daemon prio=6 os_prio=0 tid=0x000000002f0ef000 nid=0x2220 waiting on condition [0x000000002a7be000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c09f6f58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Win32ShellFolderManager2.java:556)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"SwingWorker-pool-6-thread-5" #59 daemon prio=5 os_prio=0 tid=0x000000002f0e4800 nid=0x9d0 waiting on condition [0x000000002a5be000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c2a31c90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"SwingWorker-pool-6-thread-4" #58 daemon prio=5 os_prio=0 tid=0x000000002f0eb800 nid=0x5f84 waiting on condition [0x000000002a4be000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c2a31c90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"SwingWorker-pool-6-thread-3" #57 daemon prio=5 os_prio=0 tid=0x000000002f0e3000 nid=0x5df4 waiting on condition [0x000000002a3bf000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c2a31c90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"SwingWorker-pool-6-thread-2" #56 daemon prio=5 os_prio=0 tid=0x000000002f0ea000 nid=0x54f8 waiting on condition [0x000000002a2bf000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c2a31c90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"SwingWorker-pool-6-thread-1" #55 daemon prio=5 os_prio=0 tid=0x000000002f0e4000 nid=0x43f8 waiting on condition [0x0000000029ebe000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c2a31c90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"VisualVM Shared RequestProcessor" #53 daemon prio=1 os_prio=-2 tid=0x000000002f0e2800 nid=0x5980 runnable [0x0000000000c8e000]
   java.lang.Thread.State: RUNNABLE
        at sun.tools.attach.WindowsVirtualMachine.enqueue(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.execute(WindowsVirtualMachine.java:96)
        at sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:261)
        at sun.tools.attach.HotSpotVirtualMachine.remoteDataDump(HotSpotVirtualMachine.java:218)
        at org.graalvm.visualvm.attach.AttachModelImpl.takeThreadDump(AttachModelImpl.java:93)
        - locked <0x00000005c0b61cc8> (a org.graalvm.visualvm.attach.AttachModelImpl)
        at org.graalvm.visualvm.jvm.JVMImpl.takeThreadDump(JVMImpl.java:436)
        at org.graalvm.visualvm.threaddump.impl.ThreadDumpProvider$1.run(ThreadDumpProvider.java:83)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

   Locked ownable synchronizers:
        - None

"Retained Sizes Computer" #48 daemon prio=1 os_prio=-2 tid=0x000000002f0e9000 nid=0x69ec in Object.wait() [0x0000000029fbf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.openide.util.Task.waitFinished(Task.java:139)
        - locked <0x00000005c339e408> (a org.openide.util.RequestProcessor$Task)
        at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1711)
        at org.graalvm.visualvm.heapviewer.utils.HeapOperations.initializeRetainedSizesImpl(HeapOperations.java:233)
        at org.graalvm.visualvm.heapviewer.utils.HeapOperations.initializeRetainedSizes(HeapOperations.java:81)
        at org.graalvm.visualvm.heapviewer.model.DataType$RetainedSize.computeValuesImmediately(DataType.java:212)
        at org.graalvm.visualvm.heapviewer.model.DataType$RetainedSize$1.run(DataType.java:198)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

   Locked ownable synchronizers:
        - None

"pool-4-thread-1" #44 prio=5 os_prio=0 tid=0x000000002f0ea800 nid=0xf4c waiting on condition [0x0000000034f3f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c2426b90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"Sampler timer for Eclipse (pid 23088)" #43 daemon prio=1 os_prio=-2 tid=0x000000002f0ee800 nid=0x5a98 in Object.wait() [0x000000002ff4f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.util.TimerThread.mainLoop(Timer.java:526)
        - locked <0x00000005c2339028> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
        - None

"JMX client heartbeat 2" #42 daemon prio=1 os_prio=-2 tid=0x000000002f0e1800 nid=0x54f4 waiting on condition [0x000000003463f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker.run(ClientCommunicatorAdmin.java:175)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"RMI Scheduler(0)" #41 daemon prio=1 os_prio=-2 tid=0x000000002f0e8800 nid=0x6bf4 waiting on condition [0x000000003453e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c0b2bc88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"GC Daemon" #40 daemon prio=2 os_prio=-2 tid=0x000000002f0e7800 nid=0x6b54 in Object.wait() [0x000000003443f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at sun.misc.GC$Daemon.run(GC.java:117)
        - locked <0x00000005c0bb2330> (a sun.misc.GC$LatencyLock)

   Locked ownable synchronizers:
        - None

"RMI RenewClean-[10.245.0.164:55342]" #39 daemon prio=1 os_prio=-2 tid=0x000000002f0e7000 nid=0x2d84 in Object.wait() [0x000000003433f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000005c0bb2530> (a java.lang.ref.ReferenceQueue$Lock)
        at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(DGCClient.java:563)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"Timer-0" #37 daemon prio=1 os_prio=-2 tid=0x000000002f0e5800 nid=0x4444 in Object.wait() [0x000000003403f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.util.TimerThread.mainLoop(Timer.java:552)
        - locked <0x00000005c0ae1768> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
        - None

"DestroyJavaVM" #31 prio=5 os_prio=0 tid=0x0000000027792800 nid=0x466c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"TimerQueue" #30 daemon prio=5 os_prio=0 tid=0x0000000027790800 nid=0x6a50 runnable [0x00000000317ef000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c0b825e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.DelayQueue.take(DelayQueue.java:223)
        at javax.swing.TimerQueue.run(TimerQueue.java:174)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x00000005c0b82608> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"Thread-4" #29 daemon prio=5 os_prio=0 tid=0x0000000027790000 nid=0x6908 in Object.wait() [0x00000000315ef000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000005c0ab3740> (a java.util.LinkedList)
        at java.lang.Object.wait(Object.java:502)
        at java.util.prefs.AbstractPreferences$EventDispatchThread.run(AbstractPreferences.java:1482)
        - locked <0x00000005c0ab3740> (a java.util.LinkedList)

   Locked ownable synchronizers:
        - None

"File Watcher" #26 daemon prio=1 os_prio=-2 tid=0x000000002778e800 nid=0x3070 waiting on condition [0x000000003008e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005c08a3538> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at org.netbeans.modules.masterfs.watcher.windows.WindowsNotifier.nextEvent(WindowsNotifier.java:229)
        at org.netbeans.modules.masterfs.providers.Notifier$1.nextEvent(Notifier.java:99)
        at org.netbeans.modules.masterfs.watcher.Watcher$Ext.run(Watcher.java:322)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"JNA Cleaner" #25 daemon prio=1 os_prio=-2 tid=0x000000002778d800 nid=0x5d10 in Object.wait() [0x000000002fb2f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000005c08b2060> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)

   Locked ownable synchronizers:
        - None

"AWT-EventQueue-0" #22 prio=6 os_prio=0 tid=0x000000002950f800 nid=0x3774 runnable [0x000000002b97e000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Object.notifyAll(Native Method)
        at org.openide.util.RequestProcessor$TickTac.cancel(RequestProcessor.java:2220)
        - locked <0x00000005c07655c8> (a java.lang.Class for org.openide.util.RequestProcessor$TickTac)
        at org.openide.util.RequestProcessor$Item.clear(RequestProcessor.java:1761)
        at org.openide.util.RequestProcessor$Task.schedule(RequestProcessor.java:1478)
        - locked <0x00000005c06fc6c8> (a java.lang.Object)
        at org.openide.util.RequestProcessor$Task.schedule(RequestProcessor.java:1459)
        at org.openide.util.TimedSoftReference.get(TimedSoftReference.java:112)
        - locked <0x00000005c0dffaf8> (a java.util.HashMap)
        at org.openide.util.NbBundle.getBundleFast(NbBundle.java:502)
        - locked <0x00000005c0dffaf8> (a java.util.HashMap)
        at org.openide.util.NbBundle.getBundle(NbBundle.java:433)
        at org.openide.util.NbBundle.getBundle(NbBundle.java:386)
        at org.openide.util.NbBundle.getMessage(NbBundle.java:637)
        at org.netbeans.modules.progress.ui.ListComponent.<init>(ListComponent.java:110)
        at org.netbeans.modules.progress.ui.StatusLineComponent.createListItem(StatusLineComponent.java:459)
        at org.netbeans.modules.progress.ui.StatusLineComponent.processProgressEvent(StatusLineComponent.java:279)
        at org.netbeans.modules.progress.spi.Controller.runNow(Controller.java:393)
        at org.netbeans.modules.progress.spi.SwingController.run(SwingController.java:72)
        at org.netbeans.modules.progress.spi.SwingController$2.run(SwingController.java:79)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
        - None

"AWT-Windows" #20 daemon prio=6 os_prio=0 tid=0x0000000029507800 nid=0x3e00 runnable [0x000000002b78f000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WToolkit.eventLoop(Native Method)
        at sun.awt.windows.WToolkit.run(WToolkit.java:313)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"AWT-Shutdown" #19 prio=5 os_prio=0 tid=0x0000000029506800 nid=0x4e94 in Object.wait() [0x000000002b68f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
        - locked <0x00000005c06fa158> (a java.lang.Object)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"Java2D Disposer" #18 daemon prio=10 os_prio=2 tid=0x0000000029500000 nid=0x504c in Object.wait() [0x000000002b48e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000005c06e95b0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at sun.java2d.Disposer.run(Disposer.java:148)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"RequestProcessor queue manager" #17 daemon prio=5 os_prio=0 tid=0x000000002949b800 nid=0x4658 in Object.wait() [0x000000002b0fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.openide.util.RequestProcessor$TickTac.obtainFirst(RequestProcessor.java:2257)
        - locked <0x00000005c07655c8> (a java.lang.Class for org.openide.util.RequestProcessor$TickTac)
        at org.openide.util.RequestProcessor$TickTac.run(RequestProcessor.java:2233)

   Locked ownable synchronizers:
        - None

"Retained Sizes Computer" #15 daemon prio=1 os_prio=-2 tid=0x000000002943c800 nid=0x3124 runnable [0x000000002abbe000]
   java.lang.Thread.State: RUNNABLE
        at org.graalvm.visualvm.lib.jfluid.heap.DominatorTree.computeOneLevel(DominatorTree.java:161)
        at org.graalvm.visualvm.lib.jfluid.heap.DominatorTree.computeDominators(DominatorTree.java:85)
        - locked <0x00000005d33d3f58> (a org.graalvm.visualvm.lib.jfluid.heap.DominatorTree)
        at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.computeRetainedSize(HprofHeap.java:730)
        - locked <0x00000005c25a6808> (a java.lang.Object)
        at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.getRetainedSize(HprofHeap.java:436)
        at org.graalvm.visualvm.lib.jfluid.heap.InstanceDump.getRetainedSize(InstanceDump.java:99)
        at org.graalvm.visualvm.heapviewer.utils.HeapOperations$3.run(HeapOperations.java:208)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

   Locked ownable synchronizers:
        - None

"CLI Requests Server" #14 daemon prio=5 os_prio=0 tid=0x000000002944b800 nid=0x28fc runnable [0x000000002aabf000]
   java.lang.Thread.State: RUNNABLE
        at java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
        - locked <0x00000005c06fb978> (a java.net.SocksSocketImpl)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at org.netbeans.CLIHandler$Server.run(CLIHandler.java:1079)

   Locked ownable synchronizers:
        - None

"Active Reference Queue Daemon" #13 daemon prio=1 os_prio=-2 tid=0x00000000292d7800 nid=0x6be4 in Object.wait() [0x0000000029bbf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000005c06e9798> (a java.lang.ref.ReferenceQueue$Lock)
        at org.openide.util.lookup.implspi.ActiveQueue$Impl.remove(ActiveQueue.java:67)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at org.openide.util.lookup.implspi.ActiveQueue$Impl.remove(ActiveQueue.java:76)
        at org.openide.util.lookup.implspi.ActiveQueue$Daemon.run(ActiveQueue.java:121)

   Locked ownable synchronizers:
        - None

"Service Thread" #10 daemon prio=9 os_prio=0 tid=0x00000000275dc800 nid=0x3c28 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C1 CompilerThread3" #9 daemon prio=9 os_prio=2 tid=0x0000000027536000 nid=0x2d58 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000000027534000 nid=0x44c0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x000000002752c000 nid=0x59a4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x0000000027522800 nid=0x5cb0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x0000000027520800 nid=0x1c30 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000002751f800 nid=0x2708 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x0000000025de2800 nid=0x266c in Object.wait() [0x000000002880f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000005c06e7ca8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000274b3000 nid=0x24b4 in Object.wait() [0x000000002870f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000005c07669e8> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=2 tid=0x0000000025dd7000 nid=0x40bc runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002a89800 nid=0x6154 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002a8b000 nid=0x213c runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002a8c800 nid=0x10e8 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002a8e800 nid=0x3ae4 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x0000000002a90800 nid=0xfb8 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x0000000002a91800 nid=0x6320 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x0000000002a95000 nid=0x2588 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x0000000002a96000 nid=0x6120 runnable 

"GC task thread#8 (ParallelGC)" os_prio=0 tid=0x0000000002a97000 nid=0x226c runnable 

"GC task thread#9 (ParallelGC)" os_prio=0 tid=0x0000000002a98800 nid=0x30b4 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x0000000027573000 nid=0x2214 waiting on condition 

JNI global references: 902


```

VisualVm sampling itself:

![image](https://github.com/oracle/visualvm/assets/51790620/98fd02ef-ffa2-4d97-adca-6a9300e994c9)

**Comment by thurka** [comment]
If you can share the heap dump, it would be great.

**Comment by jukzi** [comment]
> If you can share the heap dump, it would be great.

please download within 2 weeks:
https://securetransfer.ssi-schaefer.com/webdownload?deliveryUuid=e4da41ca-4c39-4a59-8458-f2265def6b80

**Comment by thurka** [comment]
Thanks I have your heap dump.
