### ISSUE TITLE
Unable to open Connection

### ISSUE THREAD

**Issue by gauravn00b** [oracle/visualvm#554]
Getting below error:
java.util.regex.PatternSyntaxException: Illegal repetition near index 9
^https://${asg_hostname}.*?$

JMXConnection:
service:jmx:rmi:///jndi/rmi://localhost:9901/jmxrmi

**Comment by gauravn00b** [comment]
Sorry for delayed response.

Open a SSH Tunnel in Mobaxterm to connect to remote server via Jump server. Now open as localhost in VisualVM.

Logs:
-------------------------------------------------------------------------------
>Log Session: Tuesday, February 13, 2024 at 2:07:57 PM India Standard Time
>System Info: 
  Product Version         = VisualVM 2.1.7
  Operating System        = Windows 11 version 10.0 running on amd64
  Java; VM; Vendor        = 11.0.20; Java HotSpot(TM) 64-Bit Server VM 11.0.20+9-LTS-256; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 11.0.20+9-LTS-256
  Java Home               = C:\Program Files\Java\jdk-11
  System Locale; Encoding = en_IN (visualvm); Cp1252
  Home Directory          = C:\Users\gaurav8.jain
  Current Directory       = C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\bin
  User Directory          = C:\Users\gaurav8.jain\AppData\Roaming\VisualVM\2.1.7
  Cache Directory         = C:\Users\gaurav8.jain\AppData\Local\VisualVM\Cache\2.1.7
  Installation            = C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\visualvm
                            C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform
  Boot & Ext. Classpath   = 
  Application Classpath   = C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\lib\boot.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\lib\org-openide-modules.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\lib\org-openide-util-lookup.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\lib\org-openide-util-ui.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\asm-9.2.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\asm-commons-9.2.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\asm-tree-9.2.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\core-base.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\core.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\org-netbeans-libs-asm.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform\core\org-openide-filesystems.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\visualvm\core\org-graalvm-visualvm-modules-startup.jar;C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\visualvm\core\locale\core_visualvm.jar
-------------------------------------------------------------------------------
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.50 20230511-c4f2d87113]
	org.openide.util [9.24 20230511-c4f2d87113]
	org.openide.util.ui [9.24 20230511-c4f2d87113]
	org.openide.modules [7.64 20230511-c4f2d87113]
	org.netbeans.api.annotations.common/1 [1.44 20230511-c4f2d87113]
	org.openide.filesystems [9.28 20230511-c4f2d87113]
	org.openide.awt [7.84 20230511-c4f2d87113]
	org.netbeans.api.progress/1 [1.64 20230511-c4f2d87113]
	org.netbeans.api.progress.nb [1.64 20230511-c4f2d87113]
	org.openide.dialogs [7.61 20230511-c4f2d87113]
	org.openide.nodes [7.61 20230511-c4f2d87113]
	org.openide.windows [6.93 20230511-c4f2d87113]
	org.netbeans.modules.editor.mimelookup/1 [1.56 20230511-c4f2d87113]
	org.openide.text [6.84 20230511-c4f2d87113]
	org.netbeans.api.scripting [1.13 20230511-c4f2d87113]
	org.netbeans.swing.tabcontrol [1.72 20230511-c4f2d87113]
	org.netbeans.swing.outline [1.50 20230511-c4f2d87113]
	org.openide.explorer [6.78 20230511-c4f2d87113]
	org.openide.actions [6.55 20230511-c4f2d87113]
	org.netbeans.modules.queries/1 [1.59 20230511-c4f2d87113]
	org.netbeans.api.templates [1.24 20230511-c4f2d87113]
	org.openide.filesystems.nb [9.26 20230511-c4f2d87113]
	org.openide.loaders [7.86 20230511-c4f2d87113]
	org.netbeans.api.intent [1.18 20230511-c4f2d87113]
	org.netbeans.api.io [1.19 20230511-c4f2d87113]
	org.openide.io [1.65 20230511-c4f2d87113]
	org.netbeans.swing.plaf [1.58 20230511-c4f2d87113]
	org.netbeans.modules.keyring [1.40 20230511-c4f2d87113]
	org.netbeans.libs.asm [5.19 20230511-c4f2d87113]
	org.netbeans.bootstrap/1 [2.94 20230511-c4f2d87113]
	org.netbeans.core.startup.base [1.78.0.1 1 20230511-c4f2d87113]
	org.netbeans.core.startup/1 [1.78.0.1 20230511-c4f2d87113]
	org.netbeans.modules.sampler [1.30 20230511-c4f2d87113]
	org.netbeans.core/2 [3.67 20230511-c4f2d87113]
	org.netbeans.spi.quicksearch [1.43 20230511-c4f2d87113]
	org.netbeans.modules.options.api/1 [1.61 20230511-c4f2d87113]
	org.netbeans.libs.flatlaf/1 [1.10 20230511-c4f2d87113]
	org.netbeans.swing.laf.flatlaf [1.9 20230511-c4f2d87113]
	org.netbeans.modules.settings/1 [1.65 20230511-c4f2d87113]
	org.netbeans.modules.sendopts/2 [2.52 20230511-c4f2d87113]
	org.netbeans.modules.progress.ui [1.49 20230511-c4f2d87113]
	org.netbeans.modules.options.keymap [1.53 20230511-c4f2d87113]
	org.netbeans.libs.jna/2 [2.13 20230511-c4f2d87113]
	org.netbeans.modules.masterfs/2 [2.71.0.2 2 20230511-c4f2d87113]
	org.netbeans.modules.masterfs.windows [1.32 20230511-c4f2d87113]
	org.netbeans.modules.masterfs.ui [2.19.0.2 20230511-c4f2d87113]
	org.netbeans.modules.masterfs.nio2 [1.31 20230511-c4f2d87113]
	org.netbeans.modules.keyring.fallback [1.24 20230511-c4f2d87113]
	org.netbeans.modules.keyring.impl [1.40 20230511-c4f2d87113]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.48 20230511-c4f2d87113]
	org.netbeans.modules.autoupdate.services [1.71 20230511-c4f2d87113]
	org.netbeans.modules.autoupdate.ui [1.62 20230511-c4f2d87113]
	org.netbeans.modules.autoupdate.cli [1.30 20230511-c4f2d87113]
	org.netbeans.libs.jna.platform/2 [2.13 20230511-c4f2d87113]
	org.netbeans.core.windows/2 [2.101 20230511-c4f2d87113]
	org.netbeans.core.ui/1 [1.61 20230511-c4f2d87113]
	org.netbeans.core.network [1.28 20230511-c4f2d87113]
	org.netbeans.core.nativeaccess/1 [1.47 20230511-c4f2d87113]
	org.netbeans.core.multitabs/1 [1.28.0.1 1 20230511-c4f2d87113]
	org.netbeans.core.io.ui/1 [1.46 20230511-c4f2d87113]
	org.graalvm.visualvm.lib.jfluid/2 [2.15 230906]
	org.graalvm.visualvm.lib.charts/2 [2.1 230906]
	org.graalvm.visualvm.lib.common/2 [2.8 230906]
	org.graalvm.visualvm.lib.profiler.api/2 [2.2 230906]
	org.graalvm.visualvm.lib.ui/2 [2.4 230906]
	org.graalvm.visualvm.uisupport/2 [2.1 230906]
	org.graalvm.visualvm.core/2 [2.4 230906]
	org.graalvm.visualvm.host/2 [2.1 230906]
	org.graalvm.visualvm.application/2 [2.4 230906]
	org.graalvm.visualvm.tools/2 [2.3 230906]
	org.graalvm.visualvm.coredump/2 [2.1 230906]
	org.graalvm.visualvm.threaddump/2 [2.1 230906]
	org.graalvm.visualvm.lib.profiler.utilities/2 [2.0 230906]
	org.graalvm.visualvm.lib.profiler.attach/2 [2.1 230906]
	org.graalvm.visualvm.lib.profiler/2 [2.4 230906]
	org.graalvm.visualvm.lib.profiler.snaptracer/2 [2.0 230906]
	org.graalvm.visualvm.profiling/2 [2.3 230906]
	org.graalvm.visualvm.lib.jfluid.heap [1.3 230906]
	org.graalvm.visualvm.lib.profiler.oql/2 [2.0 230906]
	org.graalvm.visualvm.lib.profiler.heapwalker/2 [2.2 230906]
	org.graalvm.visualvm.heapviewer/2 [2.8 230906]
	org.graalvm.visualvm.heapdump/2 [2.1 230906]
	org.graalvm.visualvm.sampler.truffle/2 [2.1 230906]
	org.graalvm.visualvm.sampler/2 [2.2 230906]
	org.graalvm.visualvm.sa/2 [2.0 230906]
	org.graalvm.visualvm.modules.startup/2 [2.1 230906]
	org.graalvm.visualvm.profiler/2 [2.1 230906]
	org.graalvm.visualvm.pluginimporter [1.0 230906]
	org.graalvm.visualvm.modules.appui/2 [2.1 230906]
	org.graalvm.visualvm.jvmstat/2 [2.0 230906]
	org.graalvm.visualvm.jvm/2 [2.0 230906]
	org.graalvm.visualvm.jmx/2 [2.2 230906]
	org.graalvm.visualvm.charts/2 [2.1 230906]
	org.graalvm.visualvm.jfr/2 [2.3 230906]
	org.graalvm.visualvm.jfr.jdk9/2 [2.1 230906]
	org.graalvm.visualvm.jfr.jdk11/2 [2.1 230906]
	org.graalvm.visualvm.jfr.generic/2 [2.4 230906]
	org.graalvm.visualvm.host.views/2 [2.0 230906]
	org.graalvm.visualvm.host.remote/2 [2.0 230906]
	org.graalvm.visualvm.heapviewer.truffle/2 [2.1 230906]
	org.graalvm.visualvm.heapviewer.console/2 [2.0 230906]
	org.graalvm.visualvm.application.views/2 [2.1 230906]
	org.graalvm.visualvm.graalvm/2 [2.0 230906]
	org.graalvm.visualvm.gotosource/2 [2.0 230906]
	org.graalvm.visualvm.attach/2 [2.0 230906]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Windows
INFO [org.netbeans.core.network.proxy.windows.WindowsNetworkProxy]: Windows system proxy resolver: auto - PAC (http://proxypac.ril.com/iaccess.pac)
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
Warning: Nashorn engine is planned to be removed from a future JDK release
INFO [null]: Last record repeated again.
WARNING [org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator]: Error when executing PAC script function FindProxyForURL : 
java.util.regex.PatternSyntaxException: Illegal repetition near index 9
^https://${asg_hostname}.*?$
         ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2213)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at org.netbeans.core.network.proxy.pac.PacUtils.createRegexPatternFromGlob(PacUtils.java:115)
	at org.netbeans.core.network.proxy.pac.impl.NbPacHelperMethods.shExpMatch(NbPacHelperMethods.java:161)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$13$751AA$\^eval\_.L:1#L:34(<eval>:35)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$12$\^eval\_.:scopeCall(<eval>)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$12$\^eval\_.FindProxyForURL(<eval>:3)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:659)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197)
	at org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator$PacScriptEngine.findProxyForURL(NbPacScriptEvaluator.java:551)
[catch] at org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator.findProxyForURL(NbPacScriptEvaluator.java:223)
	at org.netbeans.core.network.proxy.ProxyAutoConfig.findProxyForURL(ProxyAutoConfig.java:145)
	at org.netbeans.core.network.proxy.NetworkProxyReloader.reloadNetworkProxy(NetworkProxyReloader.java:92)
	at org.netbeans.core.network.proxy.NbProxySelector.lambda$new$0(NbProxySelector.java:58)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: auto
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - pac url: http://proxypac.ril.com/iaccess.pac
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy TEST - http host: 
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy TEST - http port: 0
Diagnostic information
Input arguments:
	-Xms24m
	-Xmx768m
	-Dnetbeans.accept_license_class=org.graalvm.visualvm.modules.startup.AcceptLicense
	-Dnetbeans.importclass=org.graalvm.visualvm.modules.startup.ImportSettings
	-Dsun.jvmstat.perdata.syncWaitMs=10000
	-Dsun.java2d.noddraw=true
	-Dsun.java2d.d3d=false
	-Dorg.netbeans.core.TimeableEventQueue.quantum=360000
	-Dpolyglot.js.nashorn-compat=true
	-Dsun.misc.URLClassPath.disableJarChecking=true
	-Djdk.attach.allowAttachSelf=true
	-Dorg.openide.util.ImageUtilities.level=950
	--add-exports=java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED
	--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
	--add-exports=java.desktop/sun.swing=ALL-UNNAMED
	--add-exports=jdk.attach/sun.tools.attach=ALL-UNNAMED
	--add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing.plaf.synth=ALL-UNNAMED
	--add-opens=java.base/java.net=ALL-UNNAMED
	--add-opens=java.base/java.lang.ref=ALL-UNNAMED
	--add-opens=java.base/java.lang=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
	-XX:+IgnoreUnrecognizedVMOptions
	-Djdk.home=C:\Program Files\Java\jdk-11
	-Dnetbeans.home=C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\platform
	-Dnetbeans.user=C:\Users\gaurav8.jain\AppData\Roaming\VisualVM\2.1.7
	-Dnetbeans.default_userdir_root=C:\Users\gaurav8.jain\AppData\Roaming\VisualVM
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\gaurav8.jain\AppData\Roaming\VisualVM\2.1.7\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Djava.security.manager=allow
	-Dnetbeans.dirs=C:\Users\gaurav8.jain\OneDrive - Reliance Corporate IT Park Limited\Desktop\PortableApps\visualvm_217\visualvm
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 24.0MB maximum 768.0MB
Non heap memory usage: initial 7.3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=28 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=7855 total loaded=7855 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 8,121,290,752
INFO [null]: Total physical memory 8,121,290,752
WARNING [org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator]: Error when executing PAC script function FindProxyForURL : 
java.util.regex.PatternSyntaxException: Illegal repetition near index 9
^https://${asg_hostname}.*?$
         ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2213)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at org.netbeans.core.network.proxy.pac.PacUtils.createRegexPatternFromGlob(PacUtils.java:115)
	at org.netbeans.core.network.proxy.pac.impl.NbPacHelperMethods.shExpMatch(NbPacHelperMethods.java:161)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$13$751AA$\^eval\_.L:1#L:34(<eval>:35)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$12$\^eval\_.:scopeCall(<eval>)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$12$\^eval\_.FindProxyForURL(<eval>:3)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:659)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197)
	at org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator$PacScriptEngine.findProxyForURL(NbPacScriptEvaluator.java:551)
[catch] at org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator.findProxyForURL(NbPacScriptEvaluator.java:223)
	at org.netbeans.core.network.proxy.ProxyAutoConfig.findProxyForURL(ProxyAutoConfig.java:145)
	at org.netbeans.core.network.proxy.NbProxySelector.select(NbProxySelector.java:167)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task.checkRedirect(NetworkAccess.java:180)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task.access$800(NetworkAccess.java:60)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:148)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
WARNING [org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator]: Error when executing PAC script function FindProxyForURL : 
java.util.regex.PatternSyntaxException: Illegal repetition near index 9
^https://${asg_hostname}.*?$
         ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2213)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at org.netbeans.core.network.proxy.pac.PacUtils.createRegexPatternFromGlob(PacUtils.java:115)
	at org.netbeans.core.network.proxy.pac.impl.NbPacHelperMethods.shExpMatch(NbPacHelperMethods.java:161)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$13$751AA$\^eval\_.L:1#L:34(<eval>:35)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$12$\^eval\_.:scopeCall(<eval>)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$12$\^eval\_.FindProxyForURL(<eval>:3)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:659)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197)
	at org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator$PacScriptEngine.findProxyForURL(NbPacScriptEvaluator.java:551)
[catch] at org.netbeans.core.network.proxy.pac.impl.NbPacScriptEvaluator.findProxyForURL(NbPacScriptEvaluator.java:223)
	at org.netbeans.core.network.proxy.ProxyAutoConfig.findProxyForURL(ProxyAutoConfig.java:145)
	at org.netbeans.core.network.proxy.NbProxySelector.select(NbProxySelector.java:167)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:302)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:510)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:605)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task.checkRedirect(NetworkAccess.java:180)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task.access$800(NetworkAccess.java:60)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:148)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
INFO [org.netbeans.modules.autoupdate.updateprovider.DownloadListener]: Reading URL https://visualvm.github.io/uc/release217/updates.xml.gz?unique=04e8c073d-ba54-4034-8d38-47cd64b280af_100f7a38-b09f-429a-aeb2-7e81c60e8537 failed (java.net.SocketException: Connection reset)
INFO [org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler]
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1296)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:388)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:576)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task.checkRedirect(NetworkAccess.java:180)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task.access$800(NetworkAccess.java:60)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:148)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused: java.io.IOException: Connection reset
	at org.netbeans.modules.autoupdate.updateprovider.DownloadListener.notifyException(DownloadListener.java:78)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.copy(AutoupdateCatalogCache.java:221)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.writeCatalogToCache(AutoupdateCatalogCache.java:74)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogProvider.refresh(AutoupdateCatalogProvider.java:134)
	at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.refresh(UpdateUnitProviderImpl.java:165)
	at org.netbeans.api.autoupdate.UpdateUnitProvider.refresh(UpdateUnitProvider.java:171)
[catch] at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler$4.run(AutoupdateCheckScheduler.java:130)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by thurka** [comment]
Thanks for the log. It looks like there is a problem with PAC file used for proxy. To workaround it, you can set proxy manually in Network preferences. However this problem does not seem to affect the JMX connection. Are you sure that you have correct setup for ssh tunnel? Tunneling JMX connection ivia SSH s not straightforward.
