### ISSUE TITLE
StackOverflowError when starting

### ISSUE THREAD

**Issue by guenhter** [oracle/visualvm#583]
**Describe the bug**
After installing visualvm on ubuntu 24.04, running it caused a StackOverflowError

**To Reproduce**
1. Install VisualVM via `sudo apt install visualvm`
2. run `visualvm`

**Expected behavior**
VisualVM starts up.

**VisualVM log**

```
> visualvm
Error occurred during initialization of VM
java.lang.StackOverflowError
        at java.security.BasicPermission.init(java.base@11.0.23/BasicPermission.java:107)
        at java.security.BasicPermission.<init>(java.base@11.0.23/BasicPermission.java:130)
        at java.lang.RuntimePermission.<init>(java.base@11.0.23/RuntimePermission.java:420)
        at java.lang.System.setSecurityManager0(java.base@11.0.23/System.java:342)
        at java.lang.System.setSecurityManager(java.base@11.0.23/System.java:333)
        at allow.uninstall(Unknown Source)
        at allow.checkPermission(Unknown Source)
        at java.lang.System.setSecurityManager0(java.base@11.0.23/System.java:342)
        at java.lang.System.setSecurityManager(java.base@11.0.23/System.java:333)
        at allow.uninstall(Unknown Source)
        at allow.checkPermission(Unknown Source)
        at java.lang.System.setSecurityManager0(java.base@11.0.23/System.java:342)
        at java.lang.System.setSecurityManager(java.base@11.0.23/System.java:333)
        at allow.uninstall(Unknown Source)
        at allow.checkPermission(Unknown Source)
        at java.lang.System.setSecurityManager0(java.base@11.0.23/System.java:342)
        at java.lang.System.setSecurityManager(java.base@11.0.23/System.java:333)
        at allow.uninstall(Unknown Source)
        at allow.checkPermission(Unknown Source)
        at java.lang.System.setSecurityManager0(java.base@11.0.23/System.java:342)
        at java.lang.System.setSecurityManager(java.base@11.0.23/System.java:333)
        at allow.uninstall(Unknown Source)
        at allow.checkPermission(Unknown Source)
        at java.lang.System.setSecurityManager0(java.base@11.0.23/System.java:342)
        at java.lang.System.setSecurityManager(java.base@11.0.23/System.java:333)
        at allow.uninstall(Unknown Source)
        ...
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - JDK version openjdk 11.0.23 2024-04-16
 - Version visualvm/noble,now 2.1.8-1

**Comment by guenhter** [comment]
Very interesting. This works. Thx.

**Comment by thurka** [comment]
I am glad it worked. I guess that you should be able to report this issue to ubuntu.

**Comment by mexchip** [comment]
it works if you use JDK 17, the same happens with Apache Netbeans: https://www.mexchip.com/en/2024/10/netbeans-23-does-not-start-on-kubuntu-24-04/

**Comment by vboerner-transporeon** [comment]
I had different JDK versions installed (ubuntu2404): 11, 17 and 21. After `sudo apt remove "openjdk-11-j*"`  visualvm started again.

**Comment by root-intruder** [comment]
@

> I had different JDK versions installed (ubuntu2404): 11, 17 and 21. After `sudo apt remove "openjdk-11-j*"` visualvm started again.

worked for me, thanks! Interestingly, i had set java 21 via update-alternatives, which visualvm seems to completely disregard
