### ISSUE TITLE
visualvm 2.1.9 ,win11, the application is freeze

### ISSUE THREAD

**Issue by tianqiqiu** [oracle/visualvm#594]
When i click menu -> window -> applications. visualvm is freeze, not any response. the logs is:
WARNING [org.openide.awt.Toolbar]: Error in AWT task
java.lang.InternalError: Remote thread failed for unknown reason (101)
at jdk.attach/sun.tools.attach.VirtualMachineImpl.enqueue(Native Method)
at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:107)
at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:310)
at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.getSystemProperties(HotSpotVirtualMachine.java:191)
at org.graalvm.visualvm.attach.AttachModelImpl.getSystemProperties(AttachModelImpl.java:65)
at org.graalvm.visualvm.jvm.JVMImpl.getSystemProperties(JVMImpl.java:336)
at org.graalvm.visualvm.profiler.ProfilerSupport.getJVMArchitecture(ProfilerSupport.java:392)
at org.graalvm.visualvm.profiler.ProfilerSupport.supportsProfiling(ProfilerSupport.java:313)
at org.graalvm.visualvm.profiler.ProfileApplicationAction.isEnabled(ProfileApplicationAction.java:70)
at org.graalvm.visualvm.profiler.ProfileApplicationAction.isEnabled(ProfileApplicationAction.java:42)
at org.graalvm.visualvm.core.ui.actions.SingleDataSourceAction.updateState(SingleDataSourceAction.java:77)
at org.graalvm.visualvm.profiler.ProfileApplicationAction.updateState(ProfileApplicationAction.java:78)
at org.graalvm.visualvm.core.ui.actions.DataSourceAction.initialize(DataSourceAction.java:92)
at org.graalvm.visualvm.profiler.ProfileApplicationAction.initialize(ProfileApplicationAction.java:83)
at org.graalvm.visualvm.core.ui.actions.DataSourceAction.doInitialize(DataSourceAction.java:124)
at org.graalvm.visualvm.core.ui.actions.DataSourceAction.isEnabled(DataSourceAction.java:101)
at org.openide.awt.Actions$MenuBridge.updateState(Actions.java:1387)
at org.openide.awt.Actions$Bridge.prepare(Actions.java:1029)
at org.openide.awt.Actions$MenuBridge.prepare(Actions.java:1374)
at org.openide.awt.Actions.connect(Actions.java:273)
at org.openide.awt.Actions$MenuItem.(Actions.java:1733)
at org.openide.awt.DynaMenuModel.loadSubmenu(DynaMenuModel.java:113)
at org.openide.awt.MenuBar$LazyMenu$MenuFolder.createInstance(MenuBar.java:854)
at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:863)
at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:705)
at org.openide.util.Task.run(Task.java:233)
[catch] at org.netbeans.modules.openide.loaders.AWTTask.run(AWTTask.java:54)
at org.netbeans.modules.openide.loaders.AWTTask$Processor.run(AWTTask.java:147)
at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.lambda$doEvent$0(NbMutexEventProvider.java:101)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
SEVERE [global]
java.lang.InternalError: Remote thread failed for unknown reason (101)
at jdk.attach/sun.tools.attach.VirtualMachineImpl.enqueue(Native Method)
at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:107)
at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:310)
at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.executeJCmd(HotSpotVirtualMachine.java:292)
at org.graalvm.visualvm.attach.AttachModelImpl.executeJCmd(AttachModelImpl.java:213)
at org.graalvm.visualvm.attach.AttachModelImpl.executeJCmd(AttachModelImpl.java:182)
at org.graalvm.visualvm.jfr.model.impl.JfrModelImpl.executeJCmd(JfrModelImpl.java:216)
at org.graalvm.visualvm.jfr.model.impl.JfrModelImpl.isJfrAvailable(JfrModelImpl.java:86)
at org.graalvm.visualvm.jfr.model.impl.JfrModelProvider.createModelFor(JfrModelProvider.java:43)
at org.graalvm.visualvm.jfr.model.impl.JfrModelProvider.createModelFor(JfrModelProvider.java:39)
at org.graalvm.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:105)
at org.graalvm.visualvm.tools.jfr.JfrModelFactory.getJFRFor(JfrModelFactory.java:64)
at org.graalvm.visualvm.jvm.JVMImpl.isJfrAvailable(JVMImpl.java:495)
at org.graalvm.visualvm.jfr.JFRSnapshotSupport.supportsJfrStart(JFRSnapshotSupport.java:169)
at org.graalvm.visualvm.jfr.impl.JFRStartAction.isEnabled(JFRStartAction.java:95)
at org.graalvm.visualvm.core.ui.actions.MultiDataSourceAction.updateState(MultiDataSourceAction.java:76)
at org.graalvm.visualvm.jfr.impl.JFRStartAction.updateState(JFRStartAction.java:117)
at org.graalvm.visualvm.core.ui.actions.DataSourceAction.initialize(DataSourceAction.java:92)
at org.graalvm.visualvm.core.ui.actions.DataSourceAction.doInitialize(DataSourceAction.java:124)
at org.graalvm.visualvm.core.ui.actions.DataSourceAction.isEnabled(DataSourceAction.java:101)
at org.graalvm.visualvm.core.explorer.ExplorerContextMenuFactory.getActions(ExplorerContextMenuFactory.java:172)
at org.graalvm.visualvm.core.explorer.ExplorerContextMenuFactory.getSelectionActions(ExplorerContextMenuFactory.java:128)
at org.graalvm.visualvm.core.explorer.ExplorerContextMenuFactory.getActions(ExplorerContextMenuFactory.java:122)
at org.graalvm.visualvm.core.explorer.ExplorerContextMenuFactory.createPopupMenu(ExplorerContextMenuFactory.java:74)
at org.graalvm.visualvm.core.explorer.ExplorerComponent.displayContextMenu(ExplorerComponent.java:204)
at org.graalvm.visualvm.core.explorer.ExplorerComponent.access$800(ExplorerComponent.java:68)
at org.graalvm.visualvm.core.explorer.ExplorerComponent$ExplorerTreeMouseAdapter.mouseReleased(ExplorerComponent.java:253)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
at org.graalvm.visualvm.core.explorer.ExplorerComponent$1.processMouseEvent(ExplorerComponent.java:110)
at java.desktop/java.awt.Component.processEvent(Component.java:6391)
at java.desktop/java.awt.Container.processEvent(Container.java:2266)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by thurka** [comment]
Attach complete VisualVM log, not just part of it. Thanks.
