### ISSUE TITLE
Null pointer opening heapdump

### ISSUE THREAD

**Issue by furyscript** [oracle/visualvm#608]
**Describe the bug**
Error opening heapdump.
Java openjdk 21.
Attached dump and log

**To Reproduce**
Download dump: [here](https://drive.google.com/file/d/1Qm_I6c0yc9wkTUQDS-Dm0ghhqSWV3Q_i/view?usp=drive_link)

**VisualVM log**
```
java.lang.NullPointerException: Cannot invoke "org.graalvm.visualvm.lib.jfluid.heap.ObjectArrayDump.getValues()" because "entriesObj" is null
	at org.graalvm.visualvm.lib.jfluid.heap.HprofProxy.getPropertiesFromTable(HprofProxy.java:71)
	at org.graalvm.visualvm.lib.jfluid.heap.HprofProxy.getProperties(HprofProxy.java:59)
	at org.graalvm.visualvm.lib.jfluid.heap.HprofHeap.getSystemProperties(HprofHeap.java:298)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaOverviewSummary.<init>(JavaOverviewSummary.java:140)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaOverviewSummary.<init>(JavaOverviewSummary.java:124)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaOverviewSummary$Provider.createSummary(JavaOverviewSummary.java:762)
	at org.graalvm.visualvm.heapviewer.ui.SummaryView.<init>(SummaryView.java:76)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaSummaryView.<init>(JavaSummaryView.java:56)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaSummaryProvider.getFeature(JavaSummaryProvider.java:43)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent.initImpl(HeapViewerComponent.java:142)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent.access$000(HeapViewerComponent.java:76)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent$1.run(HeapViewerComponent.java:95)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)

```

**Desktop (please complete the following information):**
 - OS: All versions (linux, windows)
 - JDK version [JDK 21]
 - Version [e.g. 2.0]

**Additional context**

**Comment by thurka** [comment]
Unfortunately the heap dump is not available:
```
Error: Quick Share could not be found. Do not close the browser window before the transfer is complete.
```

**Comment by furyscript** [comment]
Sorry, reuploaded here: [here](https://drive.google.com/file/d/1Qm_I6c0yc9wkTUQDS-Dm0ghhqSWV3Q_i/view?usp=drive_link)

**Comment by thurka** [comment]
Thanks, I am able to reproduce the issue.

**Comment by thurka** [comment]
Fixed in master.

**Comment by furyscript** [comment]
Can you create a new version? Or when it release new executable version?

**Comment by thurka** [comment]
If you need VisualVM with the fix, you can build it yourself.
