### ISSUE TITLE
VisualVM hang if there is a deadlocked Java VM

### ISSUE THREAD

**Issue by Horcrux7** [oracle/visualvm#64]
I want to try to create a thread dump of a deadlocked 64 bit VM on Windows. If I start VisualVM with standard settings (32 bit) I can see the process but can't create a thread dump.

If I try to start it with a 64 bit VM with the command line switch `--jdkhome` then VisualVM seeam to hang. In the status bar you can see "Computing description" and a pending status meter.

Here is the thread dump of VisualVM 1.4 with JDK 9. I have the same effect with a JDK 8

```
2018-02-16 10:23:17
Full thread dump Java HotSpot(TM) 64-Bit Server VM (9+175 mixed mode):

"Default RequestProcessor" - Thread t@47
   java.lang.Thread.State: RUNNABLE
        at java.management@9/sun.management.ThreadImpl.dumpThreads0(Native Method)
        at java.management@9/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:479)
        at java.base@9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@9/java.lang.reflect.Method.invoke(Method.java:564)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
        at java.base@9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@9/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base@9/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
        at java.management@9/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
        at java.management@9/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
        at java.management@9/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
        at java.management@9/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
        at java.management@9/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at java.management@9/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at java.management@9/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at java.management@9/javax.management.StandardMBean.invoke(StandardMBean.java:405)
        at java.management@9/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
        at java.management@9/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at java.management@9/com.sun.jmx.mbeanserver.MXBeanProxy$InvokeHandler.invoke(MXBeanProxy.java:150)
        at java.management@9/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
        at java.management@9/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
        at com.sun.proxy.$Proxy15.dumpAllThreads(Unknown Source)
        at com.sun.tools.visualvm.jmx.impl.JmxSupport.takeThreadDump(JmxSupport.java:202)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl.takeThreadDump(JmxModelImpl.java:343)
        at com.sun.tools.visualvm.jvm.JVMImpl.takeThreadDump(JVMImpl.java:418)
        at com.sun.tools.visualvm.threaddump.impl.ThreadDumpProvider$1.run(ThreadDumpProvider.java:83)
        at app//org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
        at app//org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
        at app//org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
        at app//org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

   Locked ownable synchronizers:
        - None

"Image Fetcher 0" - Thread t@46
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <73c52ef1> (a java.util.Vector)
        at java.desktop@9/sun.awt.image.ImageFetcher.nextImage(ImageFetcher.java:154)
        at java.desktop@9/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:207)
        at java.desktop@9/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)

   Locked ownable synchronizers:
        - None

"Inactive RequestProcessor thread [Was:Default RequestProcessor/com.sun.tools.visualvm.tools.jmx.CachedMBeanServerConnectionFactory$SnapshotInvocationHandler$2]" - Thread t@45
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <30264667> (a java.lang.Object)
        at app//org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2002)

   Locked ownable synchronizers:
        - None

"pool-5-thread-1" - Thread t@43
   java.lang.Thread.State: WAITING
        at java.base@9/jdk.internal.misc.Unsafe.park(Native Method)
        - parking to wait for <5b32aa5c> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.base@9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2062)
        at java.base@9/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base@9/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
        at java.base@9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.base@9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - None

"Timer-0" - Thread t@42
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <3b788ce3> (a java.util.TaskQueue)
        at java.base@9/java.util.TimerThread.mainLoop(Timer.java:553)
        at java.base@9/java.util.TimerThread.run(Timer.java:506)

   Locked ownable synchronizers:
        - None

"pool-3-thread-1" - Thread t@41
   java.lang.Thread.State: WAITING
        at java.base@9/jdk.internal.misc.Unsafe.park(Native Method)
        - parking to wait for <379b2629> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.base@9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2062)
        at java.base@9/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base@9/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
        at java.base@9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.base@9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - None

"DestroyJavaVM" - Thread t@30
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"TimerQueue" - Thread t@29
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/jdk.internal.misc.Unsafe.park(Native Method)
        - parking to wait for <6d73248d> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.base@9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2104)
        at java.base@9/java.util.concurrent.DelayQueue.take(DelayQueue.java:229)
        at java.desktop@9/javax.swing.TimerQueue.run(TimerQueue.java:171)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - locked <8825bd7> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"Event Dispatch Thread" - Thread t@28
   java.lang.Thread.State: WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <6f64523a> (a java.util.LinkedList)
        at java.base@9/java.lang.Object.wait(Object.java:516)
        at java.prefs@9/java.util.prefs.AbstractPreferences$EventDispatchThread.run(AbstractPreferences.java:1529)

   Locked ownable synchronizers:
        - None

"File Watcher" - Thread t@27
   java.lang.Thread.State: WAITING
        at java.base@9/jdk.internal.misc.Unsafe.park(Native Method)
        - parking to wait for <21ca65c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.base@9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2062)
        at java.base@9/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at org.netbeans.modules.masterfs.watcher.windows.WindowsNotifier.nextEvent(WindowsNotifier.java:285)
        at org.netbeans.modules.masterfs.providers.Notifier$1.nextEvent(Notifier.java:122)
        at org.netbeans.modules.masterfs.watcher.Watcher$Ext.run(Watcher.java:345)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - None

"Inactive RequestProcessor thread [Was:ThreadsWorker/com.sun.tools.visualvm.application.views.threads.ApplicationThreadsView$MasterViewSupport$3]" - Thread t@25
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <7a9db7ac> (a java.lang.Object)
        at app//org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2002)

   Locked ownable synchronizers:
        - None

"Explorer Builder Processor" - Thread t@24
   java.lang.Thread.State: RUNNABLE
        at app/jdk.attach@9/sun.tools.attach.VirtualMachineImpl.connectPipe(Native Method)
        at app/jdk.attach@9/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:100)
        at app/jdk.attach@9/sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:296)
        at app/jdk.attach@9/sun.tools.attach.HotSpotVirtualMachine.executeJCmd(HotSpotVirtualMachine.java:278)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$LocalVirtualMachine.loadManagementAgentViaJcmd(JmxModelImpl.java:802)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$LocalVirtualMachine.loadManagementAgent(JmxModelImpl.java:756)
        - locked <2e6951a4> (a com.sun.tools.visualvm.jmx.impl.JmxModelImpl$LocalVirtualMachine)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$LocalVirtualMachine.startManagementAgent(JmxModelImpl.java:732)
        - locked <2e6951a4> (a com.sun.tools.visualvm.jmx.impl.JmxModelImpl$LocalVirtualMachine)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$ProxyClient.tryConnect(JmxModelImpl.java:540)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$ProxyClient.connect(JmxModelImpl.java:507)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl.connect(JmxModelImpl.java:235)
        at com.sun.tools.visualvm.jmx.impl.JmxModelImpl.<init>(JmxModelImpl.java:205)
        at com.sun.tools.visualvm.jmx.impl.JmxModelProvider.createModelFor(JmxModelProvider.java:64)
        at com.sun.tools.visualvm.jmx.impl.JmxModelProvider.createModelFor(JmxModelProvider.java:41)
        at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
        - locked <68328cd2> (a com.sun.tools.visualvm.jvmstat.application.JvmstatApplication)
        at com.sun.tools.visualvm.tools.jmx.JmxModelFactory.getJmxModelFor(JmxModelFactory.java:69)
        at com.sun.tools.visualvm.jvm.JmxSupport.getJvmMXBeans(JmxSupport.java:157)
        - locked <46ebf48e> (a com.sun.tools.visualvm.jvm.JmxSupport)
        at com.sun.tools.visualvm.jvm.JmxSupport.getRuntime(JmxSupport.java:90)
        at com.sun.tools.visualvm.jvm.JmxSupport.getJvmArgs(JmxSupport.java:177)
        at com.sun.tools.visualvm.jvm.JVMImpl.getJvmArgsJvmstat(JVMImpl.java:529)
        at com.sun.tools.visualvm.jvm.JVMImpl.initStaticData(JVMImpl.java:500)
        - locked <10e3f89c> (a java.lang.Object)
        at com.sun.tools.visualvm.jvm.JVMImpl.getMainClass(JVMImpl.java:139)
        at com.sun.tools.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:148)
        at com.sun.tools.visualvm.application.type.MainClassApplicationTypeFactory.createModelFor(MainClassApplicationTypeFactory.java:42)
        at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
        - locked <68328cd2> (a com.sun.tools.visualvm.jvmstat.application.JvmstatApplication)
        at com.sun.tools.visualvm.application.type.ApplicationTypeFactory.getApplicationTypeFor(ApplicationTypeFactory.java:74)
        at com.sun.tools.visualvm.application.ApplicationDescriptor.<init>(ApplicationDescriptor.java:55)
        at com.sun.tools.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:43)
        at com.sun.tools.visualvm.application.ApplicationDescriptorProvider.createModelFor(ApplicationDescriptorProvider.java:38)
        at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
        - locked <68328cd2> (a com.sun.tools.visualvm.jvmstat.application.JvmstatApplication)
        at com.sun.tools.visualvm.core.datasource.descriptor.DataSourceDescriptorFactory.getDescriptor(DataSourceDescriptorFactory.java:69)
        at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.processAddedDisplayableDataSources(ExplorerModelBuilder.java:152)
        at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.processIndependentAddedDataSources(ExplorerModelBuilder.java:116)
        at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.processAddedDataSources(ExplorerModelBuilder.java:105)
        at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder.access$200(ExplorerModelBuilder.java:59)
        at com.sun.tools.visualvm.core.explorer.ExplorerModelBuilder$1.run(ExplorerModelBuilder.java:98)
        at app//org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
        at app//org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
        at app//org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
        at app//org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

   Locked ownable synchronizers:
        - None

"AWT-EventQueue-0" - Thread t@23
   java.lang.Thread.State: RUNNABLE
        at java.desktop@9/com.sun.java.swing.plaf.windows.WindowsGraphicsUtils.paintXPText(WindowsGraphicsUtils.java:139)
        at java.desktop@9/com.sun.java.swing.plaf.windows.WindowsGraphicsUtils.paintText(WindowsGraphicsUtils.java:69)
        at java.desktop@9/com.sun.java.swing.plaf.windows.WindowsButtonUI.paintText(WindowsButtonUI.java:121)
        at java.desktop@9/javax.swing.plaf.basic.BasicButtonUI.paint(BasicButtonUI.java:283)
        at java.desktop@9/com.sun.java.swing.plaf.windows.WindowsButtonUI.paint(WindowsButtonUI.java:167)
        at java.desktop@9/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
        at java.desktop@9/javax.swing.JComponent.paintComponent(JComponent.java:798)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1075)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at org.netbeans.swing.tabcontrol.TabbedContainer.paint(TabbedContainer.java:994)
        at java.desktop@9/javax.swing.JComponent.paintChildren(JComponent.java:908)
        - locked <aa555b4> (a java.awt.Component$AWTTreeLock)
        at java.desktop@9/javax.swing.JComponent.paint(JComponent.java:1084)
        at java.desktop@9/javax.swing.JComponent.paintToOffscreen(JComponent.java:5256)
        at java.desktop@9/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1697)
        at java.desktop@9/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1606)
        at java.desktop@9/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1546)
        at java.desktop@9/javax.swing.RepaintManager.paint(RepaintManager.java:1313)
        at java.desktop@9/javax.swing.JComponent._paintImmediately(JComponent.java:5204)
        at java.desktop@9/javax.swing.JComponent.paintImmediately(JComponent.java:5014)
        at java.desktop@9/javax.swing.JComponent.paintImmediately(JComponent.java:4995)
        at java.desktop@9/javax.swing.RepaintManager$4.run(RepaintManager.java:857)
        at java.desktop@9/javax.swing.RepaintManager$4.run(RepaintManager.java:840)
        at java.base@9/java.security.AccessController.doPrivileged(Native Method)
        at java.base@9/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
        at java.desktop@9/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:840)
        at java.desktop@9/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:815)
        at java.desktop@9/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:764)
        at java.desktop@9/javax.swing.RepaintManager.access$1200(RepaintManager.java:69)
        at java.desktop@9/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1880)
        at java.desktop@9/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop@9/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.desktop@9/java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.desktop@9/java.awt.EventQueue$3.run(EventQueue.java:717)
        at java.desktop@9/java.awt.EventQueue$3.run(EventQueue.java:711)
        at java.base@9/java.security.AccessController.doPrivileged(Native Method)
        at java.base@9/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
        at java.desktop@9/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at java.desktop@9/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
        at java.desktop@9/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop@9/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop@9/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop@9/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop@9/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

   Locked ownable synchronizers:
        - None

"AWT-Windows" - Thread t@21
   java.lang.Thread.State: RUNNABLE
        at java.desktop@9/sun.awt.windows.WToolkit.eventLoop(Native Method)
        at java.desktop@9/sun.awt.windows.WToolkit.run(WToolkit.java:297)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - None

"AWT-Shutdown" - Thread t@20
   java.lang.Thread.State: WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <4f0ea5be> (a java.lang.Object)
        at java.base@9/java.lang.Object.wait(Object.java:516)
        at java.desktop@9/sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:291)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - None

"Java2D Disposer" - Thread t@19
   java.lang.Thread.State: WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <3b2db79e> (a java.lang.ref.ReferenceQueue$Lock)
        at java.base@9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
        at java.base@9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:172)
        at java.desktop@9/sun.java2d.Disposer.run(Disposer.java:144)
        at java.base@9/java.lang.Thread.run(Thread.java:844)

   Locked ownable synchronizers:
        - None

"RequestProcessor queue manager" - Thread t@18
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <43ff2a4b> (a java.lang.Class)
        at app//org.openide.util.RequestProcessor$TickTac.obtainFirst(RequestProcessor.java:2282)
        at app//org.openide.util.RequestProcessor$TickTac.run(RequestProcessor.java:2258)

   Locked ownable synchronizers:
        - None

"CLI Requests Server" - Thread t@15
   java.lang.Thread.State: RUNNABLE
        at java.base@9/java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.base@9/java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
        at java.base@9/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:459)
        at java.base@9/java.net.PlainSocketImpl.accept(PlainSocketImpl.java:183)
        - locked <6ea5d135> (a java.net.SocksSocketImpl)
        at java.base@9/java.net.ServerSocket.implAccept(ServerSocket.java:551)
        at java.base@9/java.net.ServerSocket.accept(ServerSocket.java:519)
        at app//org.netbeans.CLIHandler$Server.run(CLIHandler.java:1103)

   Locked ownable synchronizers:
        - None

"Active Reference Queue Daemon" - Thread t@14
   java.lang.Thread.State: WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <7615c743> (a java.lang.ref.ReferenceQueue$Lock)
        at java.base@9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
        at app//org.openide.util.lookup.implspi.ActiveQueue$Impl.removeSuper(ActiveQueue.java:93)
        at app//org.openide.util.lookup.implspi.ActiveQueue$Daemon.run(ActiveQueue.java:131)

   Locked ownable synchronizers:
        - None

"Common-Cleaner" - Thread t@10
   java.lang.Thread.State: TIMED_WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <4835824> (a java.lang.ref.ReferenceQueue$Lock)
        at java.base@9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
        at java.base@9/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
        at java.base@9/java.lang.Thread.run(Thread.java:844)
        at java.base@9/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:122)

   Locked ownable synchronizers:
        - None

"Attach Listener" - Thread t@5
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" - Thread t@4
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Finalizer" - Thread t@3
   java.lang.Thread.State: WAITING
        at java.base@9/java.lang.Object.wait(Native Method)
        - waiting on <3e9a3e5f> (a java.lang.ref.ReferenceQueue$Lock)
        at java.base@9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
        at java.base@9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:172)
        at java.base@9/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

   Locked ownable synchronizers:
        - None

"Reference Handler" - Thread t@2
   java.lang.Thread.State: RUNNABLE
        at java.base@9/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
        at java.base@9/java.lang.ref.Reference.processPendingReferences(Reference.java:174)
        at java.base@9/java.lang.ref.Reference.access$000(Reference.java:44)
        at java.base@9/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:138)

   Locked ownable synchronizers:
        - None
```

**Comment by Horcrux7** [comment]
Ok, the problem occur only if there is a dead lock in another Java VM.

**Comment by thurka** [comment]
Not all deadlocks in monitored JVM can cause this problem. Can you, please, provide steps to reproduce? Thanks.

**Comment by Horcrux7** [comment]
- It was occurred in a JNLP application. 
- A background thread in an unsigned jar files has call InetAddress.getLocalHost() in static init code (class loading)
- This popup a security message box.
- But the AWT event thread was blocked through the class loading. It wait self on the class which has popup the security message.

I think the cause was a deadlock in class loading. If the connect from VisualVM needs to load some class then it will also block. But this is only a theory. Possible can be also a lock in the network stack.

**Comment by thurka** [comment]
Deadlock, which prevent class loading, can cause this problem, especially if the deadlock happen before you open monitored application in VisualVM.

**Comment by thurka** [comment]
Closing, I don't see how this can be fixed in VisualVM.

**Comment by Horcrux7** [comment]
With a timeout can this be fixed in VisualVM. After the timeout it show an error message. This should be a very simple fix. A program that must be killed via task manager is very bad.
