### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by barrouh** [oracle/visualvm#65]
Hi , 
I get this error when i try to open file (size 1.25 GB ) , 
Can you please advise me what i can do ?
Thanks

**Comment by jisedlac** [comment]
Please attach the VisualVM logfile after the OOME has been thrown (Help | About | Logfile).

As a quick fix, you can increase the heap size for VisualVM: `visualvm.exe -J-Xmx1024M` or by editing `etc\visualvm.conf`.

**Comment by barrouh** [comment]
Thank you for replying ,

Attached the log file : [messages.log](https://github.com/oracle/visualvm/files/1737152/messages.log)

`java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.netbeans.core.startup.logging.PrintStreamLogger.print(PrintStreamLogger.java:152)
	at org.netbeans.core.startup.logging.PrintStreamLogger.println(PrintStreamLogger.java:159)
	at org.netbeans.core.startup.logging.PrintStreamLogger.println(PrintStreamLogger.java:166)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:658)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at org.netbeans.lib.profiler.heap.AbstractLongMap$FileData.loadBufferIfNeeded(AbstractLongMap.java:346)
	at org.netbeans.lib.profiler.heap.AbstractLongMap$FileData.getLong(AbstractLongMap.java:297)
	at org.netbeans.lib.profiler.heap.AbstractLongMap.getID(AbstractLongMap.java:171)
	at org.netbeans.lib.profiler.heap.AbstractLongMap.put(AbstractLongMap.java:137)
	at org.netbeans.lib.profiler.heap.LongMap.put(LongMap.java:285)
	at org.netbeans.lib.profiler.heap.ClassDumpSegment.createClassCollection(ClassDumpSegment.java:245)
	at org.netbeans.lib.profiler.heap.HprofHeap.getAllClasses(HprofHeap.java:188)
	at org.netbeans.lib.profiler.heap.ComputedSummary.<init>(ComputedSummary.java:65)
	at org.netbeans.lib.profiler.heap.HprofHeap.getSummary(HprofHeap.java:292)
	at com.sun.tools.visualvm.heapviewer.HeapViewer.createHeap(HeapViewer.java:106)
	at com.sun.tools.visualvm.heapviewer.HeapViewer.<init>(HeapViewer.java:68)
	at com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1.run(HeapDumpView.java:137)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
`
the same thing after try visualvm.exe -J-Xmx1024M , 
Thanks ,

**Comment by thurka** [comment]
You are running VisualVM on 32bit JDK. If your Windows is 64bit, please try to run VisualVM on 64bit JDK. Use `visualvm.exe --jdkhome <path_to_64bit_JDK>`. This should allow you to open your heap dump.

**Comment by barrouh** [comment]
thurka thank you very much i resolved the problem ,
any idea what the reason of  Caused by: java.lang.OutOfMemoryError: PermGen space error ,

**Comment by blandger** [comment]
> java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

[messages.log](https://github.com/oracle/visualvm/files/1867982/messages.log)

**Comment by thurka** [comment]
The exception `java.io.IOException: Stream Closed` mentioned in messages.log file should be fixed in VisualVM 1.4.1.
