### ISSUE TITLE
NullPointerException at org.netbeans.lib.profiler.heap.HprofHeap.computeReferences()

### ISSUE THREAD

**Issue by AnEmortalKid** [oracle/visualvm#75]
I've tried to load up the Dominators view from the Objects tab and noticed that the Compute Retained Sizes was getting stuck forever.

```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapviewer.model.DataType$RetainedSize$1
java.lang.NullPointerException
	at org.netbeans.lib.profiler.heap.HprofHeap.computeReferences(HprofHeap.java:639)
	at org.netbeans.lib.profiler.heap.NearestGCRoot.computeGCRoots(NearestGCRoot.java:123)
	at org.netbeans.lib.profiler.heap.NearestGCRoot.getLeaves(NearestGCRoot.java:397)
	at org.netbeans.lib.profiler.heap.HprofHeap.computeRetainedSize(HprofHeap.java:713)
	at org.netbeans.lib.profiler.heap.HprofHeap.computeRetainedSizeByClass(HprofHeap.java:776)
	at org.netbeans.lib.profiler.heap.ClassDump.getRetainedSizeByClass(ClassDump.java:147)
	at com.sun.tools.visualvm.heapviewer.model.DataType$RetainedSize$1.run(DataType.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

I have a couple of logs from when this happened. I'll attach them here. 

[messages_old.log](https://github.com/oracle/visualvm/files/1892081/messages_old.log)
[messages.log](https://github.com/oracle/visualvm/files/1892077/messages.log)

I'll see if I can allot some time to look into this issue closer and provide a P/R :)

**Comment by thurka** [comment]
Same problem is also reported in GH-4 and [NetBeans issue #254842](https://netbeans.org/bugzilla/show_bug.cgi?id=254842). This looks like broken heapdump, but it would be great if you can share (privately) the heapdump with us, so we can find out what is wrong. Thanks.

**Comment by AnEmortalKid** [comment]
@thurka I'll get back to you on that. I'll probably have to talk to my boss about it due to the nature of the data within it. It might be a huge ordeal...

**Comment by AnEmortalKid** [comment]
I've started debugging through this in netbeans and it gave me a bit more info:
```
java.lang.NullPointerException
	at org.netbeans.lib.profiler.heap.HprofHeap.computeReferences(HprofHeap.java:615)
	at org.netbeans.lib.profiler.heap.NearestGCRoot.computeGCRoots(NearestGCRoot.java:99)
	at org.netbeans.lib.profiler.heap.NearestGCRoot.getLeaves(NearestGCRoot.java:373)
	at org.netbeans.lib.profiler.heap.HprofHeap.computeRetainedSize(HprofHeap.java:689)
	at org.netbeans.lib.profiler.heap.HprofHeap.computeRetainedSizeByClass(HprofHeap.java:752)
	at org.netbeans.lib.profiler.heap.ClassDump.getRetainedSizeByClass(ClassDump.java:123)
	at com.sun.tools.visualvm.heapviewer.model.DataType$RetainedSize.computeValuesImmediately(DataType.java:214)
	at com.sun.tools.visualvm.heapviewer.model.DataType$RetainedSize$1.run(DataType.java:197)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:395)
	at com.sun.tools.visualvm.heapviewer.model.DataType$RetainedSize.computeValues(DataType.java:196)
	at com.sun.tools.visualvm.heapviewer.java.impl.JavaObjectsView$2.run(JavaObjectsView.java:222)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It seemed to go into the 
```
case ROOT_THREAD_BLOCK:
``` 
in HprofHeap (but that might be off since i am using this for the sources: http://bits.netbeans.org/download/trunk/nightly/2018-03-28_00-02-34/zip/ )

If it helps any, my stack traces are empty (there's no expandable icon) and on visual vm 1.3.9 there's no stack trace output. At first I thought Eclipse MAT had a problem, but I've noticed that both tools don't show the stacktrace.

**Comment by thurka** [comment]
I don't quite understand, what do you mean by 'my stack traces are empty'. You already posted stack trace from VisualVM.

**Comment by thurka** [comment]
See gitter for info about sources.

**Comment by thurka** [comment]
Any update?

**Comment by AnEmortalKid** [comment]
Damn :( I got super sidetracked... I still have the file on my comp but have not gone through getting the oracle support info (for our company)
