### ISSUE TITLE
Cannot connect to Java 10.0.2

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#98]
Version 1.4.1, Windows 10 64-bit

Java 10.0.2 was just released and VisualVM 1.4.1 does not list any local sessions to attach to.

**Comment by cowwoc** [comment]
Logfile contains the following lines that might be relevant:

```
INFO [com.sun.tools.visualvm.jvmstat.JvmstatModelProvider]: getMonitoredVm failed
java.lang.Exception: Could not open PerfMemory
	at sun.misc.Perf.attach(Native Method)
	at sun.misc.Perf.attachImpl(Perf.java:270)
	at sun.misc.Perf.attach(Perf.java:200)
	at sun.jvmstat.perfdata.monitor.protocol.local.PerfDataBuffer.<init>(PerfDataBuffer.java:64)
	at sun.jvmstat.perfdata.monitor.protocol.local.LocalMonitoredVm.<init>(LocalMonitoredVm.java:68)
	at sun.jvmstat.perfdata.monitor.protocol.local.MonitoredHostProvider.getMonitoredVm(MonitoredHostProvider.java:77)
[catch] at com.sun.tools.visualvm.jvmstat.JvmstatModelProvider.getMonitoredVm(JvmstatModelProvider.java:56)
	at com.sun.tools.visualvm.jvmstat.JvmstatModelProvider.createModelFor(JvmstatModelProvider.java:71)
	at com.sun.tools.visualvm.jvmstat.JvmstatModelProvider.createModelFor(JvmstatModelProvider.java:45)
	at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
	at com.sun.tools.visualvm.tools.jvmstat.JvmstatModelFactory.getJvmstatFor(JvmstatModelFactory.java:65)
	at com.sun.tools.visualvm.jvm.JRockitJvmProvider.createModelFor(JRockitJvmProvider.java:49)
	at com.sun.tools.visualvm.jvm.JRockitJvmProvider.createModelFor(JRockitJvmProvider.java:42)
	at com.sun.tools.visualvm.core.model.ModelFactory.getModel(ModelFactory.java:111)
	at com.sun.tools.visualvm.application.jvm.JvmFactory.getJVMFor(JvmFactory.java:65)
	at com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider.processNewApplicationsByPids(JvmstatApplicationProvider.java:199)
	at com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider.registerJvmstatConnection(JvmstatApplicationProvider.java:265)
	at com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider.registerJvmstatConnections(JvmstatApplicationProvider.java:126)
	at com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider.processNewHost(JvmstatApplicationProvider.java:119)
	at com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider.access$000(JvmstatApplicationProvider.java:72)
	at com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider$1.run(JvmstatApplicationProvider.java:98)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

**Comment by cowwoc** [comment]
False alarm. I set `visualvm_jdkhome` to the home directory of JDK 10.0.2 (by default JDK 8 was being used) and restarted Windows and between those two changes the problem went away.

**Comment by thurka** [comment]
Thanks for investigation. The exception looked like JDK/OS problem anyway, so I am not sure we will be able to fix it in VisualVM.
